import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import {setupCentralFixture} from './central-fixture.mjs';
import {browser,pageFor,choose} from './review-workspace-fixture.mjs';
const key=()=>randomBytes(16).toString('hex'),base='/v1/commerce/marketing',screens='/tmp/ezkart-marketing-ui-01a0d643';
const draft=patch=>({name:'Saved autumn campaign',subject:'Tea for a slow morning',preheader:'A small moment for yourself',heading:'Make time for tea',body:'Fresh tea, carefully packed.\n\nTake a moment for yourself.',buttonLabel:'Explore the store',plannedAt:null,audience:{q:'',activity:'all',minSpend:'',minOrders:'',maxOrders:'',lastFrom:'',lastTo:'',location:'',tag:''},archived:false,...patch});
const root=p=>p.locator('[data-marketing]'),form=p=>root(p).locator('[data-marketing-form]');
async function fixture(t,overrides={},commerce={}){
  const f=await setupCentralFixture(t,overrides,commerce),cookie=f.app.adminCookie({supabase_access_token:await f.merchantToken('alice','alice@example.test'),admin_user:{id:'alice',email:'alice@example.test'}});
  const save=(values=draft(),id=null,revision=0)=>f.merchant(base+'/campaigns',{id,revision,requestKey:key(),values},{method:'POST'});
  return {...f,cookie,save,read:id=>f.merchant(base+'/campaigns/'+id)};
}
async function open(p,f){await p.goto(f.app.base+'/cart/admin/?page=marketing');await root(p).getByText('Drafts and your planning calendar are ready.',{exact:true}).waitFor();}
async function saved(p){await form(p).getByRole('button',{name:'Save draft',exact:true}).click();await form(p).getByText('Campaign draft saved.',{exact:true}).waitFor();}
async function edit(p,name){await root(p).locator('.marketing-campaign-card').filter({has:p.getByRole('heading',{name,exact:true})}).getByRole('button',{name:'Edit draft',exact:true}).click();await root(p).getByRole('heading',{name:'Campaign draft',exact:true}).waitFor();}

test('real campaign editing, saved segments, preview, archive and timezone calendar work on desktop and mobile',async t=>{
  const f=await fixture(t),b=await browser(t);await mkdir(screens,{recursive:true});
  const profile=(await f.merchant('/v1/commerce/settings')).profile.values;assert.equal((await f.merchant('/v1/commerce/settings',{kind:'profile',revision:0,requestKey:key(),values:{...profile,timezone:'Asia/Jayapura'}},{method:'POST'})).status,200);
  const segment=await f.merchant('/v1/commerce/customers/segments',{revision:0,requestKey:key(),name:'Repeat tea buyers',filters:{activity:'repeat'},archived:false},{method:'POST'});
  assert.equal(segment.status,200,segment.error);
  for(const width of [1360,390]){
    const p=await pageFor(b,f,width),errors=[];p.on('pageerror',e=>errors.push(e.message));await open(p,f);assert.equal(await root(p).getByText('Active campaigns',{exact:true}).count(),0);
    await root(p).getByRole('button',{name:'New campaign',exact:true}).click();await form(p).getByLabel('Campaign name',{exact:true}).fill('Autumn ritual '+width);
    await form(p).getByLabel('Email subject',{exact:true}).fill('Make time for a cup');await form(p).getByLabel('Inbox preview text',{exact:true}).fill('Fresh leaves, packed with care');await form(p).getByLabel('Email heading',{exact:true}).fill('A small daily ritual');
    await form(p).getByLabel('Email message',{exact:true}).fill('Start slowly.\n\n<img src=x onerror=alert(1)> Fresh tea for your morning.');await form(p).getByLabel('Planned date and time',{exact:true}).fill('2026-10-01T01:30');
    await choose(p,form(p),'segment','Repeat tea buyers');assert.equal(await form(p).locator('select[name="audience.activity"]').inputValue(),'repeat');await saved(p);
    const list=await f.merchant(base+'/campaigns?q='+width),row=list.items[0];assert.equal(row.values.plannedAt,'2026-09-30T16:30:00.000Z');assert.equal(row.values.audience.activity,'repeat');
    await root(p).getByRole('button',{name:'Preview email',exact:true}).click();const preview=root(p).getByRole('dialog',{name:'Email preview',exact:true});await preview.waitFor();
    const frame=preview.frameLocator('iframe');await frame.getByRole('heading',{name:'A small daily ritual'}).waitFor();assert.equal(await frame.locator('img,script').count(),0);assert.equal(await frame.getByText('<img src=x onerror=alert(1)> Fresh tea for your morning.',{exact:false}).count(),1);
    assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:screens+'/preview-'+width+'.png'});await preview.getByRole('button',{name:'Close preview',exact:true}).click();
    await p.reload();await root(p).getByText('Drafts and your planning calendar are ready.',{exact:true}).waitFor();assert.equal(await form(p).getByLabel('Campaign name',{exact:true}).inputValue(),'Autumn ritual '+width);assert.equal(await form(p).getByLabel('Planned date and time',{exact:true}).inputValue(),'2026-10-01T01:30');
    await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:screens+'/editor-'+width+'.png',fullPage:true});await root(p).getByRole('button',{name:'Close editor',exact:true}).click();await root(p).getByRole('button',{name:'Planning calendar',exact:true}).click();await root(p).getByLabel('Calendar month',{exact:true}).fill('2026-10');await root(p).getByRole('button',{name:'Apply filters',exact:true}).click();
    const entry=root(p).getByRole('button',{name:'01:30 · Autumn ritual '+width,exact:true});await entry.waitFor();await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:screens+'/calendar-'+width+'.png',fullPage:true});await entry.click();await form(p).getByLabel('Archive this campaign',{exact:true}).check();await saved(p);
    assert.equal((await f.read(row.id)).campaign.values.archived,true);await form(p).getByLabel('Archive this campaign',{exact:true}).uncheck();await saved(p);
    assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);await p.context().close();
  }
  assert.equal(await f.count('commerce_email_requests'),0);assert.equal((await f.providerCalls()).length,0);
});

test('a lost new-campaign save survives reload, retries the exact reference once and keeps another unfinished draft accessible',async t=>{
  const f=await fixture(t),b=await browser(t),p=await pageFor(b,f,390);await open(p,f);await root(p).getByRole('button',{name:'New campaign',exact:true}).click();await form(p).getByLabel('Campaign name',{exact:true}).fill('First unfinished draft');
  await root(p).getByRole('button',{name:'New campaign',exact:true}).click();await form(p).getByLabel('Campaign name',{exact:true}).fill('Interrupted save');f.control.drop=base+'/campaigns';
  await form(p).getByRole('button',{name:'Save draft',exact:true}).click();await form(p).getByRole('button',{name:'Retry original save',exact:true}).waitFor();await form(p).getByText('The result was not confirmed. Retry the original save.',{exact:true}).waitFor();assert.equal(await f.count('commerce_campaign_changes'),1);
  const first=f.control.calls.filter(c=>c.path===base+'/campaigns'&&c.body).at(-1).body;await p.reload();await form(p).getByRole('button',{name:'Retry original save',exact:true}).waitFor();assert.equal(await form(p).getByLabel('Campaign name',{exact:true}).isDisabled(),true);
  await form(p).getByRole('button',{name:'Retry original save',exact:true}).click();await form(p).getByText('Campaign draft saved.',{exact:true}).waitFor();assert.equal(await f.count('commerce_campaign_changes'),1);assert.deepEqual(f.control.calls.filter(c=>c.path===base+'/campaigns'&&c.body).at(-1).body,first);
  await root(p).getByRole('button',{name:'First unfinished draft · Unsaved draft',exact:true}).click();assert.equal(await form(p).getByLabel('Campaign name',{exact:true}).inputValue(),'First unfinished draft');await saved(p);assert.equal(await f.count('commerce_campaigns'),2);
});

test('concurrent campaigns compare conflicting fields and retain independent copy and audience edits',async t=>{
  const f=await fixture(t),first=await f.save(),id=first.campaign.id,b=await browser(t),a=await pageFor(b,f,390),other=await pageFor(b,f);await open(a,f);await open(other,f);await edit(a,first.campaign.values.name);await edit(other,first.campaign.values.name);
  await form(a).getByLabel('Email subject',{exact:true}).fill('My subject');await form(a).getByLabel('Email message',{exact:true}).fill('My carefully written message.');
  await form(other).getByLabel('Email subject',{exact:true}).fill('Other subject');await form(other).getByLabel('Customer tag',{exact:true}).fill('loyal');await saved(other);
  await form(a).getByRole('button',{name:'Save draft',exact:true}).click();const comparison=root(a).getByRole('dialog',{name:'Compare your campaign',exact:true});await comparison.waitFor();await choose(a,comparison,'merge-subject','My draft value');await a.screenshot({path:screens+'/comparison-390.png'});await comparison.getByRole('button',{name:'Use compared changes',exact:true}).click();
  assert.equal(await form(a).getByLabel('Customer tag',{exact:true}).inputValue(),'loyal');await saved(a);const savedRow=(await f.read(id)).campaign;assert.equal(savedRow.revision,3);assert.equal(savedRow.values.subject,'My subject');assert.equal(savedRow.values.body,'My carefully written message.');assert.equal(savedRow.values.audience.tag,'loyal');
  await root(a).getByRole('button',{name:'Saved history',exact:true}).click();const h=root(a).getByRole('dialog',{name:'Campaign history',exact:true});await h.getByText('3 saved changes shown.',{exact:true}).waitFor();await h.locator('summary').first().click();await h.getByText('My carefully written message.',{exact:true}).waitFor();
});

test('the private proxy binds account, store, CSRF and route parameters and suppresses a late response after sign-in changes',async t=>{
  const f=await fixture(t),b=await browser(t),p=await pageFor(b,f);await open(p,f);
  const headers=await p.evaluate(()=>({'X-Ezkart-CSRF':document.body.dataset.adminCsrfToken,'X-Ezkart-Marketing-Account':document.body.dataset.adminReviewAccount,'X-Ezkart-Marketing-Store':document.querySelector('[data-marketing]').dataset.store}));headers.Cookie='ezkart_admin='+f.cookie.value;
  const url=path=>'/cart/admin/?cloud='+encodeURIComponent(path),body={id:null,revision:0,requestKey:key(),values:draft()};
  assert.equal((await f.app.request(url(base+'/workspace'),undefined,{...headers,'X-Ezkart-CSRF':'wrong'})).status,401);assert.equal((await f.app.request(url(base+'/workspace'),undefined,{...headers,'X-Ezkart-Marketing-Account':'bob'})).status,401);assert.equal((await f.app.request(url(base+'/workspace'),undefined,{...headers,'X-Ezkart-Marketing-Store':'seller_bob'})).status,409);
  assert.equal((await f.app.request(url(base+'/campaigns'),body,{...headers,Origin:'https://other.example'})).status,403);
  for(const target of ['/campaigns?state=active&state=all','/campaigns?q[]=secret','/campaigns?environment=production','/workspace?store=seller_bob','/campaigns?month=2026-13','/campaigns?cursor=x#fragment','/campaigns?','/workspace/cmp_'+'a'.repeat(32)])assert.equal((await f.app.request(url(base+target),undefined,headers)).status,400,target);
  for(const path of ['/cart/admin/marketing.php','/cart/admin/marketing-proxy.php']){const response=await fetch(f.app.base+path);assert.equal(response.status,404);assert.equal(await response.text(),'');}
  f.control.afterResponse=async path=>{if(path!==base+'/campaigns'||!f.control.calls.at(-1)?.body)return;f.control.afterResponse=null;f.app.cli(`define('EZ_CUSTOMER_SESSION_BRIDGE', true); session_id('${f.cookie.value}'); require '${process.cwd()}/cart/admin/index.php'; $_SESSION['admin_user']=['id'=>'bob','email'=>'bob@example.test']; $_SESSION['csrf_token']='changed'; session_write_close();`);};
  await root(p).getByRole('button',{name:'New campaign',exact:true}).click();await form(p).getByLabel('Campaign name',{exact:true}).fill('Saved before sign-in changed');await form(p).getByRole('button',{name:'Save draft',exact:true}).click();await root(p).getByRole('link',{name:'Reload sign-in',exact:true}).waitFor();assert.equal(await root(p).locator('input,iframe').count(),0);assert.equal(await f.count('commerce_campaigns'),1);
});

test('audience and history paging retain prior rows after failures and ignore results for a closed dialog',async t=>{
  const f=await fixture(t),b=await browser(t);await f.product('campaign_tea',1000);
  for(let n=0;n<27;n++){const result=await f.create(f.input({items:[{productId:'campaign_tea',quantity:1,expectedPrice:20000,expectedWeightGrams:100}],customer:{name:'Customer '+n,email:'customer'+n+'@example.test',phone:'081234567890'}}));assert.equal(result.status,200,result.error);}
  const one=await f.save(),id=one.campaign.id;for(let n=1;n<23;n++)assert.equal((await f.save(draft({name:'Campaign version '+n}),id,n)).status,200);
  const p=await pageFor(b,f,390);await open(p,f);await edit(p,'Campaign version 22');await root(p).getByRole('button',{name:'Preview audience',exact:true}).click();const a=root(p).getByRole('dialog',{name:'Audience preview',exact:true});await a.getByText('25 matching customers shown.',{exact:true}).waitFor();
  let failAudience=true,failHistory=true;await p.route('**/cart/admin/?cloud=*',async route=>{const path=new URL(route.request().url()).searchParams.get('cloud');
    if(failAudience&&path===base+'/audience'&&route.request().postDataJSON()?.cursor){failAudience=false;await route.fulfill({status:503,json:{ok:false,error:'Audience interrupted'}});return;}
    if(failHistory&&path?.startsWith(base+'/campaigns/'+id+'/history?cursor=')){failHistory=false;await route.fulfill({status:503,json:{ok:false,error:'History interrupted'}});return;}await route.continue();});
  await a.getByRole('button',{name:'Load more customers',exact:true}).click();await a.getByText('Audience interrupted',{exact:true}).waitFor();assert.equal(await a.locator('li').count(),25);await a.getByRole('button',{name:'Try audience again',exact:true}).click();await a.getByText('27 matching customers shown.',{exact:true}).waitFor();assert.equal(await a.getByText('No permission recorded',{exact:false}).count(),27);await p.screenshot({path:screens+'/audience-390.png'});await a.getByRole('button',{name:'Close audience',exact:true}).click();
  await root(p).getByRole('button',{name:'Saved history',exact:true}).click();const h=root(p).getByRole('dialog',{name:'Campaign history',exact:true});await h.getByText('20 saved changes shown.',{exact:true}).waitFor();await h.getByRole('button',{name:'Load older changes',exact:true}).click();await h.getByText('History interrupted',{exact:true}).waitFor();assert.equal(await h.locator('li').count(),20);await h.getByRole('button',{name:'Try history again',exact:true}).click();await h.getByText('23 saved changes shown.',{exact:true}).waitFor();await h.getByRole('button',{name:'Close history',exact:true}).click();
  let release;const barrier=new Promise(resolve=>{release=resolve;});let entered;const started=new Promise(resolve=>{entered=resolve;});
  await p.route('**/cart/admin/?cloud=*',async route=>{const path=new URL(route.request().url()).searchParams.get('cloud');if(path===base+'/audience'){entered();await barrier;}await route.continue();});
  await root(p).getByRole('button',{name:'Preview audience',exact:true}).click();await started;await a.getByRole('button',{name:'Close audience',exact:true}).click();await root(p).getByRole('button',{name:'New campaign',exact:true}).click();const arrived=p.waitForResponse(r=>new URL(r.url()).searchParams.get('cloud')===base+'/audience');release();await form(p).getByLabel('Campaign name',{exact:true}).fill('A different campaign');await arrived;assert.equal(await a.isVisible(),false);assert.equal(await form(p).getByLabel('Campaign name',{exact:true}).inputValue(),'A different campaign');
});

test('storage failures and changed pending intent block writes instead of silently creating another save',async t=>{
  const f=await fixture(t),b=await browser(t),p=await pageFor(b,f);await p.addInitScript(()=>{Storage.prototype.setItem=()=>{throw Error('Storage unavailable');};});await open(p,f);await root(p).getByRole('button',{name:'New campaign',exact:true}).click();await form(p).getByLabel('Campaign name',{exact:true}).fill('Keep this draft safe');assert.equal(await form(p).getByRole('button',{name:'Save draft',exact:true}).isDisabled(),true);assert.equal(await f.count('commerce_campaigns'),0);await p.context().close();
  const other=await pageFor(b,f);await open(other,f);await root(other).getByRole('button',{name:'New campaign',exact:true}).click();await form(other).getByLabel('Campaign name',{exact:true}).fill('Original intent');f.control.drop=base+'/campaigns';await form(other).getByRole('button',{name:'Save draft',exact:true}).click();await form(other).getByText('The result was not confirmed. Retry the original save.',{exact:true}).waitFor();
  const before=await other.evaluate(()=>{const k=Object.keys(sessionStorage).find(k=>k.startsWith('ezkart.marketing.v1:'));const v=JSON.parse(sessionStorage.getItem(k));v.entries[0].pending.values.name='Changed intent';sessionStorage.setItem(k,JSON.stringify(v));return sessionStorage.getItem(k);});
  await other.reload();await root(other).getByText('The browser draft or pending save could not be verified. Keep this tab open and copy your changes before clearing its session storage.',{exact:true}).waitFor();await root(other).getByRole('button',{name:'New campaign',exact:true}).click();await form(other).getByLabel('Campaign name',{exact:true}).fill('Do not overwrite the receipt');assert.equal(await form(other).getByRole('button',{name:'Save draft',exact:true}).isDisabled(),true);assert.equal(await other.evaluate(()=>sessionStorage.getItem(Object.keys(sessionStorage).find(k=>k.startsWith('ezkart.marketing.v1:')))),before);assert.equal(await f.count('commerce_campaign_changes'),1);
});

test('viewers can inspect saved drafts during the hold and account switches never restore another account’s browser draft',async t=>{
  const f=await fixture(t,{EZKART_COMMERCE_STORAGE:'legacy'},{bindings:{COMMERCE_STORAGE:'legacy'}}),one=await f.save(),b=await browser(t),p=await pageFor(b,f,390);await open(p,f);await edit(p,one.campaign.values.name);await form(p).getByLabel('Email subject',{exact:true}).fill('Private unsaved subject');assert.equal(await root(p).getByRole('button',{name:'Preview audience',exact:true}).isDisabled(),true);
  await f.db.prepare("UPDATE seller_memberships SET role='viewer' WHERE auth_user_id='alice'").run();await p.reload();await root(p).getByText('Drafts and your planning calendar are ready.',{exact:true}).waitFor();assert.equal(await form(p).getByLabel('Email subject',{exact:true}).isDisabled(),true);assert.equal(await form(p).getByLabel('Email subject',{exact:true}).inputValue(),'Private unsaved subject');
  const bob=f.app.adminCookie({supabase_access_token:await f.merchantToken('bob','bob@example.test'),admin_user:{id:'bob',email:'bob@example.test'}});await p.context().addCookies([bob]);await p.reload();await root(p).getByText('Drafts and your planning calendar are ready.',{exact:true}).waitFor();assert.equal(await root(p).locator('[data-marketing-editor]').isVisible(),false);assert.equal(await root(p).getByText('Private unsaved subject',{exact:true}).count(),0);assert.equal(await root(p).locator('.marketing-campaign-card').count(),0);
});

test('an unverified save response retains the original request until the saved receipt can be checked',async t=>{
  const f=await fixture(t),b=await browser(t),p=await pageFor(b,f,390);await open(p,f);let alter=true;
  await p.route('**/cart/admin/?cloud=*',async route=>{if(alter&&new URL(route.request().url()).searchParams.get('cloud')===base+'/campaigns'&&route.request().method()==='POST'){
    alter=false;const response=await route.fetch(),data=await response.json();data.receipt.values.subject='A mismatched acknowledgement';await route.fulfill({response,json:data});return;}await route.continue();});
  await root(p).getByRole('button',{name:'New campaign',exact:true}).click();await form(p).getByLabel('Campaign name',{exact:true}).fill('Verify this receipt');await form(p).getByRole('button',{name:'Save draft',exact:true}).click();await form(p).getByText('The save response could not be verified. Retry the original save.',{exact:true}).waitFor();
  const first=f.control.calls.filter(c=>c.path===base+'/campaigns'&&c.body).at(-1).body;assert.equal(await f.count('commerce_campaign_changes'),1);assert.equal(await form(p).getByRole('button',{name:'Discard new draft',exact:true}).isDisabled(),true);
  await p.reload();await form(p).getByRole('button',{name:'Retry original save',exact:true}).waitFor();await form(p).getByRole('button',{name:'Retry original save',exact:true}).click();await form(p).getByText('Campaign draft saved.',{exact:true}).waitFor();assert.deepEqual(f.control.calls.filter(c=>c.path===base+'/campaigns'&&c.body).at(-1).body,first);assert.equal(await f.count('commerce_campaign_changes'),1);
});

test('an interrupted draft reopening retains its visible error and local edits; keyboard preview and explicit discard work',async t=>{
  const f=await fixture(t),first=await f.save(),id=first.campaign.id,b=await browser(t),p=await pageFor(b,f,390);await open(p,f);await edit(p,first.campaign.values.name);await form(p).getByLabel('Email subject',{exact:true}).fill('Retain this unsaved subject');
  let fail=true;await p.route('**/cart/admin/?cloud=*',async route=>{if(fail&&new URL(route.request().url()).searchParams.get('cloud')===base+'/campaigns/'+id){fail=false;await route.fulfill({status:503,json:{ok:false,error:'Draft temporarily unavailable'}});return;}await route.continue();});
  await p.reload();await root(p).getByText('Draft temporarily unavailable',{exact:true}).waitFor();await root(p).getByText('1 campaign shown.',{exact:true}).waitFor();assert.equal(await root(p).getByText('Draft temporarily unavailable',{exact:true}).count(),1);assert.equal(await root(p).locator('[data-marketing-editor]').isVisible(),false);
  await root(p).getByRole('button',{name:first.campaign.values.name+' · Unsaved draft',exact:true}).click();await root(p).getByText('Campaign ready.',{exact:true}).waitFor();assert.equal(await form(p).getByLabel('Email subject',{exact:true}).inputValue(),'Retain this unsaved subject');
  const previewButton=root(p).getByRole('button',{name:'Preview email',exact:true});await previewButton.focus();await p.keyboard.press('Enter');const preview=root(p).getByRole('dialog',{name:'Email preview',exact:true});await preview.waitFor();await p.keyboard.press('Escape');assert.equal(await preview.isVisible(),false);assert.equal(await previewButton.evaluate(n=>n===document.activeElement),true);
  await root(p).getByRole('button',{name:'New campaign',exact:true}).click();await form(p).getByLabel('Campaign name',{exact:true}).fill('Discard this local draft');await form(p).getByRole('button',{name:'Discard new draft',exact:true}).click();const discard=root(p).getByRole('dialog',{name:'Discard this new draft?',exact:true});await discard.waitFor();await discard.getByRole('button',{name:'Keep editing',exact:true}).click();assert.equal(await form(p).getByLabel('Campaign name',{exact:true}).inputValue(),'Discard this local draft');
  await form(p).getByRole('button',{name:'Discard new draft',exact:true}).click();await discard.getByRole('button',{name:'Discard draft',exact:true}).click();assert.equal(await root(p).locator('[data-marketing-editor]').isVisible(),false);assert.equal(await root(p).getByRole('button',{name:'Discard this local draft · Unsaved draft',exact:true}).count(),0);assert.equal(await root(p).getByRole('button',{name:first.campaign.values.name+' · Unsaved draft',exact:true}).count(),1);assert.equal(await f.count('commerce_campaign_changes'),1);
});
