import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {saveShippingSettings} from '../../cloudflare/ezkart-api/src/shipping-settings.js';
import {setupCentralFixture} from './central-fixture.mjs';
import {browser,pageFor} from './review-workspace-fixture.mjs';
const key=()=>randomBytes(16).toString('hex');
test('first bank setup uses verified sign-in without email codes; saved banks and enabled two-step remain protected',async t=>{
 const f=await setupCentralFixture(t,{}, {declaredOnboarding:false}),b=await browser(t);
 const address={id:'addr_'+'a'.repeat(32),label:'Warehouse',name:'Alice',phone:'081234567890',email:'',organization:'',address:'Jalan Warehouse 18',location:'Jakarta',postalCode:'54321',note:'',coordinate:{latitude:-6.2,longitude:106.8}};
 if(!await f.db.prepare('SELECT revision FROM seller_shipping_settings WHERE seller_id=?').bind('seller_alice').first()) await saveShippingSettings({DB:f.db},{sellerId:'seller_alice',id:'alice',role:'owner'},{revision:0,requestKey:key(),configuration:{addresses:[address],pickupAddressId:address.id,returnAddressId:address.id,couriers:['jne']}});
 const token=await f.merchantToken('alice','alice@example.test');
 await writeFile(join(f.app.directory,'auth-response.json'),JSON.stringify({user:{id:'alice',email:'alice@example.test'},wallet_tokens:{access_token:token,refresh_token:'fixture-refresh',expires_in:3600}}));
 const cookie=f.app.adminCookie({supabase_access_token:token,admin_user:{id:'alice',email:'alice@example.test'}});
 const p=await pageFor(b,f,1360,cookie),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(f.app.base+'/cart/admin/?page=onboarding');
 await p.locator('[data-onboarding-profile] input[name=legalName]').waitFor();
 await p.waitForFunction(()=>!document.querySelector('[data-onboarding-step=profile]').disabled);
 assert.equal(await p.getByRole('heading',{name:'Verify to open bank details'}).isVisible(),false);
 await p.getByLabel('Full legal name',{exact:true}).fill('Alice Seller');
 await p.getByLabel('Date of birth',{exact:true}).fill('1990-01-01');
 await p.locator('[name=ageConfirmed]').check();await p.getByLabel('Phone number',{exact:true}).fill('081234567890');
 await p.getByRole('button',{name:'Save and continue',exact:true}).click();
 await p.getByRole('heading',{name:'Where will orders travel from?'}).waitFor();
 const request=async(action,body={})=>f.app.request('/cart/admin/?wallet='+action,body,{Cookie:(await p.context().cookies()).map(c=>c.name+'='+c.value).join('; '),'X-Ezkart-Csrf':await p.locator('body').getAttribute('data-admin-csrf-token'),'X-Ezkart-Wallet-Account':'alice','X-Ezkart-Wallet-Store':'seller_alice'}).then(r=>({status:r.status,...r.data}));
 let r=await request('onboarding_read');assert.equal(r.status,200,r.error);assert.equal(r.onboarding.profile.legalName,'Alice Seller');assert.equal(r.onboarding.bank,null);assert.ok(r.banks.length);assert.equal(r.onboarding.bankSetupAllowed,true);
 assert.equal((await request('onboarding_bank_read')).status,200);
 // A currently enrolled authenticator still protects first bank setup.
 await writeFile(join(f.app.directory,'auth-response.json'),JSON.stringify({user:{id:'alice',email:'alice@example.test',factors:[{id:'11111111-1111-4111-8111-111111111111',factor_type:'totp',status:'verified'}]}}));
 assert.equal((await request('onboarding_bank_read')).status,401);
 assert.equal((await request('onboarding_bank',{revision:0,requestKey:key(),bank:{code:'CENAIDJA',accountNumber:'1234567890',channel:'BI_FAST'}})).status,401);
 await writeFile(join(f.app.directory,'auth-response.json'),JSON.stringify({user:{id:'alice',email:'alice@example.test'},wallet_tokens:{access_token:token,refresh_token:'fixture-refresh',expires_in:3600}}));
 await p.getByRole('button',{name:'Confirm and continue',exact:true}).click();
 await p.getByLabel('Account number',{exact:true}).waitFor();
 assert.equal(await p.getByLabel('Email code',{exact:true}).isVisible(),false);
 assert.equal((await request('onboarding_read')).onboarding.shipping.confirmed,true);
 await p.goto(f.app.base+'/cart/admin/?page=onboarding&step=bank');
 await p.locator('[data-onboarding-bank]').waitFor();
 r=await request('onboarding_bank_read');assert.equal(r.status,200,r.error);assert.ok(r.banks.length);
 const bank=r.banks.find(x=>x.channels.includes('BI_FAST'));
 await p.locator('[data-onboarding-bank] select[name=code]').selectOption(bank.code);
 await p.getByLabel('Account number',{exact:true}).fill('1234567890');
 await p.locator('[data-onboarding-bank] select[name=channel]').selectOption('BI_FAST');
 for(const width of [1360,390]){await p.setViewportSize({width,height:940});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'/tmp/ezkart-first-bank-'+width+'.png',fullPage:true,animations:'disabled'});}
 await p.setViewportSize({width:1360,height:940});
 // A lost save response must replay the first bank without creating a review.
 f.control.drop='/internal/commerce/onboarding';
 await p.getByRole('button',{name:'Save bank destination',exact:true}).click();
 await p.getByRole('heading',{name:"You're all set!",exact:true}).waitFor();
 assert.equal(new URL(p.url()).searchParams.get('step'),'complete');
 assert.equal(await p.locator('.store-switcher').count(),0);
 await p.screenshot({path:'/tmp/ezkart-onboarding-complete-1360.png',fullPage:true});
 let release;const held=new Promise(resolve=>release=resolve);
 await p.route('**/?wallet=onboarding_read',async route=>{await held;await route.continue();});
 await p.reload({waitUntil:'domcontentloaded'});
 assert.equal(await p.locator('[data-onboarding-panel=profile]').isHidden(),true);
 release();await p.getByRole('heading',{name:"You're all set!",exact:true}).waitFor();
 await p.unroute('**/?wallet=onboarding_read');
 await p.setViewportSize({width:390,height:940});await p.reload();await p.getByRole('heading',{name:"You're all set!",exact:true}).waitFor();
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await p.screenshot({path:'/tmp/ezkart-onboarding-complete-390.png',fullPage:true});
 r=await request('onboarding_read');assert.equal(r.onboarding.bank,null);assert.equal(r.onboarding.bankSaved,true);assert.equal(r.onboarding.bankRevision,0);
 await p.getByRole('button',{name:'Your bank'}).click();
 await p.getByRole('heading',{name:'Verify to open bank details'}).waitFor();
 assert.equal((await request('onboarding_bank_read')).status,401);
 for(const revision of [0,1])assert.equal((await request('onboarding_bank',{revision,requestKey:key(),reason:'Attempt to replace a saved bank without fresh verification.',bank:{code:bank.code,accountNumber:'9995555555',channel:'BI_FAST'}})).status,401);
 assert.equal(await f.count('seller_bank_change_requests'),0);
 assert.equal((await request('refresh')).status,401,'Initial bank setup must not unlock Wallet');
 await p.getByRole('button',{name:'Send email code',exact:true}).click();
 await p.getByLabel('Email code',{exact:true}).fill('654321');
 await p.getByRole('button',{name:'Verify bank details',exact:true}).click();
 await p.getByRole('button',{name:'Request bank change',exact:true}).waitFor();
 await p.locator('[data-onboarding-bank] select[name=code]').selectOption(bank.code);
 await p.getByLabel('Account number',{exact:true}).fill('9995555555');
 await p.locator('[data-onboarding-bank] select[name=channel]').selectOption('BI_FAST');
 await p.getByLabel('Why are you changing your bank?').fill('My previous account is closing and I need a replacement.');
 await p.getByRole('button',{name:'Request bank change',exact:true}).click();
 await p.waitForFunction(()=>document.querySelector('[data-bank-change-status]').textContent.includes('pending'));
 assert.equal(await p.getByRole('button',{name:'Request bank change',exact:true}).isDisabled(),true);
 r=await request('onboarding_bank_read');assert.equal(r.onboarding.bank.revision,1);assert.equal(r.onboarding.bank.accountSuffix,'7890');assert.equal(r.onboarding.bankChange.status,'pending');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await p.screenshot({path:'/tmp/ezkart-bank-review-390.png',fullPage:true});
 await p.setViewportSize({width:1360,height:940});await p.screenshot({path:'/tmp/ezkart-bank-review-1360.png',fullPage:true});
 r=await request('onboarding_read');assert.equal(r.onboarding.bankChange,null);
 await p.setViewportSize({width:390,height:940});await p.getByRole('button',{name:'About you'}).click();
 assert.equal(await p.getByLabel('Full legal name',{exact:true}).inputValue(),'Alice Seller');
 // Expiry must affect only the banking section and preserve an unsaved profile.
 await p.getByLabel('Full legal name',{exact:true}).fill('Alice Unsaved');
 const currentCookie=(await p.context().cookies()).find(c=>c.name==='ezkart_admin');
 f.app.cli(`$_COOKIE['ezkart_admin']='${currentCookie.value}'; define('EZ_CUSTOMER_SESSION_BRIDGE',true); require ${JSON.stringify(process.cwd()+'/cart/admin/index.php')}; $_SESSION['wallet_access']['expires_at']=time()-1; session_write_close();`);
 assert.equal((await request('onboarding_bank_read')).status,401);
 assert.equal((await request('onboarding_read')).status,200);
 await p.evaluate(()=>document.querySelector('[data-wallet-content]').dataset.walletSeconds='0');
 await p.addScriptTag({url:f.app.base+'/cart/admin/wallet-access.js'});
 await p.locator('[data-onboarding-bank-locked]').waitFor({state:'attached'});
 await p.waitForFunction(()=>document.querySelector('[data-wallet-content]').hidden);

 assert.equal(await p.getByLabel('Full legal name',{exact:true}).inputValue(),'Alice Unsaved');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await p.screenshot({path:'/tmp/ezkart-onboarding-profile-no-verification.png',fullPage:true});
 assert.deepEqual(errors,[]);
});
