import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {saveShippingSettings} from '../../cloudflare/ezkart-api/src/shipping-settings.js';
import {setupCentralFixture} from './central-fixture.mjs';
import {browser,pageFor} from './review-workspace-fixture.mjs';
const key=()=>randomBytes(16).toString('hex');
test('profile and address setup work without Wallet verification; bank reads and writes remain protected',async t=>{
 const f=await setupCentralFixture(t,{}, {declaredOnboarding:false}),b=await browser(t);
 const address={id:'addr_'+'a'.repeat(32),label:'Warehouse',name:'Alice',phone:'081234567890',email:'',organization:'',address:'Jalan Warehouse 18',location:'Jakarta',postalCode:'54321',note:'',coordinate:{latitude:-6.2,longitude:106.8}};
 if(!await f.db.prepare('SELECT revision FROM seller_shipping_settings WHERE seller_id=?').bind('seller_alice').first()) await saveShippingSettings({DB:f.db},{sellerId:'seller_alice',id:'alice',role:'owner'},{revision:0,requestKey:key(),configuration:{addresses:[address],pickupAddressId:address.id,returnAddressId:address.id,couriers:['jne']}});
 const token=await f.merchantToken('alice','alice@example.test');
 await writeFile(join(f.app.directory,'auth-response.json'),JSON.stringify({user:{id:'alice',email:'alice@example.test'},wallet_tokens:{access_token:token,refresh_token:'fixture-refresh',expires_in:3600}}));
 const cookie=f.app.adminCookie({supabase_access_token:token,admin_user:{id:'alice',email:'alice@example.test'}});
 const p=await pageFor(b,f,1360,cookie),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(f.app.base+'/cart/admin/?page=onboarding');
 await p.locator('[data-onboarding-profile] input[name=legalName]').waitFor();
 await p.waitForFunction(()=>!document.querySelector('[data-onboarding-step=profile]').disabled);
 assert.equal(await p.getByRole('heading',{name:'Verify to open bank details'}).isVisible(),false);
 await p.getByLabel('Full legal name',{exact:true}).fill('Alice Seller');
 await p.getByLabel('Date of birth',{exact:true}).fill('1990-01-01');
 await p.locator('[name=ageConfirmed]').check();await p.getByLabel('Phone number',{exact:true}).fill('081234567890');
 await p.getByRole('button',{name:'Save and continue',exact:true}).click();
 await p.getByRole('heading',{name:'Where will orders travel from?'}).waitFor();
 const request=async(action,body={})=>f.app.request('/cart/admin/?wallet='+action,body,{Cookie:(await p.context().cookies()).map(c=>c.name+'='+c.value).join('; '),'X-Ezkart-Csrf':await p.locator('body').getAttribute('data-admin-csrf-token'),'X-Ezkart-Wallet-Account':'alice','X-Ezkart-Wallet-Store':'seller_alice'}).then(r=>({status:r.status,...r.data}));
 let r=await request('onboarding_read');assert.equal(r.status,200,r.error);assert.equal(r.onboarding.profile.legalName,'Alice Seller');assert.equal(r.onboarding.bank,null);assert.deepEqual(r.banks,[]);
 assert.equal((await request('onboarding_bank_read')).status,401);
 assert.equal((await request('onboarding_bank',{revision:0,requestKey:key(),bank:{code:'CENAIDJA',accountNumber:'1234567890',channel:'BI_FAST'}})).status,401);
 await p.getByRole('button',{name:'Confirm and continue',exact:true}).click();
 await p.getByRole('heading',{name:'Verify to open bank details'}).waitFor();
 assert.equal((await request('onboarding_read')).onboarding.shipping.confirmed,true);
 // Direct step links must still protect banking, while profile stays reachable.
 await p.goto(f.app.base+'/cart/admin/?page=onboarding&step=bank');await p.getByRole('heading',{name:'Verify to open bank details'}).waitFor();
 await p.getByRole('button',{name:'Send email code',exact:true}).click();
 await p.getByLabel('Email code',{exact:true}).fill('654321');
 await p.getByRole('button',{name:'Verify bank details',exact:true}).click();
 await p.locator('[data-onboarding-bank]').waitFor();
 r=await request('onboarding_bank_read');assert.equal(r.status,200,r.error);assert.ok(r.banks.length);
 const bank=r.banks.find(x=>x.channels.includes('BI_FAST'));
 r=await request('onboarding_bank',{revision:r.onboarding.bankRevision,requestKey:key(),bank:{code:bank.code,accountNumber:'1234567890',channel:'BI_FAST'}});assert.equal(r.status,200,r.error);assert.equal(r.onboarding.bank.accountSuffix,'7890');
 r=await request('onboarding_read');assert.equal(r.onboarding.bank,null);assert.equal(r.onboarding.bankSaved,true);assert.equal(r.onboarding.bankRevision,0);
 await p.setViewportSize({width:390,height:940});await p.getByRole('button',{name:'About you'}).click();
 assert.equal(await p.getByLabel('Full legal name',{exact:true}).inputValue(),'Alice Seller');
 // Expiry must affect only the banking section and preserve an unsaved profile.
 await p.getByLabel('Full legal name',{exact:true}).fill('Alice Unsaved');
 const currentCookie=(await p.context().cookies()).find(c=>c.name==='ezkart_admin');
 f.app.cli(`$_COOKIE['ezkart_admin']='${currentCookie.value}'; define('EZ_CUSTOMER_SESSION_BRIDGE',true); require ${JSON.stringify(process.cwd()+'/cart/admin/index.php')}; $_SESSION['wallet_access']['expires_at']=time()-1; session_write_close();`);
 assert.equal((await request('onboarding_bank_read')).status,401);
 assert.equal((await request('onboarding_read')).status,200);
 await p.evaluate(()=>document.querySelector('[data-wallet-content]').dataset.walletSeconds='0');
 await p.addScriptTag({url:f.app.base+'/cart/admin/wallet-access.js'});
 await p.locator('[data-onboarding-bank-locked]').waitFor({state:'attached'});
 await p.waitForFunction(()=>document.querySelector('[data-wallet-content]').hidden);

 assert.equal(await p.getByLabel('Full legal name',{exact:true}).inputValue(),'Alice Unsaved');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await p.screenshot({path:'/tmp/ezkart-onboarding-profile-no-verification.png',fullPage:true});
 assert.deepEqual(errors,[]);
});
