import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {setupCentralFixture} from './central-fixture.mjs';
import {browser,pageFor} from './review-workspace-fixture.mjs';
test('seller notifications open alerts, preserve re-scan retry and gray affected pages at desktop/mobile',async t=>{
 const f=await setupCentralFixture(t),b=await browser(t),cookie=f.app.adminCookie({supabase_access_token:await f.merchantToken('alice','alice@example.test'),admin_user:{id:'alice',email:'alice@example.test'}}),p=await pageFor(b,f,1360,cookie);
 const item={id:'jcase_'+'a'.repeat(32),pageId:'notebook',name:'Notebook launch',reason:'Remove the request for bank credentials.',deadlineAt:new Date(Date.now()+2*86400000).toISOString(),findings:[{quote:'Send your bank password',explanation:'Customers must not disclose secret credentials.'}],remainingRescans:3,canRescan:true,revision:'revised-page',state:'changes_required',href:'/cart/admin/?page=alerts&alert=jcase_'+'a'.repeat(32),editHref:'?page=sites&edit=notebook.ezkart.site'};let items=[item],calls=[],drop=true;
 await p.route('**/cart/admin/?cloud=*',async route=>{const path=new URL(route.request().url()).searchParams.get('cloud');if(path?.endsWith('/alerts'))return route.fulfill({json:{ok:true,items}});if(path?.endsWith('/alert-rescan')){calls.push(route.request().postDataJSON());if(drop){drop=false;return route.abort();}items=[{...item,remainingRescans:2,canRescan:false,state:'rescan_queued'}];return route.fulfill({json:{ok:true,items}});}return route.continue();});
 await p.goto(f.app.base+'/cart/admin/?page=notifications');await p.getByRole('link',{name:'View reason and resolve',exact:true}).click();await p.getByRole('heading',{name:'Alerts',exact:true}).waitFor();assert.equal(await p.getByRole('link',{name:'Jev page reviews',exact:true}).count(),0);assert.equal(await p.getByRole('button',{name:'Run Jev review'}).count(),0);
 await p.getByRole('button',{name:'Request re-scan',exact:true}).click();await p.getByRole('button',{name:'Retry re-scan request',exact:true}).waitFor();await p.reload();await p.getByRole('button',{name:'Retry re-scan request',exact:true}).click();await p.getByText('Re-scan requested. Waiting for a reviewer; the page remains unavailable.',{exact:true}).waitFor();assert.deepEqual(calls[0],calls[1]);
 await mkdir('/tmp/ezkart-seller-alerts',{recursive:true});for(const width of [1360,390]){await p.setViewportSize({width,height:1000});await p.reload();await p.getByRole('heading',{name:'Alerts',exact:true}).waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'/tmp/ezkart-seller-alerts/alerts-'+width+'.png',fullPage:true});}
 // Exercise the same library-card observer without modifying a seller's saved pages.
 await p.goto(f.app.base+'/cart/admin/?page=sites');await p.locator('[data-project-grid]').waitFor();await p.evaluate(()=>{const card=document.createElement('article');card.className='landing-project-card';card.dataset.projectCard='';card.dataset.siteUrl='notebook.ezkart.site';card.innerHTML='<span class="landing-project-preview">Saved preview</span><span class="project-status">Published</span>';document.querySelector('[data-project-grid]').append(card);});
 await p.locator('[data-site-url="notebook.ezkart.site"].has-content-alert').waitFor();await p.locator('[data-site-url="notebook.ezkart.site"]').getByRole('link',{name:'View reason and resolve'}).waitFor();assert.match(await p.locator('[data-site-url="notebook.ezkart.site"] .landing-project-preview').evaluate(n=>getComputedStyle(n).filter),/grayscale/);
 items=[];await p.goto(f.app.base+'/cart/admin/?page=jev');await p.getByText('No unresolved alerts.',{exact:true}).waitFor();assert.equal(await p.getByRole('heading',{name:'Alerts',exact:true}).count(),1);
});
