import test from 'node:test';import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';import {generateKeyPairSync} from 'node:crypto';import {mkdtemp,rm,stat,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {fileURLToPath} from 'node:url';
const php=process.env.PHP_BINARY||'php',fixture=fileURLToPath(new URL('./treasury-bank-fixture.php',import.meta.url));
const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048,privateKeyEncoding:{type:'pkcs8',format:'pem'},publicKeyEncoding:{type:'spki',format:'pem'}});
const credentials={environment:'sandbox',clientId:'MCH-fixture-only',secretKey:'fixture-only-secret',privateKey};
const binding={environment:'sandbox',partnerReferenceNo:'EZK-TREASURY-S-'+'a'.repeat(40),fromAccount:'1234567890',beneficiaryBankCode:'CENAIDJA',beneficiaryAccountNumber:'001234567890',amount:'1000',channel:'BI_FAST',inquiryExternalId:'0'.repeat(31)+'1',paymentExternalId:'0'.repeat(31)+'2'};
const response=body=>({body:JSON.stringify(body)}),token=response({responseCode:'2007300',tokenType:'Bearer',accessToken:'fixture-token',expiresIn:900});
const inquiry=response({responseCode:'2000000',referenceNo:'fixture-inquiry',partnerReferenceNo:binding.partnerReferenceNo,type:'BANK_ACCOUNT',channel:binding.channel,fromAccount:binding.fromAccount,beneficiaryBankCode:binding.beneficiaryBankCode,beneficiaryAccountNumber:binding.beneficiaryAccountNumber,beneficiaryAccountName:'Fixture Ezkart Company',amount:{value:'1000.00',currency:'IDR'}});
async function run(t,input={},flags={}){
 const dir=await mkdtemp(join(tmpdir(),'treasury-private-'));t.after(()=>rm(dir,{recursive:true,force:true}));
 const r=spawnSync(php,['-n',fixture],{input:JSON.stringify({credentials,binding,responses:[token,inquiry],...input}),encoding:'utf8',env:{...process.env,EZKART_DEPLOYMENT_ENVIRONMENT:'test',EZKART_COMMERCE_ENVIRONMENT:'sandbox',EZKART_DATABASE_DRIVER:'d1',EZKART_DATABASE_ENVIRONMENT:'test',EZKART_CLOUDFLARE_API_URL:'https://api-test.ezkart.id',EZKART_COMMERCE_STORAGE:'d1',EZKART_COMMERCE_SERVICE_SECRET:'a'.repeat(64),EZKART_COMMERCE_TREASURY_RECOVERY_DIRECTORY:dir,EZKART_COMMERCE_TREASURY_INQUIRY:'enabled',EZKART_COMMERCE_TREASURY_PAYMENT:'enabled',...flags}});
 assert.equal(r.status,0,r.stderr);assert.equal(r.stderr,'');return JSON.parse(r.stdout);
}
test('original inquiry sends once, stores private receipt before acknowledgement and replay only reads',async t=>{const r=await run(t);assert.equal(r.error,undefined,JSON.stringify(r));assert.equal(r.requests.length,2);assert.deepEqual(r.results.map(x=>x.providerCalls),[1,0]);assert.equal(r.results[0].payoutConfirmed,false);assert.equal((await stat(r.files[0])).mode&0o777,0o600);const d=JSON.parse(await readFile(r.files[0],'utf8'));assert.equal(d.intentId,'try_'+'a'.repeat(40));assert.equal(d.evidence.externalId,binding.inquiryExternalId);});
test('unknown provider response never resends original transfer identity',async t=>{const r=await run(t,{responses:[token,{throw:true}]});assert.equal(r.error,undefined,JSON.stringify(r));assert.equal(r.requests.length,2);assert.deepEqual(r.results.map(x=>x.state),['outcome_unknown','outcome_unknown']);assert.equal(r.results[1].providerCalls,0);});
test('lost receipt delivery recovers original private evidence without another provider authentication',async t=>{const r=await run(t,{failDelivery:true,actions:['dispatch','recover','dispatch']});assert.equal(r.error,undefined,JSON.stringify(r));assert.equal(r.requests.length,2);assert.equal(r.results[0].state,'outcome_unknown');assert.equal(r.results[1].providerCalls,0);assert.equal(r.results[2].state,'recorded');});
test('held inquiry requires no provider authentication and retains intent',async t=>{const r=await run(t,{}, {EZKART_COMMERCE_TREASURY_INQUIRY:'held'});assert.match(r.error,/dispatch is held/);assert.equal(r.requests.length,0);});

const payment=()=>response({...JSON.parse(inquiry.body),referenceNo:'fixture-payment',referenceNumber:'fixture-bank',transactionDate:new Date().toISOString()});
test('released fixture payment invokes typed transport once and receipt recovery retains original confirmation',async t=>{const r=await run(t,{stage:'payment',inquiryResponse:inquiry.body,responses:[token,payment()],failDelivery:true,actions:['dispatch','recover','dispatch']});assert.equal(r.error,undefined,JSON.stringify(r));assert.equal(r.requests.length,2);assert.match(r.requests[1].url,/transfer-payment$/);const sent=JSON.parse(r.requests[1].body);assert.equal(sent.referenceNo,'fixture-inquiry');assert.equal(sent.beneficiaryAccountName,'Fixture Ezkart Company');assert.equal(r.results[1].providerCalls,0);assert.equal(r.results[2].providerCalls,0);});
test('unknown payment never repeats and unavailable policy causes no provider authentication',async t=>{let r=await run(t,{stage:'payment',inquiryResponse:inquiry.body,responses:[token,{throw:true}]});assert.equal(r.error,undefined,JSON.stringify(r));assert.equal(r.requests.length,2);assert.deepEqual(r.results.map(x=>x.state),['outcome_unknown','outcome_unknown']);r=await run(t,{stage:'payment',inquiryResponse:inquiry.body,executionAvailable:false});assert.match(r.error,/release and fee funding/);assert.equal(r.requests.length,0);});
