import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {generateKeyPairSync} from 'node:crypto';import {mkdtemp,rm,stat} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {fileURLToPath} from 'node:url';
const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048,privateKeyEncoding:{type:'pkcs8',format:'pem'},publicKeyEncoding:{type:'spki',format:'pem'}}),credentials={environment:'sandbox',clientId:'MCH-fixture-only',secretKey:'fixture-only-secret',privateKey};
async function run(t,input={},flags={}){const dir=await mkdtemp(join(tmpdir(),'treasury-observations-'));t.after(()=>rm(dir,{recursive:true,force:true}));const r=spawnSync(process.env.PHP_BINARY||'php',['-n',fileURLToPath(new URL('./treasury-observations-fixture.php',import.meta.url))],{input:JSON.stringify({credentials,...input}),encoding:'utf8',env:{...process.env,EZKART_DEPLOYMENT_ENVIRONMENT:'test',EZKART_COMMERCE_ENVIRONMENT:'sandbox',EZKART_CLOUDFLARE_API_URL:'https://api-test.ezkart.id',EZKART_COMMERCE_TREASURY_RECOVERY_DIRECTORY:dir,EZKART_COMMERCE_TREASURY_OBSERVATIONS:'enabled',...flags}});assert.equal(r.status,0,r.stderr);assert.equal(r.stderr,'');return JSON.parse(r.stdout);}
test('bounded original status and both account histories persist before delivery; recover makes zero provider calls',async t=>{const r=await run(t);assert.equal(r.results[0].error,undefined,JSON.stringify(r));assert.deepEqual(r.results.map(x=>x.providerCalls),[5,0]);assert.equal(r.requests.length,6);assert(r.requests.every(x=>/\/(b2b|transactions-status|transaction-history-list|balance-inquiries)$/.test(x.url)));assert(r.results.every(x=>x.payoutConfirmed===false));for(const file of r.files)assert.equal((await stat(file)).mode&0o777,0o600);});
test('read budget pauses original run and collection resumes saved steps without rereading provider status',async t=>{const r=await run(t,{maxReads:2,modes:['collect','recover','collect','collect','recover']});assert.equal(r.results[0].reason,'read_budget');assert.match(r.results[1].error,/unsaved provider read/);assert.equal(r.results.at(-1).providerCalls,0);assert.equal(r.requests.filter(x=>x.url.endsWith('/transactions-status')).length,1);assert.equal(r.requests.length,6);});
test('lost D1 status acknowledgement recovers stored original response before further reads',async t=>{const r=await run(t,{failDelivery:'/internal/commerce/finance/treasury/try_'+'a'.repeat(40)+'/status/receipt',modes:['collect','recover','collect','recover']});assert.match(r.results[0].error,/lost delivery/);assert.match(r.results[1].error,/unsaved provider read/);assert.equal(r.requests.filter(x=>x.url.endsWith('/transactions-status')).length,1);assert.equal(r.results.at(-1).providerCalls,0);});
test('retained failed read never substitutes a new response within the original run; held collection never authenticates',async t=>{let r=await run(t,{failOperation:'transaction-history-list',modes:['collect','recover','collect']});assert.equal(r.requests.filter(x=>x.url.endsWith('/transaction-history-list')).length,1);assert(r.results.every(x=>x.error));r=await run(t,{modes:['collect']},{EZKART_COMMERCE_TREASURY_OBSERVATIONS:'held'});assert.match(r.results[0].error,/collection is held/);assert.equal(r.requests.length,0);});

test('changed provider identity cannot replace the original company account even for read collection',async t=>{const r=await run(t,{scopeFingerprint:'f'.repeat(64),modes:['collect']});assert.match(r.results[0].error,/Configured provider differs/);assert.equal(r.requests.length,0);});

test('older original transfer uses bounded contiguous history windows without losing original source identity',async t=>{const r=await run(t,{grantedAt:new Date(Date.now()-35*86400000).toISOString()});assert.equal(r.results[0].error,undefined,JSON.stringify(r));assert.deepEqual(r.results.map(x=>x.providerCalls),[7,0]);const reads=r.requests.filter(x=>x.url.endsWith('/transaction-history-list')).map(x=>JSON.parse(x.body));assert.equal(reads.length,4);assert.equal(reads[0].toDateTime,reads[1].fromDateTime);assert.equal(reads[2].toDateTime,reads[3].fromDateTime);});
