import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp, rm, writeFile, mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium} from 'playwright';
import {Workspace} from '../workspace.mjs';

test('site favicons persist, follow the visitor theme, and can be added or skipped before publication', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'ezkart-favicons-'));
  const ws = await new Workspace(directory).init();
  await writeFile(join(directory, 'catalog.json'), JSON.stringify({products: [{id: 'one', name: 'A product', type: 'physical', status: 'active', price: 12000, stock: 4, variants: []}]}));
  await ws.create({id: 'icons', name: 'My site'});
  await ws.create({id: 'empty', name: 'Another site'});
  await ws.start();
  const browser = await chromium.launch();
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}, reducedMotion: 'reduce'});
  page.setDefaultTimeout(7000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  t.after(async () => { await browser.close(); await ws.stop(); await rm(directory, {recursive: true, force: true}); });
  const call = (method, args = {}) => page.evaluate(({method, args}) => EzkartBuilder[method](args), {method, args});
  const open = async id => {
    await page.goto(ws.url + `/cart/admin/?page=sites&edit=${id}.ezkart.site`);
    await page.waitForFunction(() => globalThis.EzkartBuilder);
    await call('settle');
  };
  const settings = page.locator('[data-sq-panel="settings"]');
  const dialog = page.locator('[data-sq-favicon-dialog]');
  const card = (host, mode) => host.locator(`[data-favicon-mode="${mode}"]`);
  const upload = async (host, mode, file) => {
    const chooser = page.waitForEvent('filechooser');
    await card(host, mode).locator('[data-favicon-upload]').click();
    await (await chooser).setFiles(file);
    await card(host, mode).getByText('Icon added.', {exact: true}).waitFor();
  };
  const svg = color => ({name: 'brand.svg', mimeType: 'image/svg+xml', buffer: Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="80" height="40"><rect width="80" height="40" fill="${color}"/></svg>`)});
  await open('icons');
  await page.locator('[data-sq-publish]').click();
  await page.locator('[data-sq-publish-message]').waitFor();
  assert.equal(await dialog.isVisible(), false, 'Product requirement still applies');
  await call('nativeInsert', {section: 'blank', node: {id: 'buy', type: 'commerce', part: 'add', productId: 'one'}});
  await page.locator('[data-sq-publish]').click();
  await dialog.waitFor();
  assert.equal((await ws.read('icons')).status, 'draft', 'Opening favicon setup does not publish');
  await page.keyboard.press('Escape');
  assert.equal(await dialog.isVisible(), false);
  await page.locator('[data-sq-tab="layers"]').click();
  await page.locator('[data-sq-panel="layers"] [data-sq-structure-view="settings"]').click();
  await upload(settings, 'light', svg('#175b46'));
  let icons = (await call('snapshot')).favicons;
  assert.match(icons.light, /^data:image\/png;base64,/);
  assert.equal(icons.dark, '');
  assert.equal(await card(settings, 'dark').locator('img').getAttribute('src'), icons.light, 'Single upload is used in both themes');
  const geometry = await card(settings, 'light').locator('img').evaluate(async image => {
    await image.decode();
    const canvas = document.createElement('canvas'); canvas.width = canvas.height = 128;
    const context = canvas.getContext('2d'); context.drawImage(image, 0, 0);
    return {width: image.naturalWidth, height: image.naturalHeight, corner: context.getImageData(0, 0, 1, 1).data[3], center: context.getImageData(64, 64, 1, 1).data[3]};
  });
  assert.deepEqual(geometry, {width: 128, height: 128, corner: 0, center: 255}, 'Non-square icons retain their proportions and transparency');
  await upload(settings, 'dark', svg('#ffdf80'));
  icons = (await call('snapshot')).favicons;
  assert.notEqual(icons.light, icons.dark);
  await call('undo'); assert.equal((await call('snapshot')).favicons.dark, '');
  await call('redo'); assert.deepEqual((await call('snapshot')).favicons, icons);
  await call('save'); await open('icons');
  assert.deepEqual((await call('snapshot')).favicons, icons);
  await page.locator('[data-sq-tab="layers"]').click();
  await page.locator('[data-sq-panel="layers"] [data-sq-structure-view="settings"]').click();
  await card(settings, 'light').locator('input').setInputFiles({name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('broken')});
  await card(settings, 'light').locator('[data-favicon-status][data-error]').waitFor();
  assert.deepEqual((await call('snapshot')).favicons, icons, 'A corrupt upload keeps both saved icons');
  await card(settings, 'light').locator('input').setInputFiles({name: 'too-big.png', mimeType: 'image/png', buffer: Buffer.alloc(8 * 1024 * 1024 + 1)});
  await card(settings, 'light').getByText('Choose an image smaller than 8 MB.', {exact: true}).waitFor();
  assert.deepEqual((await call('snapshot')).favicons, icons);
  const html = await call('exportHtml');
  const published = await browser.newPage({colorScheme: 'light'});
  await published.setContent(html);
  const icon = published.locator('link[data-ezkart-favicon]');
  assert.equal(await icon.getAttribute('href'), icons.light);
  await published.emulateMedia({colorScheme: 'dark'});
  await published.waitForFunction(src => document.querySelector('[data-ezkart-favicon]').href === src, icons.dark);
  await published.emulateMedia({colorScheme: 'light'});
  await published.waitForFunction(src => document.querySelector('[data-ezkart-favicon]').href === src, icons.light);
  await published.close();
  await page.locator('[data-sq-publish]').click();
  await page.waitForFunction(() => document.querySelector('[data-sq-save-state]').textContent === 'Published just now');
  assert.equal(await dialog.isVisible(), false, 'Existing icons skip the setup prompt');
  assert.match((await ws.read('icons')).publishedHtml, /data-ezkart-favicon/);
  await card(settings, 'light').locator('[data-favicon-remove]').click();
  assert.equal(await card(settings, 'light').locator('img').getAttribute('src'), icons.dark, 'Removing light falls back to dark');
  await card(settings, 'dark').locator('[data-favicon-remove]').click();
  assert.equal((await call('exportHtml')).includes('data-ezkart-favicon'), false);
  await page.locator('[data-sq-publish]').click(); await dialog.waitFor();
  await upload(dialog, 'dark', svg('#eeeeee'));
  await dialog.getByRole('button', {name: 'Publish page', exact: true}).click();
  await page.waitForFunction(() => document.querySelector('[data-sq-save-state]').textContent === 'Published just now');
  const darkOnly = (await call('snapshot')).favicons;
  assert.equal((await ws.read('icons')).state.favicons.dark, darkOnly.dark);
  // A new design retains page identity, and switching pages never leaks favicons.
  await page.locator('[data-sq-templates]').click();
  await page.locator('#builder-templates-dialog .sq-template-choice:has(input[value="takar"])').click();
  await page.locator('[data-template-choose]').click();
  await page.locator('#template-apply-dialog input[value="replace"]').check();
  await page.locator('[data-template-apply-submit]').click();
  await page.locator('#template-apply-dialog').waitFor({state: 'hidden'});
  assert.deepEqual((await call('snapshot')).favicons, darkOnly);
  await call('save');
  await open('empty');
  assert.deepEqual((await call('snapshot')).favicons, {light: '', dark: ''});
  await call('nativeInsert', {section: 'blank', node: {id: 'buy', type: 'commerce', part: 'add', productId: 'one'}});
  await page.locator('[data-sq-publish]').click(); await dialog.waitFor();
  await mkdir('/tmp/ezkart-favicons-review', {recursive: true});
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({width, height: 900});
    assert.equal(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth), true);
    await page.screenshot({path: `/tmp/ezkart-favicons-review/publish-${width}.png`});
  }
  await dialog.getByRole('button', {name: 'Publish without favicon'}).click();
  await page.waitForFunction(() => document.querySelector('[data-sq-save-state]').textContent === 'Published just now');
  assert.equal((await ws.read('empty')).status, 'published');
  await page.locator('[data-sq-tab="layers"]').click();
  await page.locator('[data-sq-panel="layers"] [data-sq-structure-view="settings"]').click();
  assert.equal(await settings.evaluate(node => node.scrollWidth <= node.clientWidth), true);
  await page.screenshot({path: '/tmp/ezkart-favicons-review/settings-320.png'});
  assert.deepEqual(errors, []);
});
