import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp, writeFile, rm, mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {chromium} from 'playwright';
import {Workspace, repoRoot} from '../workspace.mjs';

test('Image Stack publishes a durable public link and keeps later draft edits private', async t => {
  const dir = await mkdtemp(join(tmpdir(), 'ezkart-hosted-page-'));
  const ws = await new Workspace(dir).init();
  await writeFile(join(dir, 'catalog.json'), JSON.stringify({demoCheckout:true, products:[{id:'coffee', name:'Catalog coffee', status:'active', type:'physical', price:79000, stock:5, images:[]}]}));
  await ws.start();
  const browser = await chromium.launch();
  const page = await browser.newPage({viewport:{width:1440,height:1000}, reducedMotion:'reduce'});
  const editorErrors=[];page.on('pageerror',e=>editorErrors.push(e.message));
  t.after(async () => {await browser.close(); await ws.stop(); await rm(dir,{recursive:true,force:true});});
  await page.goto(ws.url+'/cart/admin/?page=sites');
  await page.locator('[data-library-create-card]').click();
  await page.locator('[data-bc-choose=image]').click();
  await page.locator('[name=page_name]').fill('Hosted coffee');
  await page.locator('[data-library-page-form] button[value=default]').click();
  await page.waitForURL('**edit=hosted-coffee.ezkart.site');
  await page.locator('[data-image-page-upload]').setInputFiles(join(repoRoot,'cart/admin/assets/builder-choice/kopi-senja-01.webp'));
  await page.waitForFunction(() => document.querySelectorAll('.ib-row').length===1 && !document.querySelector('.ib-controls').disabled);
  await page.locator('[data-image-page-product]').selectOption('coffee');
  const publicUrl = ws.url+'/workspace/shop/hosted-coffee';
  assert.equal((await fetch(publicUrl)).status,404);
  await page.locator('[data-sq-preview]').click();
  const previewTabPromise=page.waitForEvent('popup');
  await page.locator('[data-sq-preview-new-tab]').click();
  const previewTab=await previewTabPromise;
  await previewTab.waitForURL(publicUrl+'/preview');
  await page.locator('.preview-share-dialog [data-preview-close]').click();
  await page.locator('[data-sq-preview-close]').click();
  await page.locator('[data-sq-publish]').click();
  await page.locator('[data-favicon-publish]').click();
  const link=page.locator('[data-sq-published-link]');
  await link.waitFor({state:'visible'});
  assert.equal(await link.getAttribute('href'),publicUrl);
  await previewTab.waitForURL(publicUrl);
  const publication=page.locator('[data-sq-published-dialog]');
  await publication.waitFor({state:'visible'});
  assert.equal(await publication.locator('[data-published-url]').textContent(),publicUrl);
  await page.evaluate(()=>{navigator.clipboard.writeText=async text=>{window.copiedPageUrl=text;};});
  await publication.getByRole('button',{name:'Copy link'}).click();
  assert.equal(await page.evaluate(()=>window.copiedPageUrl),publicUrl);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await publication.evaluate(node=>node.scrollWidth<=node.clientWidth),true);
  await mkdir('/tmp/ezkart-hosting-review',{recursive:true});
  await page.screenshot({path:'/tmp/ezkart-hosting-review/publication-390.png'});
  await page.setViewportSize({width:1440,height:1000});
  await publication.getByRole('button',{name:'Back to editor'}).click();
  // A separate browser context has no editor cookies or storage.
  const visitor=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
  const live=await visitor.newPage();
  const errors=[];live.on('pageerror',e=>errors.push(e.message));
  assert.equal((await live.goto(publicUrl)).status(),200);
  await live.frameLocator('[data-hosted-page]').locator('[data-image-upload]').evaluate(img=>img.decode());
  await live.frameLocator('[data-hosted-page]').locator('[data-ezkart-add]').click();
  assert.match(await live.frameLocator('[data-hosted-page]').locator('.ezkart-cart-row').innerText(),/Catalog coffee/);
  await live.frameLocator('[data-hosted-page]').locator('[data-ezkart-cart-go]').click();
  assert.match(await live.frameLocator('[data-hosted-page]').locator('[data-ezkart-cart-items]').innerText(),/No order was placed/);
  await page.locator('.ib-row summary').click();
  await page.locator('.ib-row textarea').fill('Unpublished artwork description');
  await page.locator('.ib-row textarea').blur();
  await page.evaluate(()=>EzkartBuilder.save());
  await live.reload();
  assert.notEqual(await live.frameLocator('[data-hosted-page]').locator('[data-image-upload]').getAttribute('alt'),'Unpublished artwork description');
  await page.locator('[data-sq-publish]').click();
  await page.locator('[data-favicon-publish]').click();
  await page.waitForFunction(()=>document.querySelector('[data-sq-save-state]').textContent==='Published just now');
  await publication.getByRole('button',{name:'Back to editor'}).click();
  await live.reload();
  assert.equal(await live.frameLocator('[data-hosted-page]').locator('[data-image-upload]').getAttribute('alt'),'Unpublished artwork description');
  await page.reload();
  await link.waitFor({state:'visible'});
  assert.equal(await link.getAttribute('href'),publicUrl);
  await mkdir('/tmp/ezkart-hosting-review',{recursive:true});
  for (const width of [390,941,1440]) {
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    const bounds=await link.boundingBox();
    assert.ok(bounds.x>=0 && bounds.x+bounds.width<=width);
    await page.screenshot({path:`/tmp/ezkart-hosting-review/editor-${width}.png`});
  }
  await live.frameLocator('[data-hosted-page]').locator('[data-image-upload]').evaluate(img=>img.decode());
  await live.screenshot({path:'/tmp/ezkart-hosting-review/public-390.png'});
  await page.goto(ws.url+'/cart/admin/?page=sites');
  const copy=page.getByRole('button',{name:'Copy published page URL'});
  await page.evaluate(()=>{navigator.clipboard.writeText=async text=>{window.copiedPageUrl=text;};});
  await page.locator('[data-project-card]').hover();
  await copy.click();
  assert.equal(await page.evaluate(()=>window.copiedPageUrl),publicUrl);
  await page.close();
  await live.reload();
  assert.equal(await live.frameLocator('[data-hosted-page]').locator('[data-image-upload]').count(),1);
  assert.deepEqual(errors,[]);
  assert.deepEqual(editorErrors,[]);
});
