import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp, rm, mkdir, readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium} from 'playwright';
import {Workspace, repoRoot} from '../workspace.mjs';

test('image replacement preserves layout and history, handles failures, and keeps long inspector titles clear', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'ezkart-image-replace-'));
  const ws = await new Workspace(directory).init();
  await ws.create({id: 'image-replacement', name: 'Image replacement'});
  await ws.start();
  const browser = await chromium.launch();
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}, reducedMotion: 'reduce'});
  page.setDefaultTimeout(7000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  t.after(async () => { await browser.close(); await ws.stop(); await rm(directory, {recursive: true, force: true}); });
  const call = (method, args = {}) => page.evaluate(({method, args}) => EzkartBuilder[method](args), {method, args});
  await page.goto(ws.url + '/cart/admin/?page=sites&edit=image-replacement.ezkart.site');
  await page.waitForFunction(() => globalThis.EzkartBuilder);
  if (await page.locator('[data-sq-panel=add]').isVisible()) await page.locator('[data-sq-tab=add]').click();
  const longName = 'ZERO Syrup 50 - 550 ml Better than Stevia Syrup Nol Gula Sugar-Free image 9';
  const original = 'data:image/webp;base64,' + (await readFile(join(repoRoot, 'cart/admin/assets/products/kopi-susu.webp'))).toString('base64');
  await call('nativeInsert', {section: 'blank', node: {id: 'photo', type: 'image', name: longName, alt: 'Original image description', src: original, props: {width: '200px', height: '190px', objectFit: 'cover', borderRadius: '12px'}}});
  await call('nativeInsert', {section: 'blank', node: {id: 'other-photo', type: 'image', src: original, props: {width: '120px', height: '100px'}}});
  await call('settle');
  const photo = page.locator('[data-native-id="photo"]');
  const panel = page.locator('[data-sq-native-inspector]');
  await photo.click();
  const before = await call('nativeInspect', {id: 'photo'});
  const replace = panel.getByRole('button', {name: 'Replace image', exact: true});
  assert.equal(await replace.isVisible(), true);
  assert.equal(await panel.locator('[data-native-src]').inputValue(), '', 'Embedded images do not expose base64 text in the URL field');
  const png = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 40; canvas.height = 60;
    const context = canvas.getContext('2d'); context.fillStyle = '#195f4b'; context.fillRect(0, 0, 40, 60);
    return canvas.toDataURL('image/png').split(',')[1];
  });
  const file = {name: 'replacement.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64')};
  const choose = page.waitForEvent('filechooser'); await replace.click(); await (await choose).setFiles(file);
  await panel.getByText('Image replaced. Saved to your uploads.', {exact: true}).waitFor();
  await photo.evaluate(image => image.decode());
  const after = await call('nativeInspect', {id: 'photo'});
  assert.notEqual(after.src, before.src);
  assert.deepEqual({...after, src: before.src}, before, 'Only the selected image source changes');
  assert.equal(await photo.evaluate(image => image.naturalWidth), 40);
  assert.equal(await photo.evaluate(image => image.naturalHeight), 60);
  assert.equal((await call('nativeInspect', {id: 'other-photo'})).src, original);
  await call('undo'); assert.equal((await call('nativeInspect', {id: 'photo'})).src, original);
  await call('redo'); assert.equal((await call('nativeInspect', {id: 'photo'})).src, after.src);
  await call('save'); await page.reload(); await page.waitForFunction(() => globalThis.EzkartBuilder); await call('settle');
  assert.equal((await call('nativeInspect', {id: 'photo'})).src, after.src);
  if (await page.locator('[data-sq-panel=add]').isVisible()) await page.locator('[data-sq-tab=add]').click();
  await photo.click();
  await panel.locator('[data-native-image-upload]').setInputFiles({name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from('Not an image')});
  await panel.locator('[data-native-image-upload-status][data-error]').waitFor();
  assert.equal((await call('nativeInspect', {id: 'photo'})).src, after.src, 'Invalid files keep the existing image');
  // A server failure leaves the current image intact and the upload control reusable.
  const assetRoute = '**/*cloud=%2Fv1%2Fassets';
  await page.route(assetRoute, route => route.request().method() === 'POST' ? route.fulfill({status: 503, json: {ok: false, error: 'Upload unavailable. Try again.'}}) : route.continue());
  await panel.locator('[data-native-image-upload]').setInputFiles(file);
  await panel.getByText('Upload unavailable. Try again.', {exact: true}).waitFor();
  assert.equal((await call('nativeInspect', {id: 'photo'})).src, after.src);
  assert.equal(await replace.isEnabled(), true);
  await page.unroute(assetRoute);
  // Changing selection during an upload must never replace the newly selected image.
  let release;
  const gate = new Promise(resolve => { release = resolve; });
  let reached;
  const started = new Promise(resolve => { reached = resolve; });
  await page.route(assetRoute, async route => { if (route.request().method() === 'POST') { reached(); await gate; } await route.continue(); });
  await panel.locator('[data-native-image-upload]').setInputFiles({name: 'new-photo.webp', mimeType: 'image/webp', buffer: await readFile(join(repoRoot, 'cart/admin/assets/products/kopi-susu.webp'))});
  await started;
  await page.locator('[data-native-id="other-photo"]').click();
  release();
  await page.waitForFunction(src => JSON.parse(document.querySelector('[data-native-id="photo"]').dataset.sqNative).src === src, original);
  assert.equal((await call('nativeInspect', {id: 'other-photo'})).src, original);
  assert.equal(await page.locator('[data-sq-inspector-title]').innerText(), 'Image', 'Upload completion preserves current selection');
  await page.unroute(assetRoute);
  await photo.click();
  await mkdir('/tmp/ezkart-image-inspector', {recursive: true});
  for (const width of [1440, 940, 390, 320]) {
    await page.setViewportSize({width, height: 1000}); await call('settle');
    await panel.locator('[data-native-content]').scrollIntoViewIfNeeded();
    const header = await page.locator('.sq-inspector > header').boundingBox();
    const title = await page.locator('[data-sq-inspector-title]').boundingBox();
    const close = await page.locator('[data-sq-close-inspector]').boundingBox();
    const scroll = await page.locator('.sq-inspector-scroll').boundingBox();
    assert.ok(title.y >= header.y + 12 && title.y + title.height <= header.y + header.height - 12, `Long title has vertical breathing room at ${width}px`);
    assert.ok(title.x + title.width <= close.x - 8, `Title clears the close button at ${width}px`);
    assert.ok(scroll.y >= header.y + header.height - 1, `Fields start below the full header at ${width}px`);
    assert.equal(await panel.evaluate(node => node.scrollWidth <= node.clientWidth), true);
    assert.equal(await replace.isVisible(), true);
    await page.screenshot({path: `/tmp/ezkart-image-inspector/${width}.png`});
  }
  assert.deepEqual(errors, []);
});
