import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium} from 'playwright';
import {Workspace,repoRoot} from '../workspace.mjs';
import {chooseBasic} from './asset-helpers.mjs';
const invalid=['https://wa.me/123','https://example.com','https://linktr.ee/shop','https://bit.ly/profile','https://instagram.com.evil.test/shop','https://user@instagram.com/shop','https://instagram.com/p/123','https://instagram.com/shop?next=evil','javascript:alert(1)'];

test('Image Stack profile selector supports handles, rejects unsupported links, preserves saved repair values and exports only profiles',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'ezkart-image-profiles-')),ws=await new Workspace(dir).init();await writeFile(join(dir,'catalog.json'),JSON.stringify({products:[{id:'coffee',name:'Coffee',status:'active',price:89000,stock:8,type:'physical'}],demoCheckout:true}));await ws.start();
 const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:941,height:904},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();await ws.stop();await rm(dir,{recursive:true,force:true});assert.deepEqual(errors,[]);});
 await page.goto(ws.url+'/cart/admin/?page=sites');await page.locator('[data-library-create-card]').click();await page.locator('[data-bc-choose=image]').click();await page.locator('[name=page_name]').fill('Social profiles');await page.locator('[data-library-page-form] button[value=default]').click();await page.waitForURL('**edit=social-profiles.ezkart.site');await page.locator('[data-image-page-upload]').setInputFiles(join(repoRoot,'cart/admin/assets/builder-choice/sambal.webp'));await page.waitForFunction(()=>document.querySelector('.ib-row')&&!document.querySelector('.ib-controls').disabled);await page.locator('[data-image-page-product]').selectOption('coffee');
 const footer=page.locator('[data-image-settings=footer]');await footer.locator('summary').click();await page.locator('[data-image-extra=footer-enabled]').check();await page.locator('[data-image-social-add]').click();const row=page.locator('.ib-social-link'),url=row.locator('input').nth(1);
 await row.getByRole('combobox',{name:'Social network 1'}).selectOption('instagram');await url.fill('@my.shop');await url.blur();assert.equal(await page.locator('[data-image-footer] a').getAttribute('href'),'https://www.instagram.com/my.shop');assert.equal(await page.locator('[data-image-footer] a').textContent(),'Instagram');
 for(const value of invalid){await url.fill(value);await url.blur();assert.equal(await url.getAttribute('aria-invalid'),'true',value);assert.equal(await row.locator('[role=status]').isVisible(),true);assert.equal(await page.locator('[data-image-footer] a').getAttribute('href'),'https://www.instagram.com/my.shop');}
 await url.fill('@my.shop');await url.blur();await row.locator('input').first().fill('Orders');await row.locator('input').first().blur();await page.evaluate(()=>EzkartBuilder.save());await page.reload();await page.locator('[data-image-settings=footer]>summary').click();assert.equal(await row.locator('input').first().inputValue(),'Orders');assert.equal(await url.inputValue(),'https://www.instagram.com/my.shop');
 // Simulate an existing pre-policy saved website without losing its repair data.
 await page.evaluate(()=>{const page=document.querySelector('[data-image-page]'),extras=JSON.parse(page.dataset.imageExtras);extras.footer.links.push({label:'Old website',url:'https://example.com'});page.dataset.imageExtras=JSON.stringify(extras);});await page.evaluate(()=>EzkartBuilder.save());await page.reload();await page.locator('[data-image-settings=footer]>summary').click();assert.equal(await row.nth(1).locator('input').nth(1).inputValue(),'https://example.com');assert.equal(await row.nth(1).locator('input').nth(1).getAttribute('aria-invalid'),'true');assert.equal(await page.locator('[data-image-footer] a').count(),1);
 const html=await page.evaluate(()=>EzkartBuilder.previewHtml());const view=await browser.newPage();await view.setContent(html);assert.equal(await view.locator('[data-image-footer] a').count(),1);assert.equal(await view.locator('[data-image-footer] a').textContent(),'Orders');assert.equal(await view.locator('[data-image-footer] a').getAttribute('rel'),'noopener noreferrer');
 for(const width of [320,390,941,1440]){await page.setViewportSize({width,height:904});await footer.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width===941)await page.screenshot({path:'/tmp/ezkart-social-image-941.png'});if(width===390)await page.screenshot({path:'/tmp/ezkart-social-image-390.png'});}
 assert.equal(await page.locator('.ib-phone').evaluate(n=>getComputedStyle(n).borderTopWidth),'0px');assert.equal(await page.locator('.ib-phone').evaluate(n=>getComputedStyle(n).borderRadius),'0px');
});

test('Studio social controls validate selected profile provider, preserve names, and omit old unsupported links after reopening',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'ezkart-studio-profiles-')),ws=await new Workspace(dir).init();await ws.create({id:'studio-profiles',name:'Studio profiles'});await ws.start();const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}});t.after(async()=>{await browser.close();await ws.stop();await rm(dir,{recursive:true,force:true});});
 await page.goto(ws.url+'/cart/admin/?page=sites&edit=studio-profiles.ezkart.site');await page.waitForFunction(()=>globalThis.EzkartBuilder);assert.deepEqual(await page.evaluate(()=>({unicode:EzkartMedia.socialProfile('https://youtube.com/@caf%C3%A9-shop')?.url,linkedin:EzkartMedia.socialProfile('@my-shop','linkedin')?.url,encoded:EzkartMedia.socialProfile('https://instagram.com/%2fshop')})),{unicode:'https://www.youtube.com/@caf%C3%A9-shop',linkedin:'https://www.linkedin.com/in/my-shop',encoded:null});await chooseBasic(page,'native-social');const id=await page.evaluate(()=>EzkartBuilder.nativeInspect().find(n=>n.type==='social').id);await page.locator(`[data-native-id="${id}"]`).click();const panel=page.locator('[data-sq-native-inspector]'),url=panel.locator('[data-native-social-url="0"]'),apply=panel.locator('[data-native-social-apply]');await panel.locator('[data-native-social-provider="0"]').selectOption('youtube');await url.fill('@my-shop');await panel.locator('[data-native-social-label="0"]').fill('Orders');await apply.click();assert.equal(await page.locator(`[data-native-id="${id}"] a`).getAttribute('href'),'https://www.youtube.com/@my-shop');
 for(const value of [...invalid,'https://instagram.com/myshop']){await url.fill(value);await apply.click();assert.equal(await url.getAttribute('aria-invalid'),'true');assert.equal(await panel.locator('[data-native-social-reason="0"]').isVisible(),true);assert.equal(await page.locator(`[data-native-id="${id}"] a`).textContent(),'Orders');}
 await url.fill('@my-shop');await apply.click();await page.evaluate(()=>EzkartBuilder.save());await page.reload();await page.waitForFunction(()=>globalThis.EzkartBuilder);await page.locator(`[data-native-id="${id}"]`).click();assert.equal(await url.inputValue(),'https://www.youtube.com/@my-shop');
 await assert.rejects(()=>page.evaluate(id=>EzkartBuilder.nativeUpdate({id,links:[{label:'WhatsApp',url:'https://wa.me/123'}]}),id),/social network/);
 await page.evaluate(id=>{const node=document.querySelector(`[data-native-id="${id}"]`),config=EzkartNative.read(node);config.links.push({label:'Old website',url:'https://example.com'});EzkartNative.write(node,config);},id);await page.evaluate(()=>EzkartBuilder.save());await page.reload();await page.waitForFunction(()=>globalThis.EzkartBuilder);await page.locator(`[data-native-id="${id}"]`).click();assert.equal(await panel.locator('[data-native-social-url="1"]').inputValue(),'https://example.com');assert.equal(await panel.locator('[data-native-social-reason="1"]').isVisible(),true);assert.equal(await page.locator(`[data-native-id="${id}"] a`).count(),1);
 const html=await page.evaluate(()=>EzkartBuilder.previewHtml()),view=await browser.newPage();await view.setContent(html);assert.equal(await view.locator(`[data-native-id="${id}"] a`).count(),1);assert.equal(await view.locator(`[data-native-id="${id}"] a`).textContent(),'Orders');
 for(const width of [390,941,1440]){await page.setViewportSize({width,height:904});const close=page.locator('[data-sq-close-inspector]');if(await close.isVisible())await close.click();await page.locator(`[data-native-id="${id}"]`).click();await page.evaluate(()=>EzkartBuilder.settle());await panel.locator('[data-native-social]').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width===941)await page.screenshot({path:'/tmp/ezkart-social-studio-941.png'});}
});
