(() => {
  'use strict';
  const root=document.querySelector('[data-jev]'); if(!root)return;
  const $=s=>root.querySelector(s), detail=$('[data-jev-detail]'), list=$('[data-jev-list]'), message=$('[data-jev-message]');
  const account=root.dataset.account, storageKey='ezkart:jev:pending:'+account;
  let canWrite=root.dataset.canWrite==='true', mode={}, current=null, pages=[], loadedStore='', busy=false, pending=null;
  const labels={queued:'Queued',running:'Review started',completed:'Reviewed',failed:'Review failed',uncertain:'Review outcome unknown',clear:'No violation flagged',needs_change:'Changes recommended',escalate:'Human review needed',archived:'Temporarily archived',active:'Available',restored:'Restored'};
  const words=v=>labels[v]||String(v||'Not recorded').replaceAll('_',' ');
  const node=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(className)n.className=className;return n;};
  const date=value=>{const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString():String(value||'Not recorded');};
  const note=(text,error=false)=>{message.textContent=text;message.setAttribute('role',error?'alert':'status');};
  const key=()=>crypto.randomUUID().replaceAll('-','');
  const hasMedia=value=>Array.isArray(value)?value.length>0:value===true;
  function sync(){root.querySelectorAll('button,input,textarea,select').forEach(e=>{if(e.matches('[data-jev-refresh]'))e.disabled=busy;else if(e.matches('[data-jev-retry]'))e.disabled=busy||!canWrite;else if(e.closest('[data-jev-intake]')||e.closest('[data-jev-action]'))e.disabled=busy||!canWrite||!!pending||e.dataset.held==='true';});$('[data-jev-recovery]').hidden=!pending;}
  function remember(value){if(value)sessionStorage.setItem(storageKey,JSON.stringify(value));else sessionStorage.removeItem(storageKey);pending=value;sync();}
  try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(saved&&typeof saved.path==='string'&&saved.path.startsWith('/v1/jev/reviews')&&saved.body?.requestKey)pending=saved;}catch{}
  async function api(path,body){
    const response=await fetch('jev-api.php?path='+encodeURIComponent(path),{method:body?'POST':'GET',credentials:'same-origin',headers:{'X-Ezkart-CSRF':root.dataset.csrf,'X-Ezkart-Jev-Account':account,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
    let data;try{data=await response.json();}catch{throw Error('The response could not be confirmed. Retry the original action.');}
    if(!response.ok){const e=Error(data.error||data.message||'Review request unavailable.');e.status=response.status;if([401,403].includes(response.status)){canWrite=false;detail.replaceChildren(node('h2','Review access needs verification'),node('p','Reload this page and verify your authenticator before continuing.'));list.replaceChildren();sync();}throw e;}
    return data;
  }
  function renderMode(){const budget=Number(mode.remainingBudgetMicrousd);$('[data-jev-budget]').textContent=Number.isFinite(budget)?'Review allowance remaining: $'+(budget/1000000).toFixed(2)+' USD · '+Math.min(Number(mode.remainingCalls),Math.floor(budget/Number(mode.perCallReservationMicrousd||10000)))+' calls within that allowance. Each call reserves $'+(Number(mode.perCallReservationMicrousd||10000)/1000000).toFixed(2)+'; unknown costs remain reserved. '+(mode.benchmarkCalls||0)+' benchmark and '+(mode.reviewerCalls||0)+' reviewer calls recorded. This is the app’s conservative allowance, not a live account balance.':'';const enabled=mode.archiveEnabled===true||mode.autoArchive===true;const ready=mode.modelEnabled===true; $('[data-jev-mode]').textContent=(enabled?'Temporary archiving is enabled only for the configured evidenced violations.':'Automatic archiving is held; recommendations do not by themselves change page visibility.')+' '+(ready?'Reviews are started by authorized reviewers.':'Review availability depends on the configured model and policy.')+(!canWrite?' Your current access is read-only; a reviewer with fresh verification can make changes.':'');}
  async function refresh(){const result=await api('/v1/jev/reviews');canWrite=result.canWrite===true;mode=result.mode||{};renderMode();list.replaceChildren();const items=result.items||[];if(!items.length)list.append(node('p','No saved reviews yet. Queue a page below to begin.'));for(const item of items){const b=node('button',undefined,'jev-queue-item');b.type='button';b.setAttribute('aria-current',String(item.id===current?.id));b.append(node('strong',item.caseTitle||item.pageName||item.pageId),node('span',(item.evaluationOnly?'Synthetic evaluation':item.store||'')+' · '+words(item.state)),node('span','Revision '+(item.revision||'')+' · '+date(item.createdAt)));b.addEventListener('click',()=>open(item.id).catch(e=>note(e.message,true)));list.append(b);}sync();}
  const entry=(dl,label,value)=>{dl.append(node('dt',label),node('dd',value));};
  const section=(title,text)=>{detail.append(node('h3',title));if(text)detail.append(node('p',text));};
  function form(action,title,fields,button){const f=node('form');f.dataset.jevAction=action;f.append(node('h3',title));for(const field of fields){const label=node('label',field.label),control=node(field.options?'select':'textarea');control.name=field.name;control.required=true;if(field.options)for(const [value,text] of field.options){const o=node('option',text);o.value=value;control.append(o);}else{control.rows=3;control.maxLength=action==='restore'?1000:1200;}label.append(control);f.append(label);}const b=node('button',button,'action-button');b.type='submit';f.append(b);f.addEventListener('submit',event=>{event.preventDefault();const body=Object.fromEntries(new FormData(f));if(action==='grade')body.score=Number(body.score);if(['rescan','restore'].includes(action))body.expectedRevision=current.currentRevision;if(action==='restore')body.expectedArchiveId=current.archiveId;mutate('/v1/jev/reviews/'+encodeURIComponent(current.id)+'/'+action,body);});detail.append(f);}
  function render(r){
    current=r;detail.replaceChildren(node('h2',r.caseTitle||r.pageName||r.pageId),node('span',words(r.state),'jev-state'));
    const dl=node('dl');entry(dl,'Store',r.store);entry(dl,'Page revision',r.revision);entry(dl,'Requested',date(r.createdAt));if(!r.evaluationOnly){entry(dl,'Review deadline',date(r.deadlineAt));entry(dl,'Rescans',String(r.rescanCount||0)+' of 3');}detail.append(dl);
    if(r.evaluationOnly)detail.append(node('p','Synthetic evaluation. These sources are a private test case, not a public seller page. Grading records your assessment of this one result, not general accuracy.','jev-notice'));
    if(!r.evaluationOnly&&r.deadlineAt&&Date.parse(r.deadlineAt)<=Date.now())detail.append(node('p','The five-day review deadline has passed. Human review is required; the page is not automatically deleted.','jev-warning'));
    section('Reported concern',r.reportText||'No additional concern was supplied.');detail.append(node('p','This is an allegation submitted for review, not an established fact.','jev-help'));
    const archive=typeof r.archiveState==='object'?r.archiveState?.state:r.archiveState;
    section('Page visibility',archive==='archived'?'Temporarily archived. Visitors cannot open this page; the seller can edit it and existing orders remain available.':archive==='restored'?'Restored by a reviewer.':'No temporary archive is recorded for this page.');
    if(r.archiveReason)detail.append(node('p','Latest visibility decision: '+r.archiveReason));
    if(r.stale&&!r.evaluationOnly)detail.append(node('p','The page has changed since this review. This result does not approve or assess the current revision '+r.currentRevision+'.','jev-warning'));
    if(r.coverage?.truncated)detail.append(node('p','The source snapshot was truncated. Unseen text needs human review.','jev-warning'));
    if(hasMedia(r.coverage?.unreviewedMedia))detail.append(node('p','Images or video were not reviewed. Their content must not be inferred from this text review.','jev-help'));
    const policy=node('dl');entry(policy,'Policy',r.policyVersion);entry(policy,'Model',r.model||mode.model);detail.append(policy);
    if(r.state==='queued'){
      detail.append(node('p','This request has not been reviewed. Starting it makes one bounded model request.'));
      const actions=node('div',undefined,'jev-actions');actions.dataset.jevAction='run';const b=node('button','Run Jev review','action-button primary');b.type='button';b.dataset.held=String(mode.modelEnabled!==true||mode.remainingCalls===0||Number(mode.remainingBudgetMicrousd)<Number(mode.perCallReservationMicrousd||10000)||r.stale||r.evaluationOnly);b.addEventListener('click',()=>mutate('/v1/jev/reviews/'+encodeURIComponent(r.id)+'/run',{}));actions.append(b);detail.append(actions);
    }else if(['running','uncertain'].includes(r.state))detail.append(node('p','The original attempt may already have reached the model. Refresh to recover its saved result; do not create another request to retry this attempt.','jev-warning'));
    else if(r.state==='failed')detail.append(node('p','Jev did not return a usable review. This is not a clean result or evidence of a violation. Human review is required.','jev-warning'));
    if(r.failureCode){const reasons={jev_unmatched_evidence:'The model quoted text that was not in the saved page sources. The backend rejected that review.',jev_invalid_outcome:'The model output did not match the required review format.',jev_invalid_finding:'The model finding did not match the required evidence format.',jev_inconsistent_verdict:'The model verdict did not match its evidence.',jev_incomplete_response:'The model response was incomplete or did not match the requested model.',jev_provider_rejected:'The model provider rejected the request.',jev_transport_uncertain:'The original provider response could not be confirmed.'};detail.append(node('p',reasons[r.failureCode]||'The original review could not be accepted. Failure reference: '+r.failureCode,'jev-warning'));}
    if(r.rejectedOutput){section('Rejected model output');detail.append(node('p','The backend rejected this output. It is shown only to evaluate the failure; it is not accepted evidence.','jev-help'),node('blockquote',r.rejectedOutput,'jev-source'));}
    if(r.evaluationOnly&&r.expectedVerdict)detail.append(node('p','Synthetic benchmark expectation: '+words(r.expectedVerdict)+'. This is a test expectation, not a human grade.','jev-help'));
    if(r.outcome){section('Jev recommendation',words(r.outcome.verdict));detail.append(node('p',r.outcome.summary));for(const f of r.outcome.findings||[]){const q=node('blockquote',f.quote,'jev-source');detail.append(node('h3',words(f.code)),q,node('p',f.explanation),node('p','Source: '+f.sourceId,'jev-help'));const rule=(mode.policyRules||[]).find(rule=>rule.code===f.code);if(rule)detail.append(node('p','Rule: '+(rule.label||rule.text||rule.code)+' · Basis: '+(rule.source?.title||words(rule.basis))+(rule.source?.article?' · '+rule.source.article:''),'jev-help'));}if(r.outcome.uncertainties?.length){section('Limits and uncertainty');const ul=node('ul');for(const u of r.outcome.uncertainties)ul.append(node('li',u));detail.append(ul);}detail.append(node('p','This recommendation concerns the saved sources below. It does not verify external claims, identity, or unseen media.','jev-help'));}
    section(r.evaluationOnly?'Synthetic test sources':'Saved page sources');for(const source of r.sources||[]){detail.append(node('p',source.label||source.id,'jev-help'),node('blockquote',source.text,'jev-source'));}if(!r.sources?.length)detail.append(node('p','No readable source text is recorded.'));
    if(r.currentSources){section('Current page text — not yet reviewed by Jev');detail.append(node('p','Current revision '+r.currentRevision+'. This is separate from the original evidence above.','jev-help'));for(const source of r.currentSources)detail.append(node('p',source.id,'jev-help'),node('blockquote',source.text,'jev-source'));if(hasMedia(r.currentCoverage?.unreviewedMedia)||r.currentCoverage?.truncated)detail.append(node('p','The current text snapshot does not assess all page content. Unseen media or omitted text need human review.','jev-warning'));}
    if(r.canGrade===true||r.outcome||r.failureCode){detail.append(node('p','Grades are saved evaluation records. They do not automatically train Jev or change its policy.','jev-help'));form('grade',r.outcome?'Grade this recommendation':'Grade this failed or uncertain attempt',[{name:'score',label:'Usefulness score',options:[['5','5 — Excellent'],['4','4 — Useful'],['3','3 — Mixed'],['2','2 — Poor'],['1','1 — Unusable']]},{name:'agreement',label:'Agreement',options:[['uncertain','Uncertain'],['agree','Agree'],['disagree','Disagree']]},{name:'comment',label:'Reason for your grade'}],'Save grade');}
    if(!r.evaluationOnly&&r.state==='completed'&&r.currentRevision&&r.stale&&!r.due&&r.rescanCount<3){form('rescan','Review the edited page',[{name:'reportText',label:'Concern to review in the current revision'}],'Queue current revision');detail.append(node('p','This queues revision '+r.currentRevision+' within the original five-day deadline. A reviewer starts the new model call separately.','jev-help'));}
    if(!r.evaluationOnly&&archive==='archived'&&r.currentRevision&&r.archiveId){detail.append(node('p','Restoring will release the page hold at current revision '+r.currentRevision+'. Review the edited page before choosing to restore.','jev-help'));form('restore','Restore this page',[{name:'reason',label:'Reason for restoring current revision '+r.currentRevision}],'Restore page');}
    if(r.grades?.length){section('Saved human grades');for(const g of r.grades){const d=node('div',undefined,'jev-grade');d.append(node('strong',g.score+'/5 · '+({agree:'Agree',disagree:'Disagree',uncertain:'Uncertain'}[g.agreement]||g.agreement)),node('p',g.comment),node('p',date(g.createdAt),'jev-help'));detail.append(d);}}
    sync();
  }
  async function open(id){const result=await api('/v1/jev/reviews/'+encodeURIComponent(id));if(typeof result.canWrite==='boolean')canWrite=result.canWrite;if(result.mode){mode=result.mode;renderMode();}render(result.review);const url=new URL(location.href);url.searchParams.set('review',result.review.id);history.replaceState(null,'',url);list.querySelectorAll('button').forEach(e=>e.setAttribute('aria-current','false'));}
  async function mutate(path,body,retry=false){if(busy||!canWrite)return;if(pending&&!retry){note('Recover the original unconfirmed action first.',true);return;}try{if(!retry)remember({path,body:{...body,requestKey:key()}});}catch{note('This browser cannot preserve the original action for recovery. Enable session storage before continuing.',true);return;}
    busy=true;sync();note('Saving the original action…');const intent=pending;try{const result=await api(intent.path,intent.body);remember(null);if(result.review){render(result.review);const url=new URL(location.href);url.searchParams.set('review',result.review.id);history.replaceState(null,'',url);}await refresh();if(current)await open(current.id);note('The original action is confirmed.');}catch(e){if(e.status>=400&&e.status<500&&![401,403,408,429].includes(e.status))remember(null);note(e.message,true);}finally{busy=false;sync();}}
  $('[data-jev-pages]').addEventListener('submit',async event=>{event.preventDefault();if(busy||pending)return;const store=new FormData(event.currentTarget).get('store').trim();busy=true;sync();try{const result=await api('/v1/jev/pages?store='+encodeURIComponent(store));loadedStore=result.store||store;pages=result.pages||[];const select=$('[name=pageId]');select.replaceChildren();for(const p of pages){const o=node('option',(p.name||p.id)+' · '+words(p.status));o.value=p.id;select.append(o);}$('[data-jev-create]').hidden=!pages.length;revision();note(pages.length?'Choose the saved page and describe the concern.':'No saved pages were found for this store.');}catch(e){note(e.message,true);}finally{busy=false;sync();}});
  function revision(){const p=pages.find(p=>p.id===$('[name=pageId]').value);$('[data-jev-revision]').textContent=p?'This request will review revision '+p.revision+'. Later edits require a separate review.':'';}
  $('[name=pageId]').addEventListener('change',revision);
  $('[data-jev-create]').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget),page=pages.find(p=>p.id===data.get('pageId'));if(page)mutate('/v1/jev/reviews',{store:loadedStore,pageId:page.id,expectedRevision:page.revision,reportText:data.get('reportText').trim()});});
  $('[data-jev-refresh]').addEventListener('click',()=>refresh().then(()=>current&&open(current.id)).catch(e=>note(e.message,true)));
  $('[data-jev-retry]').addEventListener('click',()=>pending&&mutate(pending.path,pending.body,true));
  sync();refresh().then(()=>{const id=new URL(location.href).searchParams.get('review');if(id)return open(id);}).catch(e=>note(e.message,true));
})();
