<?php
declare(strict_types=1);
if (!isset($authenticated) || !$authenticated) { http_response_code(404); exit; }
ez_page_header('Marketing', 'Write emails, choose customer groups, and plan your campaigns.');
?>
<section class="marketing-workspace" data-marketing data-store="<?= ez_admin_escape($sellerId) ?>">
  <div class="marketing-toolbar"><p class="marketing-muted" data-marketing-status role="status">Loading your campaigns…</p><div class="marketing-actions"><button class="ui-button" type="button" data-marketing-refresh>Refresh campaigns</button><button class="ui-button primary" type="button" data-marketing-new disabled data-ui-icon="plus">New campaign</button></div></div>
  <section class="page-stat-strip" aria-label="Saved campaign totals">
    <article><div><small>Current campaigns</small><strong data-marketing-count="active">—</strong><p>Drafts and published campaigns</p></div></article>
    <article><div><small>On your calendar</small><strong data-marketing-count="planned">—</strong><p>Planned reminders and send schedules</p></div></article>
    <article><div><small>Archived campaigns</small><strong data-marketing-count="archived">—</strong><p>Kept with their saved history</p></div></article>
  </section>
  <aside class="marketing-readiness"><span class="marketing-readiness-icon"><?= ez_admin_icon('mail') ?></span><div><h2>Email campaigns</h2><p data-marketing-delivery>Checking delivery availability…</p><p data-marketing-audience-availability></p></div></aside>
  <aside class="marketing-local-drafts" data-marketing-local hidden><h2>Unfinished drafts in this tab</h2><p class="marketing-muted">Reopen a draft to finish editing or confirm a pending save.</p><div class="marketing-actions" data-marketing-local-items></div></aside>
  <aside class="marketing-local-drafts" data-campaign-delivery-recovery hidden></aside>
  <section class="surface marketing-library" aria-labelledby="marketing-library-heading">
    <header class="surface-header"><div><h2 id="marketing-library-heading">Your campaigns</h2><p>Build your message, choose an audience, and keep track of your plans.</p></div><div class="marketing-actions" aria-label="Campaign view"><button type="button" class="ui-button" data-marketing-view="list" aria-pressed="true">Campaign list</button><button type="button" class="ui-button" data-marketing-view="calendar" aria-pressed="false">Planning calendar</button></div></header>
    <form class="marketing-filters" data-marketing-filters><label>Find a campaign<input type="search" name="q" maxlength="120" placeholder="Campaign name or subject"></label><label>Show<select name="state"><option value="active">Current campaigns</option><option value="archived">Archived campaigns</option><option value="all">All campaigns</option></select></label><label data-marketing-month-label hidden>Calendar month<input type="month" name="month" min="2000-01" max="2099-12"></label><button type="submit" class="ui-button">Apply filters</button></form>
    <p class="marketing-muted" data-marketing-list-status role="status"></p><div class="marketing-campaign-list" data-marketing-list></div>
    <div class="marketing-calendar" data-marketing-calendar hidden></div>
    <footer class="marketing-library-footer"><button type="button" class="ui-button" data-marketing-more hidden>Load more campaigns</button><button type="button" class="ui-button" data-marketing-list-retry hidden>Try loading again</button><p class="marketing-muted" data-marketing-calendar-note hidden>Dates use your store’s timezone. Planned drafts are reminders. Published campaigns show their send schedule.</p></footer>
  </section>
  <section class="surface marketing-editor" data-marketing-editor hidden aria-labelledby="marketing-editor-title">
    <header class="surface-header"><div><h2 id="marketing-editor-title" data-marketing-editor-title tabindex="-1">Campaign draft</h2><p data-marketing-editor-meta></p></div><div class="marketing-actions"><button type="button" class="ui-button" data-marketing-preview>Preview email</button><button type="button" class="ui-button" data-marketing-history>Saved history</button><button type="button" class="ui-button" data-marketing-close>Close editor</button></div></header>
    <form data-marketing-form>
      <fieldset class="marketing-edit-fields"><legend class="marketing-sr-only">Campaign details</legend>
        <div class="marketing-editor-columns">
          <div class="marketing-copy-fields"><h3>Your message</h3><label>Campaign name<input name="name" aria-label="Campaign name" type="text" maxlength="120" required autocomplete="off"><small>For your team. Customers see the email subject.</small></label>
            <label>Email subject<input name="subject" type="text" maxlength="160" autocomplete="off"></label><label>Inbox preview text<input name="preheader" aria-label="Inbox preview text" type="text" maxlength="200" autocomplete="off"><small>The short introduction beside the subject in an inbox.</small></label>
            <label>Email heading<input name="heading" type="text" maxlength="160"></label><label>Email message<textarea name="body" aria-label="Email message" rows="9" maxlength="6000" placeholder="Share what is new, useful, or worth coming back for."></textarea><small>Plain text. Paragraph breaks are kept in the email.</small></label>
            <label>Store button label<input name="buttonLabel" aria-label="Store button label" type="text" maxlength="60" placeholder="Explore the store"><small>Leave empty to omit the button.</small></label><p class="marketing-muted">Button destination: <a data-marketing-shop target="_blank" rel="noopener">Your store</a><span data-marketing-shop-state></span></p>
          </div>
          <div class="marketing-audience-fields"><h3>Choose your audience</h3><label>Start from a saved segment<select name="segment" aria-label="Start from a saved segment"><option value="">Choose a saved segment</option></select><small>Copies its current filters into this draft. Later segment changes do not change your campaign.</small></label>
            <div class="marketing-filter-grid">
              <label class="marketing-wide">Customer search<input name="audience.q" type="search" maxlength="120" placeholder="Name, email or phone"></label>
              <label class="marketing-wide">Customer group<select name="audience.activity"><option value="all">All customers</option><option value="high_value">High value · Rp150.000+</option><option value="one_order">One checkout</option><option value="repeat">Repeat paid buyers</option><option value="no_paid">No paid order</option></select></label>
              <label>Delivery location<input name="audience.location" type="text" maxlength="100"></label><label>Customer tag<input name="audience.tag" type="text" maxlength="32"></label>
              <label class="marketing-wide">Minimum customer value (Rp)<input name="audience.minSpend" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="19"></label>
              <label>Minimum orders<input name="audience.minOrders" type="number" min="0" max="1000000000" step="1"></label><label>Maximum orders<input name="audience.maxOrders" type="number" min="0" max="1000000000" step="1"></label>
              <label>Last order from<input name="audience.lastFrom" type="date"></label><label>Last order through<input name="audience.lastTo" type="date"></label>
            </div>
            <small>Order-date filters use Jakarta time (WIB).</small><div class="marketing-plan"><h3>Plan your campaign</h3><label>Planned date and time<input name="plannedAt" aria-label="Planned date and time" type="datetime-local" min="2000-01-01T00:00" max="2099-12-31T23:59"><small data-marketing-timezone></small></label><p class="marketing-muted">Add a reminder to your planning calendar. Saving a draft never sends an email.</p><label class="marketing-check"><input name="archived" type="checkbox">Archive this campaign</label></div>
          </div>
        </div>
      </fieldset>
      <div class="marketing-editor-footer"><p data-marketing-save-status role="status" class="marketing-muted"></p><p data-marketing-save-error role="alert" class="marketing-error" hidden></p><div class="marketing-actions"><button type="submit" class="ui-button primary" data-marketing-save>Save draft</button><button type="button" class="ui-button primary" data-marketing-retry hidden>Retry original save</button><button type="button" class="ui-button" data-marketing-compare-saved>Review saved version</button><button type="button" class="ui-button" data-marketing-audience>Preview audience</button><button type="button" class="ui-button" data-marketing-discard-new hidden>Discard new draft</button><button type="button" class="ui-button" data-marketing-storage-retry hidden>Check browser storage</button></div></div>
    </form>
    <section class="marketing-publication" data-campaign-delivery aria-labelledby="campaign-delivery-title"></section>
  </section>
  <dialog class="marketing-dialog" data-marketing-discard-dialog aria-labelledby="marketing-discard-title"><h2 id="marketing-discard-title">Discard this new draft?</h2><p>This draft has not been saved. Discarding it removes its copy from this browser tab.</p><div class="marketing-actions"><button type="button" class="ui-button" data-marketing-dialog-close autofocus>Keep editing</button><button type="button" class="ui-button primary" data-marketing-confirm-discard>Discard draft</button></div></dialog>
  <dialog class="marketing-dialog" data-marketing-comparison aria-labelledby="marketing-comparison-title"><h2 id="marketing-comparison-title">Compare your campaign</h2><p data-marketing-comparison-note></p><div data-marketing-comparison-rows></div><div class="marketing-actions"><button type="button" class="ui-button primary" data-marketing-use-merged>Use compared changes</button><button type="button" class="ui-button" data-marketing-use-saved>Use saved version</button><button type="button" class="ui-button" data-marketing-dialog-close>Keep my draft</button></div></dialog>
  <dialog class="marketing-dialog marketing-email-preview" data-marketing-preview-dialog aria-labelledby="marketing-preview-title"><div class="marketing-dialog-heading"><h2 id="marketing-preview-title">Email preview</h2><button type="button" class="ui-button" data-marketing-dialog-close>Close preview</button></div><p><b>Subject:</b> <span data-marketing-preview-subject></span></p><p class="marketing-muted">Preview of your current draft. No email has been sent.</p><iframe title="Campaign email preview" sandbox="" referrerpolicy="no-referrer"></iframe></dialog>
  <dialog class="marketing-dialog" data-marketing-audience-dialog aria-labelledby="marketing-audience-title"><div class="marketing-dialog-heading"><h2 id="marketing-audience-title">Audience preview</h2><button type="button" class="ui-button" data-marketing-dialog-close>Close audience</button></div><p class="marketing-muted">Based on current customer records and these draft filters. Recorded permission is specific to this store and email address. Permission and the account address must be checked again before delivery.</p><div class="marketing-audience-totals" data-marketing-audience-totals></div><p data-marketing-audience-status role="status"></p><ul class="marketing-audience-list" data-marketing-audience-items></ul><div class="marketing-actions"><button type="button" class="ui-button" data-marketing-audience-more hidden>Load more customers</button><button type="button" class="ui-button" data-marketing-audience-retry hidden>Try audience again</button></div></dialog>
  <dialog class="marketing-dialog" data-marketing-history-dialog aria-labelledby="marketing-history-title"><div class="marketing-dialog-heading"><h2 id="marketing-history-title">Campaign history</h2><button type="button" class="ui-button" data-marketing-dialog-close>Close history</button></div><p data-marketing-history-status role="status"></p><ol data-marketing-history-items></ol><div class="marketing-actions"><button type="button" class="ui-button" data-marketing-history-more hidden>Load older changes</button><button type="button" class="ui-button" data-marketing-history-retry hidden>Try history again</button></div></dialog>
</section>
