<section class="shipping-workspace" data-shipping-settings>
  <header class="page-heading"><div><a class="ui-button" href="?page=<?= ($_GET['setup'] ?? '') === '1' ? 'onboarding' : 'settings' ?>"><?= ez_admin_icon('chevron-left') ?><span><?= ($_GET['setup'] ?? '') === '1' ? 'Back to seller setup' : 'Settings' ?></span></a><h1>Shipping settings</h1><p>Manage the addresses and couriers your store uses for delivery.</p></div><div class="shipping-heading-actions"><button type="button" class="ui-button" data-shipping-reload data-ui-icon="refresh">Reload saved settings</button><button type="button" class="ui-button primary" data-shipping-save disabled data-ui-icon="eye">Review changes</button></div></header>
  <p class="shipping-notice" data-shipping-status role="status">Loading shipping settings…</p>
  <p class="shipping-error" data-shipping-error role="alert" hidden></p>
  <div class="shipping-recovery" data-shipping-recovery hidden><p>A previous save still needs confirmation. Check it before making more changes.</p><button type="button" class="ui-button" data-shipping-retry data-ui-icon="eye">Check original save</button></div>
  <div class="shipping-settings-layout">
    <div><section class="surface shipping-section"><header><div><h2>Address book</h2><p>Save up to 10 locations. Your chosen pickup address applies to new orders.</p></div><button type="button" class="ui-button" data-shipping-add disabled><?= ez_admin_icon('plus') ?>Add address</button></header><div class="shipping-addresses" data-shipping-addresses></div></section>
      <section class="surface shipping-section"><header><div><h2>Delivery couriers</h2><p>Customers see the enabled couriers that return a rate for their address and package.</p></div></header><fieldset class="shipping-couriers" data-shipping-couriers disabled><legend class="sr-only">Enabled couriers</legend></fieldset><p class="shipping-help">Instant couriers need a saved pickup pin and a customer's delivery pin. Availability and prices are confirmed at checkout.</p></section>
    </div>
    <aside><section class="surface shipping-section"><header><div><h2>Default addresses</h2><p>Existing orders keep their original addresses.</p></div></header><label>Pickup address<select data-shipping-pickup disabled></select></label><label>Return address<select data-shipping-return disabled></select></label><p class="shipping-help">The return address is saved with each new order for return arrangements. Each order ships from one pickup location.</p></section>
      <section class="surface shipping-section"><header><h2>Recent changes</h2></header><ol class="shipping-history" data-shipping-history></ol></section></aside>
  </div>
  <dialog class="shipping-dialog shipping-address-dialog" data-shipping-address-dialog aria-labelledby="shipping-address-title"><header><h2 id="shipping-address-title">Add address</h2><button type="button" class="ui-button" data-shipping-address-close aria-label="Close address editor">×</button></header>
    <form id="shipping-address-form" data-shipping-address-form><div class="shipping-fields">
      <label class="wide">Address label<input name="label" required minlength="2" maxlength="50" placeholder="Main warehouse"></label>
      <label>Contact name<input name="name" required minlength="2" maxlength="100" autocomplete="name"></label><label>Phone number<input name="phone" required type="tel" maxlength="20" placeholder="081234567890" autocomplete="tel"></label>
      <label>Contact email <small>(optional)</small><input name="email" type="email" maxlength="120" autocomplete="email"></label><label>Organization <small>(optional)</small><input name="organization" maxlength="100" autocomplete="organization"></label>
      <label class="wide">Street address<textarea name="address" required minlength="5" maxlength="300" autocomplete="street-address" rows="3" placeholder="Street, building and unit number"></textarea></label>
      <label>City or district<input name="location" required minlength="3" maxlength="120" autocomplete="address-level2"></label><label>Postcode<input name="postalCode" required inputmode="numeric" pattern="[1-9][0-9]{4}" maxlength="5" autocomplete="postal-code"></label>
      <label class="wide">Courier instructions <small>(optional)</small><input name="note" maxlength="120" placeholder="Entrance, landmark or collection instructions"></label>
    </div><div class="shipping-location-panel"><div data-shipping-map></div><p class="shipping-help">Confirm the entrance to include this pin, or save the address without a pin. Instant couriers require a pickup pin.</p><div class="shipping-heading-actions"><button type="button" class="ui-button" data-shipping-confirm-pin data-ui-icon="check">Use this map pin</button><button type="button" class="ui-button" data-shipping-clear-pin data-ui-icon="trash">Remove pin</button></div><p class="shipping-error" data-shipping-address-error role="alert" hidden></p></div></form>
    <footer><button type="button" class="ui-button" data-shipping-address-close data-ui-icon="x">Cancel</button><button type="submit" form="shipping-address-form" class="ui-button primary" data-ui-icon="check">Use this address</button></footer>
  </dialog>
  <dialog class="shipping-dialog" data-shipping-review aria-labelledby="shipping-review-title"><header><h2 id="shipping-review-title">Review shipping changes</h2><button type="button" class="ui-button" data-shipping-review-close aria-label="Close review">×</button></header><div class="shipping-review-body" data-shipping-preview></div><p class="shipping-error" data-shipping-review-error role="alert" hidden></p><footer><button type="button" class="ui-button" data-shipping-review-close data-ui-icon="arrow-left">Back</button><button type="button" class="ui-button primary" data-shipping-confirm data-ui-icon="save">Save shipping settings</button></footer></dialog>
</section>
