<?php
declare(strict_types=1);
?>
<section class="sq-studio sq-site-loading" id="visual-builder" aria-label="Landing page builder" aria-busy="true">
  <header class="sq-commandbar">
    <div class="sq-page-identity">
      <a href="?page=sites" aria-label="Return to landing pages"><?= ez_admin_icon('chevron-left') ?></a>
      <button type="button" data-sq-open-panel="pages"><span><small>Landing page</small><b data-current-site-name>Landing page</b></span><?= ez_admin_icon('chevron-down') ?></button>
      <span class="sq-live-state"><i></i> Draft</span>
    </div>
    <div class="sq-history-tools" aria-label="Editing history">
      <button type="button" data-sq-undo aria-label="Undo" disabled><?= ez_admin_icon('undo') ?></button>
      <button type="button" data-sq-redo aria-label="Redo" disabled><?= ez_admin_icon('redo') ?></button>
      <span data-sq-save-state>All changes saved</span>
    </div>
    <div class="sq-device-tools" aria-label="Responsive preview">
      <button class="active" type="button" data-sq-device="desktop" aria-label="Desktop preview"><?= ez_admin_icon('monitor') ?></button>
      <button type="button" data-sq-device="tablet" aria-label="Tablet preview"><?= ez_admin_icon('layout') ?></button>
      <button type="button" data-sq-device="mobile" aria-label="Mobile preview"><?= ez_admin_icon('smartphone') ?></button>
      <button type="button" data-sq-fit aria-label="Fit canvas to window"><?= ez_admin_icon('refund') ?></button>
    </div>
    <div class="sq-command-actions">
      <button type="button" data-sq-preview><?= ez_admin_icon('eye') ?><span>Preview</span></button>
      <button type="button" data-sq-export><?= ez_admin_icon('code') ?><span>Export HTML</span></button>
      <button class="primary" type="button" data-sq-publish>Publish</button>
    </div>
  </header>

  <div class="sq-editor-grid">
    <aside class="sq-builder-sidebar">
      <nav class="sq-tool-rail" aria-label="Builder tools">
        <button class="active" type="button" data-sq-tab="layers" aria-label="Page layers"><?= ez_admin_icon('layers') ?><span>Layers</span></button>
        <button type="button" data-sq-tab="add" aria-label="Add section"><?= ez_admin_icon('plus') ?><span>Add</span></button>
        <button type="button" data-sq-tab="products" aria-label="Products"><?= ez_admin_icon('box') ?><span>Products</span><i data-sq-product-count>0</i></button>
        <button type="button" data-sq-tab="brand" aria-label="Brand styling"><?= ez_admin_icon('palette') ?><span>Brand</span></button>
        <button type="button" data-sq-tab="pages" aria-label="Pages and domains"><?= ez_admin_icon('globe') ?><span>Pages</span></button>
      </nav>

      <div class="sq-tool-panels">
        <section class="sq-tool-panel active" data-sq-panel="layers">
          <header><div><small>Page structure</small><h2>Layers</h2></div><button type="button" data-sq-open-panel="add" aria-label="Add section"><?= ez_admin_icon('plus') ?></button></header>
          <p class="sq-panel-intro">Drag sections to reorder them. Click anything to edit it.</p>
          <div class="sq-layer-list" data-sq-layer-list aria-label="Sections and elements"></div>
          <footer><span><?= ez_admin_icon('shield') ?> Autosaved and versioned</span></footer>
        </section>

        <section class="sq-tool-panel" data-sq-panel="add">
          <header><div><small>Section library</small><h2>Add content</h2></div></header>
          <label class="sq-panel-search"><?= ez_admin_icon('search') ?><input type="search" placeholder="Search elements or sections" data-sq-block-search></label>
          <div class="sq-block-group"><h3>Text &amp; movement</h3><div class="sq-block-grid sq-element-library">
            <button type="button" data-sq-add-element="heading" data-search="heading title text"><?= ez_admin_icon('message') ?><b>Heading</b><small>Independent headline</small></button>
            <button type="button" data-sq-add-element="text" data-search="paragraph text copy"><?= ez_admin_icon('message') ?><b>Text</b><small>Body copy block</small></button>
            <button type="button" data-sq-add-element="marquee" data-search="marquee ticker scrolling moving announcement text"><?= ez_admin_icon('trend') ?><b>Marquee</b><small>Looping text ticker</small></button>
          </div></div>
          <div class="sq-block-group"><h3>Media &amp; structure</h3><div class="sq-block-grid sq-element-library">
            <button type="button" data-sq-add-element="image" data-search="image photo picture"><?= ez_admin_icon('image') ?><b>Image</b><small>Single movable image</small></button>
            <button type="button" data-sq-add-element="divider" data-search="divider line separator"><?= ez_admin_icon('layers') ?><b>Divider</b><small>Visual separator</small></button>
            <button type="button" data-sq-add-element="html" data-search="html css javascript code embed custom"><?= ez_admin_icon('code') ?><b>HTML / code</b><small>Sandboxed custom code</small></button>
          </div></div>
          <div class="sq-block-group"><h3>Actions &amp; capture</h3><div class="sq-block-grid sq-element-library">
            <button type="button" data-sq-add-element="button" data-search="button call action"><?= ez_admin_icon('play') ?><b>Button</b><small>Linked action</small></button>
            <button type="button" data-sq-add-element="form" data-search="form email newsletter lead"><?= ez_admin_icon('mail') ?><b>Form</b><small>Email capture</small></button>
          </div><p class="sq-library-note">Add to the selected section, then move, resize, duplicate, hide, or delete it independently.</p></div>
          <div class="sq-block-group sq-components-library"><div class="sq-components-heading"><h3>Components</h3><span data-sq-component-count>0 / 20</span></div><button class="sq-create-component" type="button" data-sq-create-component><?= ez_admin_icon('plus') ?><span><b>Create component</b><small>Save reusable HTML, CSS &amp; JS</small></span></button><div class="sq-component-list" data-sq-component-list></div><p class="sq-component-empty" data-sq-component-empty>Your main components will appear here. Drag an instance onto any section.</p></div>
          <div class="sq-block-group"><h3>Commerce</h3><div class="sq-block-grid">
            <button type="button" data-sq-add-block="products" data-search="products shop collection"><?= ez_admin_icon('box') ?><b>Products</b><small>Multi-product grid</small></button>
            <button type="button" data-sq-add-block="checkout" data-search="checkout payment midtrans"><?= ez_admin_icon('credit-card') ?><b>Checkout</b><small>Secure cart CTA</small></button>
          </div></div>
          <div class="sq-block-group"><h3>Image-led</h3><div class="sq-block-grid">
            <button type="button" data-sq-add-block="full-image" data-search="image photo full bleed"><?= ez_admin_icon('image') ?><b>Full image</b><small>No text required</small></button>
            <button type="button" data-sq-add-block="gallery" data-search="gallery images photos"><?= ez_admin_icon('layout') ?><b>Gallery</b><small>Editorial mosaic</small></button>
            <button type="button" data-sq-add-block="blank" data-search="blank empty canvas custom"><?= ez_admin_icon('plus') ?><b>Blank canvas</b><small>Build from nothing</small></button>
          </div></div>
          <div class="sq-block-group"><h3>Story &amp; trust</h3><div class="sq-block-grid">
            <button type="button" data-sq-add-block="text" data-search="text story copy"><?= ez_admin_icon('message') ?><b>Text</b><small>Headline and body</small></button>
            <button type="button" data-sq-add-block="testimonials" data-search="reviews testimonials trust"><?= ez_admin_icon('star') ?><b>Reviews</b><small>Social proof</small></button>
            <button type="button" data-sq-add-block="faq" data-search="faq questions"><?= ez_admin_icon('help') ?><b>FAQ</b><small>Expandable answers</small></button>
            <button type="button" data-sq-add-block="spacer" data-search="space spacer gap"><?= ez_admin_icon('layers') ?><b>Spacer</b><small>Responsive breathing room</small></button>
          </div></div>
        </section>

        <section class="sq-tool-panel" data-sq-panel="products">
          <header><div><small>Commerce source</small><h2>Products</h2></div><a href="?page=products">Manage</a></header>
          <p class="sq-panel-intro">Use one product or the whole catalog. Ezkart keeps price, stock, checkout items, and shipping weights synchronized.</p>
          <div class="sq-product-picker">
            <p class="sq-products-empty" data-sq-products-empty>No catalog products are available. <a href="?page=products">Create a product</a> before building a landing page.</p>
          </div>
          <div class="sq-product-rule"><span><?= ez_admin_icon('check-circle') ?></span><p><b>At least one product</b><small>A landing page always needs something customers can purchase.</small></p></div>
        </section>

        <section class="sq-tool-panel sq-brand-panel" data-sq-panel="brand">
          <header><div><small>Global identity</small><h2>Branding</h2></div></header>
          <div class="sq-brand-intro"><span><?= ez_admin_icon('palette') ?></span><div><b>One system, everywhere</b><small>Colors, typography, shapes, and buttons stay synchronized across the entire page.</small></div></div>
          <div class="sq-control-section" data-sq-brand-palette><div class="sq-inspector-heading"><h3>Brand palette</h3><span>Page-wide</span></div><div class="sq-theme-grid"><button class="active coral" type="button" data-sq-theme="theme-coral" aria-label="Coral theme"></button><button class="forest" type="button" data-sq-theme="theme-forest" aria-label="Forest theme"></button><button class="indigo" type="button" data-sq-theme="theme-indigo" aria-label="Indigo theme"></button><button class="charcoal" type="button" data-sq-theme="theme-charcoal" aria-label="Charcoal theme"></button></div><div class="sq-brand-colors"><label><span>Accent</span><input type="color" value="#f44b34" data-sq-brand-color="accent"><output data-sq-brand-color-output="accent">#F44B34</output></label><label><span>Page</span><input type="color" value="#fffbf7" data-sq-brand-color="page"><output data-sq-brand-color-output="page">#FFFBF7</output></label><label><span>Text</span><input type="color" value="#24262b" data-sq-brand-color="ink"><output data-sq-brand-color-output="ink">#24262B</output></label><label><span>Surface</span><input type="color" value="#ffffff" data-sq-brand-color="surface"><output data-sq-brand-color-output="surface">#FFFFFF</output></label></div></div>
          <div class="sq-control-section"><div class="sq-inspector-heading"><h3>Typography</h3><span>Page-wide</span></div><div class="sq-brand-type-grid"><label><span>Heading font</span><select data-sq-brand-font="heading"><option value="Poppins, sans-serif">Poppins</option><option value="Arial, Helvetica, sans-serif">Modern Sans</option><option value="Georgia, 'Times New Roman', serif">Editorial Serif</option><option value="'Times New Roman', Times, serif">Classic Serif</option><option value="ui-monospace, SFMono-Regular, Consolas, monospace">Mono</option></select></label><label><span>Body font</span><select data-sq-brand-font="body"><option value="Poppins, sans-serif">Poppins</option><option value="Arial, Helvetica, sans-serif">Modern Sans</option><option value="Georgia, 'Times New Roman', serif">Editorial Serif</option><option value="'Times New Roman', Times, serif">Classic Serif</option><option value="ui-monospace, SFMono-Regular, Consolas, monospace">Mono</option></select></label></div><label><span>Base size</span><input type="range" min="13" max="20" value="16" data-sq-font-size><output data-sq-font-output>16px</output></label></div>
          <div class="sq-control-section sq-button-system" data-sq-brand-button-system><div class="sq-inspector-heading"><h3>Button system</h3><span>3 reusable roles</span></div><label><span>Editing role</span><select data-sq-button-style-role><option value="primary">Primary</option><option value="secondary">Secondary</option><option value="tertiary">Tertiary</option></select></label><div class="sq-button-color-row"><label><span>Fill</span><input type="color" value="#f44b34" data-sq-button-color="bg"></label><label><span>Text</span><input type="color" value="#ffffff" data-sq-button-color="fg"></label><label><span>Border</span><input type="color" value="#f44b34" data-sq-button-color="border"></label></div><div class="sq-brand-type-grid"><label><span>Treatment</span><select data-sq-button-treatment><option value="solid">Solid</option><option value="outline">Outline</option><option value="soft">Soft</option><option value="text">Text only</option></select></label><label><span>Weight</span><select data-sq-button-weight><option value="500">Medium</option><option value="600">Semibold</option><option value="700">Bold</option></select></label></div><div class="sq-brand-type-grid"><label><span>Shadow</span><select data-sq-button-shadow><option value="none">None</option><option value="soft">Soft</option><option value="strong">Strong</option></select></label><label><span>Letter case</span><select data-sq-button-case><option value="none">Normal</option><option value="uppercase">Uppercase</option></select></label></div><label><span>Corner radius</span><input type="range" min="0" max="40" value="24" data-sq-button-radius><output data-sq-button-radius-output>24px</output></label><div class="sq-brand-type-grid"><label><span>Border width</span><input type="range" min="0" max="6" step="1" value="0" data-sq-button-border-width><output data-sq-button-border-width-output>0px</output></label><label><span>Button height</span><input type="range" min="30" max="64" step="1" value="42" data-sq-button-height><output data-sq-button-height-output>42px</output></label></div><button class="sq-button-live-preview button-primary" type="button" data-sq-button-preview><span>Button preview</span></button></div>
          <div class="sq-control-section"><div class="sq-inspector-heading"><h3>Shape &amp; layout</h3><span>Page-wide</span></div><label><span>Corner style</span><select data-sq-radius><option value="radius-soft">Soft · 16px</option><option value="radius-round">Rounded · 28px</option><option value="radius-square">Square · 4px</option></select></label><label><span>Page layout</span><select data-sq-layout><option value="layout-rich">Balanced commerce</option><option value="layout-editorial">Editorial images</option><option value="layout-image-only">Image-first / no default copy</option></select></label></div>
        </section>

        <section class="sq-tool-panel" data-sq-panel="pages">
          <header><div><small>Website</small><h2>Pages &amp; hosting</h2></div><button type="button" data-open-page-creator aria-label="New landing page"><?= ez_admin_icon('plus') ?></button></header>
          <div class="sq-page-list">
            <template data-sq-site-template><button type="button" data-sq-site><span><?= ez_admin_icon('layout') ?></span><div><b>Landing page</b><small>page.ezkart.site</small></div><em class="draft">Draft</em></button></template>
          </div>
          <div class="sq-host-card"><span><?= ez_admin_icon('shield') ?></span><div><b>Managed hosting</b><small>Global CDN · 99.99% uptime</small></div><em>Active</em></div>
          <button class="sq-wide-button" type="button" data-toast="Domain manager opened">Manage domains &amp; SEO</button>
        </section>
      </div>
    </aside>

    <main class="sq-canvas-stage">
      <div class="sq-canvas-meta"><span><?= ez_admin_icon('shield') ?><b data-current-site-url>ezkart.site</b></span><div><button type="button" data-sq-zoom-out aria-label="Zoom out">−</button><output data-sq-zoom>80%</output><button type="button" data-sq-zoom-in aria-label="Zoom in">+</button></div></div>
      <div class="sq-canvas-scroll">
        <div class="sq-site-loader" role="status" aria-live="polite" aria-atomic="true">
          <span class="sq-site-loader-worm" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span>
          <span class="sq-site-loader-copy"><b>Loading your page</b><small>Preparing your Ezkart canvas</small></span>
        </div>
        <div class="sq-device-frame" data-sq-device-frame>
          <article class="sq-page-preview theme-coral radius-soft layout-rich" data-sq-preview-root>
            <section class="sq-page-block sq-announcement selected" draggable="true" data-sq-block data-sq-fluid data-sq-rows="2" data-section-id="announcement"><button class="sq-block-handle" type="button" aria-label="Drag announcement section"><?= ez_admin_icon('grip') ?></button><p data-sq-element data-sq-element-type="text" data-layout-desktop="1,1,12,2" data-layout-tablet="1,1,12,2" data-layout-mobile="1,1,12,2">Secure checkout for every product on this page</p></section>
            <nav class="sq-page-block sq-store-nav" draggable="true" data-sq-block data-sq-fluid data-sq-rows="2" data-section-id="navigation"><button class="sq-block-handle" type="button" aria-label="Drag navigation section"><?= ez_admin_icon('grip') ?></button><div class="sq-site-logo" data-sq-element data-sq-element-type="logo" data-layout-desktop="1,1,4,2" data-layout-tablet="1,1,5,2" data-layout-mobile="1,1,6,2"><img data-sq-logo-image alt="" hidden><b data-sq-logo-text>Morning Ritual</b></div><div data-sq-element data-sq-element-type="navigation" data-layout-desktop="7,1,6,2" data-layout-tablet="6,1,7,2" data-layout-mobile="7,1,6,2"><a href="#products">Shop</a><a href="#story">Our story</a><a href="#shipping" data-physical-only>Delivery</a><button type="button">Buy now</button></div></nav>
            <section class="sq-page-block sq-hero sq-hero-elements" draggable="true" data-sq-block data-sq-fluid data-sq-rows="15" data-section-id="hero"><button class="sq-block-handle" type="button" aria-label="Drag hero section"><?= ez_admin_icon('grip') ?></button><span class="sq-hero-kicker" data-sq-element data-sq-element-type="eyebrow" data-layout-desktop="1,3,6,1" data-layout-tablet="1,1,12,1" data-layout-mobile="1,1,12,1">Made with care · ready when you are</span><h1 class="sq-hero-heading" data-sq-element data-sq-element-type="heading" data-sq-content="headline" data-layout-desktop="1,4,6,5" data-layout-tablet="1,2,12,4" data-layout-mobile="1,2,12,4">Small-batch favorites for a better everyday ritual.</h1><p class="sq-hero-description" data-sq-element data-sq-element-type="text" data-sq-content="description" data-layout-desktop="1,9,6,3" data-layout-tablet="1,6,12,2" data-layout-mobile="1,6,12,3">Discover thoughtful products and a secure checkout with fulfillment matched to what you buy.</p><button class="sq-hero-action button-primary" type="button" data-sq-element data-sq-element-type="button" data-sq-button-role="primary" data-sq-link-type="section" data-sq-link="products" data-sq-new-tab="false" data-sq-content="cta" data-layout-desktop="1,12,3,2" data-layout-tablet="1,8,5,2" data-layout-mobile="1,9,7,2">Shop the collection</button><small class="sq-hero-trust" data-sq-element data-sq-element-type="trust-note" data-layout-desktop="4,12,3,2" data-layout-tablet="6,8,7,2" data-layout-mobile="1,11,12,1"><?= ez_admin_icon('shield') ?> Secure checkout powered by Ezkart</small><div class="sq-hero-collage" data-sq-element data-sq-element-type="collage" data-layout-desktop="7,2,6,12" data-layout-tablet="1,10,12,7" data-layout-mobile="1,12,12,7" data-sq-image-list><span class="large" draggable="true" tabindex="0" data-sq-image-item data-product-visual="granola" aria-label="Granola image — drag to rearrange"><?= ez_admin_product_art('Granola Madu Nusantara') ?></span><span draggable="true" tabindex="0" data-sq-image-item data-product-visual="coffee" aria-label="Kopi Susu image — drag to rearrange"><?= ez_admin_product_art('Kopi Susu Concentrate') ?></span><span draggable="true" tabindex="0" data-sq-image-item data-product-visual="sambal" aria-label="Sambal Roa image — drag to rearrange"><?= ez_admin_product_art('Sambal Roa Signature') ?></span></div></section>
            <section class="sq-page-block sq-product-section" id="products" draggable="true" data-sq-block data-sq-fluid data-sq-rows="21" data-section-id="products"><button class="sq-block-handle" type="button" aria-label="Drag product section"><?= ez_admin_icon('grip') ?></button><header data-sq-element data-sq-element-type="collection-heading" data-layout-desktop="1,1,12,7" data-layout-tablet="1,1,12,7" data-layout-mobile="1,1,12,7"><div><span>Shop the collection</span><h2>Pick one favorite—or build your whole basket.</h2></div><p>Every item stays synchronized with availability, secure payment, and the right fulfillment flow.</p></header><div class="sq-product-grid" data-sq-element data-sq-element-type="product-grid" data-layout-desktop="1,8,12,14" data-layout-tablet="1,8,12,28" data-layout-mobile="1,8,12,42" data-sq-product-grid>
              <article data-product-card="granola"><?= ez_admin_product_art('Granola Madu Nusantara') ?><div><small>Breakfast · 320 g</small><h3>Granola Madu Nusantara</h3><p>Honey-toasted oats, cashews, and warm local spice.</p><footer><b>Rp58.000</b><button type="button">Add to cart</button></footer></div></article>
              <article data-product-card="coffee"><?= ez_admin_product_art('Kopi Susu Concentrate') ?><div><small>Drinks · 650 ml</small><h3>Kopi Susu Concentrate</h3><p>Rich café-style coffee, balanced and ready in seconds.</p><footer><b>Rp79.000</b><button type="button">Add to cart</button></footer></div></article>
              <article data-product-card="sambal"><?= ez_admin_product_art('Sambal Roa Signature') ?><div><small>Pantry · 260 g</small><h3>Sambal Roa Signature</h3><p>Deep smoke, bright chili, and a savory Manado finish.</p><footer><b>Rp46.000</b><button type="button">Add to cart</button></footer></div></article>
            </div></section>
            <section class="sq-page-block sq-image-story" id="story" draggable="true" data-sq-block data-sq-fluid data-sq-rows="12" data-section-id="image-story"><button class="sq-block-handle" type="button" aria-label="Drag image story section"><?= ez_admin_icon('grip') ?></button><div data-sq-element data-sq-element-type="image" data-layout-desktop="1,1,7,12" data-layout-tablet="1,1,12,6" data-layout-mobile="1,1,12,6"><?= ez_admin_product_art('Granola Madu Nusantara') ?></div><article data-sq-element data-sq-element-type="copy" data-layout-desktop="8,1,5,12" data-layout-tablet="1,7,12,6" data-layout-mobile="1,7,12,6"><span>Image-led storytelling</span><h2>Let the product fill the screen.</h2><p>Use photography as the complete section or pair it with a short story. Image-only layouts are always available, but never forced by default.</p><button type="button">See how it is made</button></article></section>
            <section class="sq-page-block sq-benefit-row" draggable="true" data-sq-block data-sq-fluid data-sq-rows="6" data-section-id="benefits"><button class="sq-block-handle" type="button" aria-label="Drag benefits section"><?= ez_admin_icon('grip') ?></button><article data-sq-element data-sq-element-type="benefit" data-layout-desktop="1,1,4,6" data-layout-tablet="1,1,4,6" data-layout-mobile="1,1,12,2"><?= ez_admin_icon('star') ?><div><b>Clear product details</b><small>Know exactly what you will receive</small></div></article><article data-sq-element data-sq-element-type="benefit" data-layout-desktop="5,1,4,6" data-layout-tablet="5,1,4,6" data-layout-mobile="1,3,12,2"><?= ez_admin_icon('credit-card') ?><div><b>Secure payment</b><small>Checkout details verified by Ezkart</small></div></article><article data-physical-only data-sq-element data-sq-element-type="benefit" data-layout-desktop="9,1,4,6" data-layout-tablet="9,1,4,6" data-layout-mobile="1,5,12,2"><?= ez_admin_icon('truck') ?><div><b>Delivery arranged</b><small>Courier, live rate, and ETA at checkout</small></div></article></section>
            <section class="sq-page-block sq-cart-section" draggable="true" data-sq-block data-sq-fluid data-sq-rows="12" data-section-id="checkout"><button class="sq-block-handle" type="button" aria-label="Drag checkout section"><?= ez_admin_icon('grip') ?></button><div data-sq-element data-sq-element-type="copy" data-layout-desktop="1,1,6,12" data-layout-tablet="1,1,12,5" data-layout-mobile="1,1,12,5"><span>Your basket</span><h2>One checkout for every product on the page.</h2><p>Customers can combine products, choose quantities, and pay once through Ezkart's secure checkout.</p></div><aside data-sq-element data-sq-element-type="checkout" data-layout-desktop="8,2,5,10" data-layout-tablet="1,6,12,7" data-layout-mobile="1,6,12,7"><small>Example basket</small><ul data-sq-basket-lines><li data-product-line="granola"><span>Granola Madu Nusantara</span><b>Rp58.000</b></li><li data-product-line="coffee"><span>Kopi Susu Concentrate</span><b>Rp79.000</b></li><li data-product-line="sambal"><span>Sambal Roa Signature</span><b>Rp46.000</b></li></ul><footer><span>Total</span><strong data-sq-basket-total>Rp183.000</strong></footer><button type="button">Continue to secure checkout</button><em><?= ez_admin_icon('shield') ?> Secure checkout powered by Ezkart</em></aside></section>
            <section class="sq-page-block sq-shipping-section" id="shipping" data-physical-only draggable="true" data-sq-block data-sq-fluid data-sq-rows="5" data-section-id="shipping"><button class="sq-block-handle" type="button" aria-label="Drag shipping section"><?= ez_admin_icon('grip') ?></button><span data-sq-element data-sq-element-type="icon" data-layout-desktop="1,1,1,5" data-layout-tablet="1,1,2,5" data-layout-mobile="1,1,2,5"><?= ez_admin_icon('truck') ?></span><div data-sq-element data-sq-element-type="copy" data-layout-desktop="2,1,7,5" data-layout-tablet="3,1,10,3" data-layout-mobile="3,1,10,3"><small>Ezkart fulfillment</small><h2>From page visit to delivered order.</h2><p>Address collection, product weights, courier quotes, payment state, and fulfillment stay connected in one flow.</p></div><ul data-sq-element data-sq-element-type="list" data-layout-desktop="9,1,4,5" data-layout-tablet="3,4,10,2" data-layout-mobile="3,4,10,2"><li>JNE REG</li><li>SiCepat REG</li><li>J&amp;T EZ</li></ul></section>
          </article>
          <button class="sq-page-height-handle" type="button" role="slider" aria-orientation="vertical" aria-valuemin="0" aria-valuemax="6000" aria-valuenow="0" data-sq-page-height-handle aria-label="Extra page height" title="Drag to extend the page downward"><span></span></button>
        </div>
      </div>
      <footer class="sq-stage-footer">
        <span class="sq-stage-ready"><i></i> Editable canvas</span>
        <div class="sq-stage-scale">
          <span class="sq-stage-size" data-sq-stage-size>Desktop · 1440px</span>
          <label>
            <span>Page scale</span>
            <input type="range" min="40" max="100" step="1" value="90" data-sq-zoom-slider aria-label="Page scale">
            <output data-sq-zoom>90%</output>
          </label>
        </div>
        <span data-sq-commerce-status><?= ez_admin_icon('shield') ?> Checking commerce integrations…</span>
      </footer>
    </main>

    <aside class="sq-inspector">
      <header><div><small data-sq-inspector-context>Selected section</small><h2 data-sq-inspector-title>Announcement</h2></div><button type="button" data-sq-close-inspector aria-label="Close inspector"><?= ez_admin_icon('x') ?></button></header>
      <div class="sq-inspector-scroll">
        <section class="sq-page-spacing-panel" data-sq-page-spacing-controls hidden>
          <div class="sq-spacing-intro"><span><?= ez_admin_icon('layout') ?></span><div><b>Page grid</b><small>Shape the rectangles used to place every block.</small></div></div>
          <div class="sq-page-appearance-card"><div class="sq-inspector-heading"><h3>Page appearance</h3><span>Page-wide</span></div><div class="sq-page-appearance-colors"><label><span>Page</span><input type="color" value="#fffbf7" data-sq-page-brand-color="page"><output data-sq-page-brand-output="page">#FFFBF7</output></label><label><span>Surface</span><input type="color" value="#ffffff" data-sq-page-brand-color="surface"><output data-sq-page-brand-output="surface">#FFFFFF</output></label></div><button type="button" data-sq-page-brand-link>Edit all colors in Branding <?= ez_admin_icon('chevron-right') ?></button></div>
          <div class="sq-layout-grid-controls"><div class="sq-inspector-heading"><h3>Rectangle grid</h3><span data-sq-grid-density-device>Desktop</span></div><label class="sq-show-layout-grid"><input type="checkbox" data-sq-show-layout-grid><span>Keep grid visible</span></label><div class="sq-grid-count"><span>Visible grid</span><strong data-sq-grid-count-output>12 columns × 12 rows</strong></div><label class="sq-grid-density-control"><span>Density · both axes</span><input type="range" min="1" max="5" step="1" value="3" data-sq-grid-density><output data-sq-grid-density-output>Balanced</output></label><div class="sq-grid-density-scale"><span>Fewer rectangles</span><span>More rectangles</span></div><label><span>Rectangle width</span><input type="range" min="6" max="180" step="1" value="100" data-sq-grid-cell-width><output data-sq-grid-cell-width-output>100px</output></label><label><span>Rectangle height</span><input type="range" min="6" max="72" step="1" value="24" data-sq-grid-cell-height><output data-sq-grid-cell-height-output>24px</output></label><label><span>Gap</span><input type="range" min="0" max="40" step="1" value="10" data-sq-page-column-gap><output data-sq-page-column-gap-output>10px</output></label><p class="sq-field-note">The grid appears while you drag or adjust these values, then fades away. Keep it visible only when you want a persistent guide.</p></div>
          <div class="sq-page-spacing-system"><div class="sq-inspector-heading"><h3>Page edges</h3><span>Whole page</span></div><label><span>Desktop gutter</span><input type="range" min="0" max="180" step="2" value="60" data-sq-page-gutter="desktop"><output data-sq-page-gutter-output="desktop">60px</output></label><label><span>Tablet gutter</span><input type="range" min="0" max="120" step="2" value="38" data-sq-page-gutter="tablet"><output data-sq-page-gutter-output="tablet">38px</output></label><label><span>Mobile gutter</span><input type="range" min="0" max="64" step="1" value="22" data-sq-page-gutter="mobile"><output data-sq-page-gutter-output="mobile">22px</output></label><button class="sq-reset-page-spacing" type="button" data-sq-page-spacing-reset>Reset spacing</button></div>
        </section>
        <section class="sq-content-controls" data-sq-section-controls><div class="sq-inspector-heading"><h3>Content</h3><span>Direct edit</span></div><p class="sq-field-note">Edit here or click text directly on the canvas. Every section has its own fields.</p><div class="sq-content-fields" data-sq-content-fields></div></section>
        <section class="sq-element-controls" data-sq-element-controls hidden>
          <button class="sq-inspector-back" type="button" data-sq-select-section><?= ez_admin_icon('chevron-left') ?> Back to section</button>
          <div class="sq-element-tabs" role="tablist" aria-label="Element settings">
            <button class="active" id="sq-element-tab-content" type="button" role="tab" aria-selected="true" aria-controls="sq-element-panel-content" data-sq-element-tab="content">Content</button>
            <button id="sq-element-tab-style" type="button" role="tab" aria-selected="false" aria-controls="sq-element-panel-style" data-sq-element-tab="style">Style</button>
            <button id="sq-element-tab-motion" type="button" role="tab" aria-selected="false" aria-controls="sq-element-panel-motion" data-sq-element-tab="motion">Motion</button>
            <button id="sq-element-tab-layout" type="button" role="tab" aria-selected="false" aria-controls="sq-element-panel-layout" data-sq-element-tab="layout">Layout</button>
          </div>
          <div class="sq-button-brand-summary" data-sq-button-brand-summary hidden>
            <div class="sq-button-brand-summary-copy"><span class="sq-button-brand-swatches" aria-hidden="true"><i data-sq-selected-brand-swatch="bg"></i><i data-sq-selected-brand-swatch="fg"></i><i data-sq-selected-brand-swatch="border"></i></span><span><small>Connected brand style</small><b><span data-sq-selected-brand-role>Primary</span> button</b><em>Fill <span data-sq-selected-brand-value="bg">#F44B34</span> · Text <span data-sq-selected-brand-value="fg">#FFFFFF</span></em></span></div>
            <button type="button" data-sq-edit-button-brand>Edit in Branding <?= ez_admin_icon('chevron-right') ?></button>
          </div>
          <div class="sq-element-panel active" id="sq-element-panel-content" role="tabpanel" aria-labelledby="sq-element-tab-content" data-sq-element-panel="content">
          <div class="sq-element-text-editor" data-sq-element-text-controls hidden><label><span data-sq-element-text-label>Text content</span><textarea rows="4" data-sq-element-text></textarea></label><p class="sq-field-note">Changes appear on the canvas immediately.</p></div>
          <div class="sq-marquee-editor" data-sq-marquee-controls hidden><div class="sq-inspector-heading"><h3>Marquee movement</h3><span>Continuous</span></div><label><span>Movement</span><select data-sq-marquee-mode><option value="auto">Automatic</option><option value="scroll">Follow page scroll</option></select></label><label><span>Speed</span><input type="range" min="20" max="200" step="10" value="60" data-sq-marquee-speed><output data-sq-marquee-speed-output>60 px/s</output></label><p class="sq-field-note" data-sq-marquee-mode-note>Automatic movement loops continuously with no empty gap.</p></div>
          <div class="sq-review-editor" data-sq-review-controls hidden><div class="sq-inspector-heading"><h3>Review rating</h3><span>Visible stars</span></div><div class="sq-review-rating" role="group" aria-label="Review star rating"><button type="button" data-sq-review-rating="1" aria-label="1 star">1 ★</button><button type="button" data-sq-review-rating="2" aria-label="2 stars">2 ★</button><button type="button" data-sq-review-rating="3" aria-label="3 stars">3 ★</button><button type="button" data-sq-review-rating="4" aria-label="4 stars">4 ★</button><button type="button" data-sq-review-rating="5" aria-label="5 stars">5 ★</button></div><p class="sq-field-note">Choose the rating shown above this review.</p></div>
          <div class="sq-logo-editor" data-sq-logo-controls hidden><div class="sq-inspector-heading"><h3>Logo</h3><span>Header brand</span></div><div class="sq-image-source-row"><label class="sq-upload-image"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif,image/svg+xml" data-sq-logo-upload><?= ez_admin_icon('image') ?><span>Upload logo</span></label><button type="button" data-sq-logo-clear>Use text</button></div><label><span>Logo URL</span><input type="url" placeholder="https://…" data-sq-logo-src></label><label><span>Brand name fallback</span><input type="text" maxlength="80" data-sq-logo-text-input></label><label><span>Logo alt text</span><input type="text" maxlength="120" data-sq-logo-alt></label><label><span>Logo width</span><input type="range" min="40" max="280" value="140" data-sq-logo-width><output data-sq-logo-width-output>140px</output></label><p class="sq-field-note">PNG, SVG, WebP, and JPEG are supported. Text remains as an accessible fallback.</p></div>
          <div class="sq-image-editor" data-sq-image-controls hidden>
            <div class="sq-inspector-heading"><h3>Image</h3><span>Live preview</span></div>
            <div class="sq-image-source-row"><label class="sq-upload-image"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif" data-sq-image-upload><?= ez_admin_icon('image') ?><span>Replace image</span></label><button type="button" data-sq-image-reset>Reset effects</button></div>
            <label><span>Image URL</span><input type="url" placeholder="https://…" data-sq-image-src></label>
            <label><span>Alt text</span><input type="text" maxlength="180" placeholder="Describe this image" data-sq-image-alt></label>
            <div class="sq-element-style-row"><label><span>Fit</span><select data-sq-image-fit><option value="cover">Cover</option><option value="contain">Contain</option><option value="fill">Stretch</option></select></label><label><span>Position</span><select data-sq-image-position><option value="center">Center</option><option value="top">Top</option><option value="bottom">Bottom</option><option value="left">Left</option><option value="right">Right</option></select></label></div>
            <div class="sq-image-adjustments">
              <label><span>Blur</span><input type="range" min="0" max="24" step="1" value="0" data-sq-image-filter="blur"><output data-sq-image-output="blur">0px</output></label>
              <label><span>Brightness</span><input type="range" min="30" max="170" step="5" value="100" data-sq-image-filter="brightness"><output data-sq-image-output="brightness">100%</output></label>
              <label><span>Contrast</span><input type="range" min="30" max="170" step="5" value="100" data-sq-image-filter="contrast"><output data-sq-image-output="contrast">100%</output></label>
              <label><span>Saturation</span><input type="range" min="0" max="200" step="5" value="100" data-sq-image-filter="saturate"><output data-sq-image-output="saturate">100%</output></label>
              <label><span>Grayscale</span><input type="range" min="0" max="100" step="5" value="0" data-sq-image-filter="grayscale"><output data-sq-image-output="grayscale">0%</output></label>
              <label><span>Opacity</span><input type="range" min="10" max="100" step="5" value="100" data-sq-image-filter="opacity"><output data-sq-image-output="opacity">100%</output></label>
            </div>
          </div>
          <div class="sq-element-button-role" data-sq-element-button-controls hidden>
            <div class="sq-inspector-heading"><h3>Button action</h3><span>Click behavior</span></div>
            <label><span>Button label</span><input type="text" maxlength="80" data-sq-button-label></label>
            <label><span>Destination</span><select data-sq-button-link-type><option value="section">Page section</option><option value="url">Web address</option><option value="checkout">Checkout</option><option value="email">Email</option><option value="phone">Phone</option><option value="none">No action</option></select></label>
            <label data-sq-button-link-wrap><span data-sq-button-link-label>Section ID</span><input type="text" placeholder="products" data-sq-button-link></label>
            <label class="sq-new-tab"><input type="checkbox" data-sq-button-new-tab><span>Open in a new tab</span></label>
            <div class="sq-checkout-test" data-sq-checkout-test hidden><span><?= ez_admin_icon('shield') ?></span><div><b>Connected checkout handoff</b><small>Biteship rates → secure payment</small></div><button type="button" data-sq-test-checkout>Open checkout</button></div>
            <h3 class="sq-role-heading">Visual role</h3><div class="sq-role-choices"><button class="active button-primary" type="button" data-sq-role-choice="primary">Primary</button><button class="button-secondary" type="button" data-sq-role-choice="secondary">Secondary</button><button class="button-tertiary" type="button" data-sq-role-choice="tertiary">Tertiary</button></div><p class="sq-field-note">Roles stay synchronized with the global button system.</p>
          </div>
          <div class="sq-code-controls" data-sq-code-controls hidden><div class="sq-inspector-heading"><h3>Custom HTML, CSS &amp; JS</h3><span>Sandboxed</span></div><p class="sq-field-note">Code runs inside an isolated preview while editing and is included directly in exported HTML.</p><textarea rows="12" spellcheck="false" data-sq-code-input></textarea><button class="sq-replay-button" type="button" data-sq-run-code><?= ez_admin_icon('play') ?> Run code preview</button></div>
          <div class="sq-component-instance-controls" data-sq-component-instance-controls hidden><div class="sq-instance-badge"><?= ez_admin_icon('box') ?><span><small>Instance of</small><b data-sq-instance-name>Component</b></span></div><p class="sq-field-note">This instance stays connected to its main component. Editing the main component updates every instance.</p><button type="button" data-sq-edit-main-component>Edit main component</button><button type="button" data-sq-detach-instance>Detach instance</button></div>
          <p class="sq-element-panel-empty" data-sq-element-content-empty hidden>This element has no content fields. Use Style, Motion, or Layout to continue editing.</p>
          </div>
          <div class="sq-element-panel" id="sq-element-panel-style" role="tabpanel" aria-labelledby="sq-element-tab-style" data-sq-element-panel="style" hidden>
          <div class="sq-element-appearance">
            <section class="sq-style-card" aria-labelledby="sq-style-type-title" data-sq-typography-controls>
              <div class="sq-style-card-heading"><h3 id="sq-style-type-title">Typography</h3><span>Text</span></div>
              <div class="sq-style-two-column">
                <label><span>Font</span><select data-sq-element-font-family><option value="Poppins, sans-serif">Poppins</option><option value="Arial, Helvetica, sans-serif">Modern Sans</option><option value="Georgia, 'Times New Roman', serif">Editorial Serif</option><option value="'Times New Roman', Times, serif">Classic Serif</option><option value="ui-monospace, SFMono-Regular, Consolas, monospace">Mono</option></select></label>
                <label><span>Weight</span><select data-sq-element-font-weight><option value="400">Regular</option><option value="500">Medium</option><option value="600">Semibold</option><option value="700">Bold</option></select></label>
              </div>
              <label class="sq-style-range"><span>Font size</span><input type="range" min="8" max="160" step="1" value="32" data-sq-element-font-size><output data-sq-element-font-size-output>32px</output></label>
              <div class="sq-style-two-column sq-style-compact-ranges">
                <label class="sq-style-range"><span>Line height</span><input type="range" min="0.7" max="2.2" step="0.05" value="1.2" data-sq-element-line-height><output data-sq-element-line-height-output>1.2</output></label>
                <label class="sq-style-range"><span>Letter space</span><input type="range" min="-10" max="20" step="0.25" value="0" data-sq-element-letter-spacing><output data-sq-element-letter-spacing-output>0px</output></label>
              </div>
              <span class="sq-style-label">Alignment</span>
              <div class="sq-style-segmented" role="group" aria-label="Text alignment"><button type="button" data-sq-element-align="left">Left</button><button type="button" data-sq-element-align="center">Center</button><button type="button" data-sq-element-align="right">Right</button></div>
              <span class="sq-style-label">Letter case</span>
              <div class="sq-style-segmented" role="group" aria-label="Letter case"><button type="button" data-sq-element-transform="none">Normal</button><button type="button" data-sq-element-transform="uppercase">UPPER</button><button type="button" data-sq-element-transform="lowercase">lower</button></div>
            </section>
            <section class="sq-style-card" aria-labelledby="sq-style-colors-title">
              <div class="sq-style-card-heading"><h3 id="sq-style-colors-title">Colors</h3><span>Fill &amp; outline</span></div>
              <div class="sq-style-color-list">
                <div class="sq-style-color" data-sq-color-card="color"><input type="color" value="#24262b" aria-label="Choose text color" data-sq-element-color="color"><label><span>Text</span><input type="text" value="#24262B" maxlength="7" spellcheck="false" data-sq-element-color-hex="color"></label></div>
                <div class="sq-style-color" data-sq-color-card="backgroundColor"><input type="color" value="#ffffff" aria-label="Choose background color" data-sq-element-color="backgroundColor"><label><span>Background</span><input type="text" value="#FFFFFF" maxlength="7" spellcheck="false" data-sq-element-color-hex="backgroundColor"></label><button type="button" aria-label="Remove background color" title="No background" data-sq-element-color-clear="backgroundColor">×</button></div>
                <div class="sq-style-color" data-sq-color-card="borderColor"><input type="color" value="#e3e5e7" aria-label="Choose border color" data-sq-element-color="borderColor"><label><span>Border</span><input type="text" value="#E3E5E7" maxlength="7" spellcheck="false" data-sq-element-color-hex="borderColor"></label><button type="button" aria-label="Remove border color" title="No border color" data-sq-element-color-clear="borderColor">×</button></div>
              </div>
            </section>
            <section class="sq-style-card" aria-labelledby="sq-style-surface-title">
              <div class="sq-style-card-heading"><h3 id="sq-style-surface-title">Surface &amp; border</h3></div>
              <span class="sq-style-label">Surface</span>
              <div class="sq-surface-choices" role="group" aria-label="Surface treatment"><button type="button" data-sq-element-surface="none"><i></i><span>None</span></button><button type="button" data-sq-element-surface="soft"><i></i><span>Soft</span></button><button type="button" data-sq-element-surface="card"><i></i><span>Card</span></button><button type="button" data-sq-element-surface="outline"><i></i><span>Outline</span></button><button type="button" data-sq-element-surface="glass"><i></i><span>Glass</span></button></div>
              <div class="sq-style-two-column">
                <label class="sq-style-range"><span>Border width</span><input type="range" min="0" max="12" step="1" value="0" data-sq-element-border-width><output data-sq-element-border-width-output>0px</output></label>
                <label><span>Border style</span><select data-sq-element-border-style><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option><option value="double">Double</option></select></label>
              </div>
            </section>
            <section class="sq-style-card" aria-labelledby="sq-style-corners-title">
              <div class="sq-style-card-heading"><h3 id="sq-style-corners-title">Corners</h3></div>
              <div class="sq-radius-presets" role="group" aria-label="Corner presets"><button type="button" data-sq-radius-choice="0"><i></i><span>Square</span></button><button type="button" data-sq-radius-choice="8"><i></i><span>Soft</span></button><button type="button" data-sq-radius-choice="20"><i></i><span>Round</span></button><button type="button" data-sq-radius-choice="999"><i></i><span>Pill</span></button></div>
              <div class="sq-radius-control"><label class="sq-style-range"><span>Radius</span><input type="range" min="0" max="64" value="0" data-sq-element-radius><output data-sq-element-radius-output>0px</output></label><label class="sq-radius-number"><span>Exact</span><input type="number" min="0" max="999" value="0" data-sq-element-radius-number><b>px</b></label></div>
            </section>
            <button class="sq-reset-style" type="button" data-sq-element-style-reset>Reset style overrides</button>
          </div>
          </div>
          <div class="sq-element-panel" id="sq-element-panel-motion" role="tabpanel" aria-labelledby="sq-element-tab-motion" data-sq-element-panel="motion" hidden>
          <div class="sq-image-scroll-editor" data-sq-image-scroll-controls hidden><div class="sq-inspector-heading"><h3>Image scroll</h3><span>Runs in Preview</span></div><label><span>Scroll effect</span><select data-sq-image-scroll-effect><option value="none">None</option><option value="parallax">Parallax</option><option value="parallax-reverse">Reverse parallax</option><option value="zoom">Scroll zoom</option></select></label><label><span>Strength</span><input type="range" min="0" max="100" step="1" value="50" data-sq-image-scroll-strength><output data-sq-image-scroll-strength-output>50%</output></label><label class="sq-image-damping-toggle"><input type="checkbox" data-sq-image-scroll-damping checked><i aria-hidden="true"></i><span><b>Damping</b><small>Adds smooth velocity and catch-up.</small></span></label><p>For Parallax, 0% follows the page normally and 100% pins the image to the viewport. Reverse and zoom range from subtle to strongest.</p></div>
          <div class="sq-element-motion"><div class="sq-inspector-heading"><h3>Motion</h3><span>Runs in Preview</span></div><label><span>Entrance effect</span><select data-sq-element-animation-control><option value="none">None</option><option value="fade">Fade in</option><option value="rise">Rise and fade</option><option value="slide-left">Slide from left</option><option value="slide-right">Slide from right</option><option value="scale">Soft scale</option><option value="blur">Blur reveal</option><option value="flip">Perspective flip</option></select></label><div class="sq-inline-controls"><label><span>Duration</span><input type="range" min="200" max="1800" step="100" value="700" data-sq-element-duration><output data-sq-element-duration-output>700ms</output></label><label><span>Delay</span><input type="range" min="0" max="1200" step="100" value="0" data-sq-element-delay><output data-sq-element-delay-output>0ms</output></label></div><span class="sq-control-label">Hover effect</span><div class="sq-hover-options"><button type="button" data-sq-hover-choice="none"><span>None</span></button><button type="button" data-sq-hover-choice="lift"><span>Lift</span></button><button type="button" data-sq-hover-choice="scale"><span>Scale</span></button><button type="button" data-sq-hover-choice="glow"><span>Glow</span></button><button type="button" data-sq-hover-choice="tilt"><span>Tilt</span></button><button type="button" data-sq-hover-choice="image-zoom"><span>Image zoom</span></button></div><button class="sq-replay-button" type="button" data-sq-element-replay><?= ez_admin_icon('play') ?> Preview page</button></div>
          </div>
          <div class="sq-element-panel" id="sq-element-panel-layout" role="tabpanel" aria-labelledby="sq-element-tab-layout" data-sq-element-panel="layout" hidden>
          <div class="sq-product-layout-controls" data-sq-product-layout-controls hidden>
            <div class="sq-inspector-heading"><h3>Product grid layout</h3><span data-sq-product-layout-device>Desktop</span></div>
            <label><span>Cards per row</span><select data-sq-product-columns><option value="auto">Auto fit while resizing</option><option value="1">1 card</option><option value="2">2 cards</option><option value="3">3 cards</option><option value="4">4 cards</option></select></label>
            <label><span>Card size</span><select data-sq-product-density><option value="compact">Compact</option><option value="balanced">Balanced</option><option value="showcase">Large showcase</option></select></label>
            <p class="sq-field-note">Drag product cards to reorder them. Auto fit reflows cards as you resize this element instead of clipping them.</p>
          </div>
          <div class="sq-element-inset-controls"><div class="sq-inspector-heading"><h3>Element spacing</h3><span data-sq-element-inset-device>Desktop</span></div><span class="sq-style-label">Position in section</span><div class="sq-style-segmented" role="group" aria-label="Element position"><button type="button" data-sq-element-position-choice="left">Left</button><button type="button" data-sq-element-position-choice="center">Center</button><button type="button" data-sq-element-position-choice="right">Right</button></div><label class="sq-element-width-control"><span>Element width</span><input type="range" min="1" max="12" step="1" value="6" data-sq-element-width-quick><output data-sq-element-width-quick-output>6 columns</output></label><div class="sq-element-inset-heading"><span>Inner inset</span><label><input type="checkbox" data-sq-link-element-inset checked> Link sides</label></div><div class="sq-element-inset-grid"><label><span>Top</span><input type="number" min="0" max="240" value="0" data-sq-element-inset="top"></label><label><span>Right</span><input type="number" min="0" max="240" value="0" data-sq-element-inset="right"></label><label><span>Bottom</span><input type="number" min="0" max="240" value="0" data-sq-element-inset="bottom"></label><label><span>Left</span><input type="number" min="0" max="240" value="0" data-sq-element-inset="left"></label></div><button class="sq-reset-element-inset" type="button" data-sq-element-inset-reset>Use element default</button><p class="sq-field-note">Elements on the same grid column align exactly when their left inset matches.</p></div>
          <details class="sq-advanced-layout"><summary>Advanced position &amp; size <span>Responsive grid</span></summary><div><label data-sq-hero-preset-wrap><span>Section layout preset</span><select data-sq-layout-preset><option value="custom">Custom arrangement</option><option value="split">Split</option><option value="text-only">Text only / remove images</option><option value="single-image">Text + single image</option><option value="image-only">Image only</option><option value="stacked">Stacked</option></select></label><div class="sq-element-position"><label><span>Column</span><input type="number" min="1" max="24" data-sq-element-x></label><label><span>Row</span><input type="number" min="1" max="80" data-sq-element-y></label><label><span>Width</span><input type="number" min="1" max="24" data-sq-element-w></label><label><span>Height</span><input type="number" min="1" max="80" data-sq-element-h></label></div><p class="sq-field-note">Drag on the canvas for normal editing. Exact values are saved independently for desktop, tablet, and mobile.</p></div></details>
          </div>
          <div class="sq-element-actions"><button type="button" data-sq-element-duplicate><?= ez_admin_icon('layers') ?> Duplicate</button><button type="button" data-sq-element-hide><?= ez_admin_icon('eye') ?> Hide</button><button class="danger" type="button" data-sq-element-delete><?= ez_admin_icon('x') ?> Delete</button></div>
        </section>
        <section data-sq-section-controls><div class="sq-inspector-heading"><h3>Responsive spacing</h3><span data-sq-spacing-device>Desktop</span></div><label class="sq-link-spacing"><input type="checkbox" data-sq-link-spacing><span>Link all sides</span></label><div class="sq-spacing-grid"><label><span>Top</span><input type="range" min="0" max="160" value="8" data-sq-spacing="top"><output data-sq-spacing-output="top">8</output></label><label><span>Right</span><input type="range" min="0" max="160" value="16" data-sq-spacing="right"><output data-sq-spacing-output="right">16</output></label><label><span>Bottom</span><input type="range" min="0" max="160" value="8" data-sq-spacing="bottom"><output data-sq-spacing-output="bottom">8</output></label><label><span>Left</span><input type="range" min="0" max="160" value="16" data-sq-spacing="left"><output data-sq-spacing-output="left">16</output></label></div><p class="sq-field-note">Values are saved independently for desktop, tablet, and mobile.</p></section>
        <section data-sq-section-controls><h3>Entrance animation</h3><label><span>Effect</span><select data-sq-animation><option value="none">None</option><option value="fade">Fade in</option><option value="slide-up">Slide up</option><option value="slide-left">Slide from left</option><option value="scale">Soft scale</option></select></label><div class="sq-inline-controls"><label><span>Duration</span><input type="range" min="200" max="1600" step="100" value="600" data-sq-duration><output data-sq-duration-output>600ms</output></label><label><span>Delay</span><input type="range" min="0" max="1000" step="100" value="0" data-sq-delay><output data-sq-delay-output>0ms</output></label></div><label><span>Easing</span><select data-sq-easing><option value="ease-out">Smooth out</option><option value="ease-in-out">Smooth both</option><option value="cubic-bezier(.2,.8,.2,1)">Expressive</option><option value="linear">Linear</option></select></label><button class="sq-replay-button" type="button" data-sq-replay><?= ez_admin_icon('play') ?> Preview page</button></section>
        <section data-sq-section-controls><h3>Section layout</h3><label><span>Content width</span><input type="range" min="720" max="1440" step="40" value="1200" data-sq-content-width><output data-sq-width-output>1200px</output></label><label><span>Background</span><select data-sq-background><option value="light">Warm white</option><option value="white">White</option><option value="dark">Charcoal</option><option value="accent">Brand accent</option></select></label></section>
      </div>
      <footer data-sq-section-actions><button type="button" data-sq-duplicate><?= ez_admin_icon('layers') ?> Duplicate</button><button type="button" data-sq-visibility><?= ez_admin_icon('eye') ?> Hide</button><button class="danger" type="button" data-sq-delete aria-label="Delete selected section"><?= ez_admin_icon('x') ?> Delete section</button></footer>
    </aside>
  </div>
</section>

<dialog class="sq-live-preview-dialog" id="landing-preview-dialog">
  <div class="sq-live-preview-shell"><header><div><small>Live page preview</small><h2 data-sq-preview-title>Landing page</h2></div><nav aria-label="Preview size"><button class="active" type="button" data-sq-preview-device="desktop"><?= ez_admin_icon('monitor') ?><span>Desktop · 1440</span></button><button type="button" data-sq-preview-device="tablet"><?= ez_admin_icon('layout') ?><span>Tablet · 768</span></button><button type="button" data-sq-preview-device="mobile"><?= ez_admin_icon('smartphone') ?><span>Mobile · 390</span></button></nav><div><button type="button" data-sq-preview-new-tab><?= ez_admin_icon('globe') ?><span>Open tab</span></button><button type="button" data-sq-preview-close aria-label="Close preview"><?= ez_admin_icon('x') ?></button></div></header><main data-sq-live-preview-stage data-preview-device="desktop"><div class="sq-live-preview-frame"><iframe title="Landing page production preview" sandbox="allow-scripts allow-forms allow-popups allow-top-navigation-by-user-activation" data-sq-live-preview-frame></iframe></div></main></div>
</dialog>

<dialog class="sq-export-dialog" id="html-export-dialog">
  <form method="dialog"><header><span><?= ez_admin_icon('code') ?></span><div><small>Production output</small><h2>Generated landing-page HTML</h2><p>Responsive structure, selected products, spacing, animations, SEO metadata, and checkout hooks are included.</p></div><button value="close" aria-label="Close HTML export"><?= ez_admin_icon('x') ?></button></header><div class="sq-export-summary"><span><?= ez_admin_icon('check-circle') ?> Semantic HTML</span><span><?= ez_admin_icon('check-circle') ?> Responsive CSS</span><span><?= ez_admin_icon('check-circle') ?> Animation CSS</span><span><?= ez_admin_icon('check-circle') ?> Commerce hooks</span></div><textarea readonly spellcheck="false" data-sq-html-output></textarea><footer><small data-sq-html-size>Ready to generate</small><button type="button" data-sq-copy-html>Copy HTML</button><button class="primary" type="button" data-sq-download-html><?= ez_admin_icon('download') ?> Download .html</button></footer></form>
</dialog>

<dialog class="sq-component-dialog" data-sq-component-dialog>
  <form method="dialog" data-sq-component-form>
    <header><span><?= ez_admin_icon('code') ?></span><div><small data-sq-component-dialog-context>Create component</small><h2 data-sq-component-dialog-title>New main component</h2><p>Write HTML, CSS, and JavaScript in one sandboxed component.</p></div><button type="button" data-sq-component-close aria-label="Close component editor"><?= ez_admin_icon('x') ?></button></header>
    <section><div class="sq-component-meta"><label><span>Name</span><input name="component_name" maxlength="80" required placeholder="Announcement card"></label><label><span>Description</span><input name="component_description" maxlength="180" placeholder="Optional usage note"></label></div><label class="sq-component-code-field"><span>Component code</span><textarea name="component_code" rows="18" required spellcheck="false"></textarea></label><div class="sq-component-budget"><span><b data-sq-component-size>0 KB</b> of 200 KB</span><span><b data-sq-component-total>0</b> of 20 components</span></div><p class="sq-component-error" data-sq-component-error hidden></p></section>
    <footer><button type="button" data-sq-component-delete hidden>Delete main component</button><span></span><button type="button" data-sq-component-close>Cancel</button><button class="primary" type="submit" data-sq-component-save>Save component</button></footer>
  </form>
</dialog>

<dialog class="page-creator-dialog" id="page-creator-dialog"><form method="dialog" data-page-creator-form>
  <header><span><?= ez_admin_icon('layout') ?></span><div><small>Create a landing page</small><h2>Start with at least one product.</h2><p>Choose from the real products already saved in your Ezkart catalog.</p></div><button type="button" data-creator-close aria-label="Close"><?= ez_admin_icon('x') ?></button></header>
  <section>
    <label><span>Page name</span><input name="page_name" required maxlength="60" placeholder="Example: Ramadan Collection"></label>
    <fieldset data-creator-products><legend>Starting products</legend><p class="creator-products-empty" data-creator-products-empty>No products are available yet. <a href="?page=products">Create a product first</a>.</p></fieldset>
    <label><span>Free Ezkart URL</span><div class="slug-field"><input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="ramadan-collection"><em>.ezkart.site</em></div></label>
  </section>
  <footer><button type="button" data-creator-close>Cancel</button><button class="primary" value="default" data-create-page>Build full page</button></footer>
</form></dialog>
