<?php
declare(strict_types=1);
?>
<section class="sq-studio" id="visual-builder" aria-label="Landing page builder">
  <header class="sq-commandbar">
    <div class="sq-page-identity">
      <a href="?page=sites" aria-label="Return to landing pages"><?= ez_admin_icon('chevron-left') ?></a>
      <button type="button" data-sq-open-panel="pages"><span><small>Landing page</small><b data-current-site-name>Landing page</b></span><?= ez_admin_icon('chevron-down') ?></button>
      <span class="sq-live-state"><i></i> Draft</span>
    </div>
    <div class="sq-history-tools" aria-label="Editing history">
      <button type="button" data-sq-undo aria-label="Undo" disabled><?= ez_admin_icon('undo') ?></button>
      <button type="button" data-sq-redo aria-label="Redo" disabled><?= ez_admin_icon('redo') ?></button>
      <span data-sq-save-state>All changes saved</span>
    </div>
    <div class="sq-device-tools" aria-label="Responsive preview">
      <button class="active" type="button" data-sq-device="desktop" aria-label="Desktop preview"><?= ez_admin_icon('monitor') ?></button>
      <button type="button" data-sq-device="tablet" aria-label="Tablet preview"><?= ez_admin_icon('layout') ?></button>
      <button type="button" data-sq-device="mobile" aria-label="Mobile preview"><?= ez_admin_icon('smartphone') ?></button>
      <button type="button" data-sq-fit aria-label="Fit canvas to window"><?= ez_admin_icon('refund') ?></button>
    </div>
    <div class="sq-command-actions">
      <button type="button" data-sq-preview><?= ez_admin_icon('eye') ?><span>Preview</span></button>
      <button type="button" data-sq-export><?= ez_admin_icon('code') ?><span>Export HTML</span></button>
      <button class="primary" type="button" data-sq-publish>Publish</button>
    </div>
  </header>

  <div class="sq-editor-grid">
    <aside class="sq-builder-sidebar">
      <nav class="sq-tool-rail" aria-label="Builder tools">
        <button class="active" type="button" data-sq-tab="layers" aria-label="Page layers"><?= ez_admin_icon('layers') ?><span>Layers</span></button>
        <button type="button" data-sq-tab="templates" aria-label="Website templates"><?= ez_admin_icon('layout') ?><span>Templates</span></button>
        <button type="button" data-sq-tab="add" aria-label="Add section"><?= ez_admin_icon('plus') ?><span>Add</span></button>
        <button type="button" data-sq-tab="products" aria-label="Products"><?= ez_admin_icon('box') ?><span>Products</span><i data-sq-product-count>0</i></button>
        <button type="button" data-sq-tab="design" aria-label="Site design"><?= ez_admin_icon('palette') ?><span>Design</span></button>
        <button type="button" data-sq-tab="pages" aria-label="Pages and domains"><?= ez_admin_icon('globe') ?><span>Pages</span></button>
      </nav>

      <div class="sq-tool-panels">
        <section class="sq-tool-panel active" data-sq-panel="layers">
          <header><div><small>Page structure</small><h2>Layers</h2></div><button type="button" data-sq-open-panel="add" aria-label="Add section"><?= ez_admin_icon('plus') ?></button></header>
          <p class="sq-panel-intro">Drag sections to reorder them. Click anything to edit it.</p>
          <div class="sq-layer-list" data-sq-layer-list aria-label="Sections and elements"></div>
          <footer><span><?= ez_admin_icon('shield') ?> Autosaved and versioned</span></footer>
        </section>

        <section class="sq-tool-panel sq-template-panel" data-sq-panel="templates">
          <header><div><small>Complete websites</small><h2>Template gallery</h2></div><span class="sq-template-total">13 designs</span></header>
          <p class="sq-panel-intro">Start with a complete branded page. Every section, image, color, button, and animation stays editable.</p>
          <label class="sq-panel-search"><?= ez_admin_icon('search') ?><input type="search" placeholder="Search style or industry" data-sq-template-search></label>
          <div class="sq-template-filters" aria-label="Template categories"><button class="active" type="button" data-template-filter="all">All</button><button type="button" data-template-filter="shop">Shop</button><button type="button" data-template-filter="services">Services</button><button type="button" data-template-filter="editorial">Editorial</button></div>
          <div class="sq-template-grid">
            <button type="button" data-sq-template="gallery" data-template-category="shop editorial" data-search="gallery catalog modern minimal multi product home retail general"><span style="--template-image:url('/landing-templates/gallery/assets/collection-hero.png')"><i>Catalog</i><em>New template</em></span><b>Gallery</b><small>Modern multi-product catalog</small></button>
            <button type="button" data-sq-template="sora" data-template-category="shop editorial" data-search="fashion modest warm editorial sora"><span style="--template-image:url('assets/templates/fashion-terracotta.webp')"><i>Fashion</i><em>Live motion</em></span><b>Sora Modest</b><small>Warm editorial fashion</small></button>
            <button type="button" data-sq-template="embun" data-template-category="shop" data-search="beauty skincare botanical green embun"><span style="--template-image:url('assets/templates/skincare-sage.webp')"><i>Beauty</i><em>Live motion</em></span><b>Embun Botanics</b><small>Botanical product launch</small></button>
            <button type="button" data-sq-template="pulih" data-template-category="services editorial" data-search="wellness yoga studio calm bali pulih"><span style="--template-image:url('assets/templates/wellness-bali.webp')"><i>Wellness</i><em>Live motion</em></span><b>Ruang Pulih</b><small>Wellness &amp; membership</small></button>
            <button type="button" data-sq-template="tanah" data-template-category="shop editorial" data-search="homeware ceramics interior clay tanah"><span style="--template-image:url('assets/templates/homeware-clay.webp')"><i>Home</i><em>Live motion</em></span><b>Tanah Studio</b><small>Artisanal homeware</small></button>
            <button type="button" data-sq-template="senja" data-template-category="shop" data-search="coffee cafe dark modern senja"><span style="--template-image:url('assets/products/kopi-susu.webp')"><i>Coffee</i><em>Live motion</em></span><b>Kopi Senja</b><small>Bold coffee commerce</small></button>
            <button type="button" data-sq-template="timur" data-template-category="shop" data-search="food sambal spicy red launch timur"><span style="--template-image:url('assets/products/sambal-roa.webp')"><i>Food</i><em>Live motion</em></span><b>Dapur Timur</b><small>High-energy food launch</small></button>
            <button type="button" data-sq-template="pagi" data-template-category="shop" data-search="food granola breakfast bright pagi"><span style="--template-image:url('assets/products/granola.webp')"><i>Food</i><em>Live motion</em></span><b>Meja Pagi</b><small>Bright everyday goods</small></button>
            <button type="button" data-sq-template="mono" data-template-category="shop editorial" data-search="minimal monochrome catalog mono"><span class="template-mono"><i>Minimal</i><em>Live motion</em></span><b>Mono Catalog</b><small>Quiet product grid</small></button>
            <button type="button" data-sq-template="neon" data-template-category="shop editorial" data-search="streetwear neon launch drop bold"><span class="template-neon"><i>Launch</i><em>Live motion</em></span><b>Neon Drop</b><small>High-impact campaign</small></button>
            <button type="button" data-sq-template="kisah" data-template-category="services editorial" data-search="portfolio photographer creative kisah"><span style="--template-image:url('assets/templates/fashion-terracotta.webp')"><i>Portfolio</i><em>Live motion</em></span><b>Kisah Visual</b><small>Creative portfolio shop</small></button>
            <button type="button" data-sq-template="kelas" data-template-category="services" data-search="course creator class digital kelas"><span style="--template-image:url('assets/templates/wellness-bali.webp')"><i>Creator</i><em>Live motion</em></span><b>Kelas Bertumbuh</b><small>Course &amp; community</small></button>
            <button type="button" data-sq-template="kanvas" data-template-category="editorial" data-search="image first campaign minimal kanvas"><span style="--template-image:url('assets/templates/skincare-sage.webp')"><i>Image-led</i><em>Live motion</em></span><b>Kanvas</b><small>Full-bleed storytelling</small></button>
          </div>
        </section>

        <section class="sq-tool-panel" data-sq-panel="add">
          <header><div><small>Section library</small><h2>Add content</h2></div></header>
          <label class="sq-panel-search"><?= ez_admin_icon('search') ?><input type="search" placeholder="Search elements or sections" data-sq-block-search></label>
          <div class="sq-block-group"><h3>Free-position elements</h3><div class="sq-block-grid sq-element-library">
            <button type="button" data-sq-add-element="heading" data-search="heading title text"><?= ez_admin_icon('message') ?><b>Heading</b><small>Independent headline</small></button>
            <button type="button" data-sq-add-element="text" data-search="paragraph text copy"><?= ez_admin_icon('message') ?><b>Text</b><small>Body copy block</small></button>
            <button type="button" data-sq-add-element="button" data-search="button call action"><?= ez_admin_icon('play') ?><b>Button</b><small>Linked action</small></button>
            <button type="button" data-sq-add-element="image" data-search="image photo picture"><?= ez_admin_icon('image') ?><b>Image</b><small>Single movable image</small></button>
            <button type="button" data-sq-add-element="divider" data-search="divider line separator"><?= ez_admin_icon('layers') ?><b>Divider</b><small>Visual separator</small></button>
            <button type="button" data-sq-add-element="form" data-search="form email newsletter lead"><?= ez_admin_icon('mail') ?><b>Form</b><small>Email capture</small></button>
            <button type="button" data-sq-add-element="html" data-search="html css javascript code embed custom"><?= ez_admin_icon('code') ?><b>HTML / code</b><small>Sandboxed custom code</small></button>
          </div><p class="sq-library-note">Add to the selected section, then move, resize, duplicate, hide, or delete it independently.</p></div>
          <div class="sq-block-group"><h3>Commerce</h3><div class="sq-block-grid">
            <button type="button" data-sq-add-block="products" data-search="products shop collection"><?= ez_admin_icon('box') ?><b>Products</b><small>Multi-product grid</small></button>
            <button type="button" data-sq-add-block="checkout" data-search="checkout payment midtrans"><?= ez_admin_icon('credit-card') ?><b>Checkout</b><small>Secure cart CTA</small></button>
          </div></div>
          <div class="sq-block-group"><h3>Image-led</h3><div class="sq-block-grid">
            <button type="button" data-sq-add-block="full-image" data-search="image photo full bleed"><?= ez_admin_icon('image') ?><b>Full image</b><small>No text required</small></button>
            <button type="button" data-sq-add-block="gallery" data-search="gallery images photos"><?= ez_admin_icon('layout') ?><b>Gallery</b><small>Editorial mosaic</small></button>
            <button type="button" data-sq-add-block="blank" data-search="blank empty canvas custom"><?= ez_admin_icon('plus') ?><b>Blank canvas</b><small>Build from nothing</small></button>
          </div></div>
          <div class="sq-block-group"><h3>Story &amp; trust</h3><div class="sq-block-grid">
            <button type="button" data-sq-add-block="text" data-search="text story copy"><?= ez_admin_icon('message') ?><b>Text</b><small>Headline and body</small></button>
            <button type="button" data-sq-add-block="testimonials" data-search="reviews testimonials trust"><?= ez_admin_icon('star') ?><b>Reviews</b><small>Social proof</small></button>
            <button type="button" data-sq-add-block="faq" data-search="faq questions"><?= ez_admin_icon('help') ?><b>FAQ</b><small>Expandable answers</small></button>
            <button type="button" data-sq-add-block="spacer" data-search="space spacer gap"><?= ez_admin_icon('layers') ?><b>Spacer</b><small>Responsive breathing room</small></button>
          </div></div>
        </section>

        <section class="sq-tool-panel" data-sq-panel="products">
          <header><div><small>Commerce source</small><h2>Products</h2></div><a href="?page=products">Manage</a></header>
          <p class="sq-panel-intro">Use one product or the whole catalog. Ezkart keeps price, stock, checkout items, and shipping weights synchronized.</p>
          <div class="sq-product-picker">
            <p class="sq-products-empty" data-sq-products-empty>No catalog products are available. <a href="?page=products">Create a product</a> before building a landing page.</p>
          </div>
          <div class="sq-product-rule"><span><?= ez_admin_icon('check-circle') ?></span><p><b>At least one product</b><small>A landing page always needs something customers can purchase.</small></p></div>
        </section>

        <section class="sq-tool-panel" data-sq-panel="design">
          <header><div><small>Global styles</small><h2>Site design</h2></div></header>
          <div class="sq-control-section"><h3>Color theme</h3><div class="sq-theme-grid"><button class="active coral" type="button" data-sq-theme="theme-coral" aria-label="Coral theme"></button><button class="forest" type="button" data-sq-theme="theme-forest" aria-label="Forest theme"></button><button class="indigo" type="button" data-sq-theme="theme-indigo" aria-label="Indigo theme"></button><button class="charcoal" type="button" data-sq-theme="theme-charcoal" aria-label="Charcoal theme"></button></div><div class="sq-brand-colors"><label><span>Accent</span><input type="color" value="#f44b34" data-sq-brand-color="accent"></label><label><span>Page</span><input type="color" value="#fffbf7" data-sq-brand-color="page"></label><label><span>Text</span><input type="color" value="#24262b" data-sq-brand-color="ink"></label><label><span>Surface</span><input type="color" value="#ffffff" data-sq-brand-color="surface"></label></div></div>
          <div class="sq-control-section sq-button-system"><div class="sq-inspector-heading"><h3>Button system</h3><span>3 reusable roles</span></div><label><span>Editing role</span><select data-sq-button-style-role><option value="primary">Primary</option><option value="secondary">Secondary</option><option value="tertiary">Tertiary</option></select></label><div class="sq-button-color-row"><label><span>Fill</span><input type="color" value="#f44b34" data-sq-button-color="bg"></label><label><span>Text</span><input type="color" value="#ffffff" data-sq-button-color="fg"></label><label><span>Border</span><input type="color" value="#f44b34" data-sq-button-color="border"></label></div><label><span>Treatment</span><select data-sq-button-treatment><option value="solid">Solid</option><option value="outline">Outline</option><option value="soft">Soft</option><option value="text">Text only</option></select></label><label><span>Corner radius</span><input type="range" min="0" max="40" value="10" data-sq-button-radius><output data-sq-button-radius-output>10px</output></label><button class="sq-button-live-preview button-primary" type="button" data-sq-button-preview><span>Hover button preview</span></button></div>
          <div class="sq-control-section"><label><span>Corner style</span><select data-sq-radius><option value="radius-soft">Soft · 16px</option><option value="radius-round">Rounded · 28px</option><option value="radius-square">Square · 4px</option></select></label><label><span>Page layout</span><select data-sq-layout><option value="layout-rich">Balanced commerce</option><option value="layout-editorial">Editorial images</option><option value="layout-image-only">Image-first / no default copy</option></select></label></div>
          <div class="sq-control-section"><h3>Typography</h3><div class="sq-font-card"><span>Aa</span><div><b>Poppins</b><small>Headings and body · 4 weights</small></div></div><label><span>Base size</span><input type="range" min="13" max="20" value="16" data-sq-font-size><output data-sq-font-output>16px</output></label></div>
        </section>

        <section class="sq-tool-panel" data-sq-panel="pages">
          <header><div><small>Website</small><h2>Pages &amp; hosting</h2></div><button type="button" data-open-page-creator aria-label="New landing page"><?= ez_admin_icon('plus') ?></button></header>
          <div class="sq-page-list">
            <template data-sq-site-template><button type="button" data-sq-site><span><?= ez_admin_icon('layout') ?></span><div><b>Landing page</b><small>page.ezkart.site</small></div><em class="draft">Draft</em></button></template>
          </div>
          <div class="sq-host-card"><span><?= ez_admin_icon('shield') ?></span><div><b>Managed hosting</b><small>Global CDN · 99.99% uptime</small></div><em>Active</em></div>
          <button class="sq-wide-button" type="button" data-toast="Domain manager opened">Manage domains &amp; SEO</button>
        </section>
      </div>
    </aside>

    <main class="sq-canvas-stage">
      <div class="sq-canvas-meta"><span><?= ez_admin_icon('shield') ?><b data-current-site-url>ezkart.site</b></span><div><button type="button" data-sq-zoom-out aria-label="Zoom out">−</button><output data-sq-zoom>80%</output><button type="button" data-sq-zoom-in aria-label="Zoom in">+</button></div></div>
      <div class="sq-canvas-scroll">
        <div class="sq-device-frame" data-sq-device-frame>
          <article class="sq-page-preview theme-coral radius-soft layout-rich" data-sq-preview-root>
            <section class="sq-page-block sq-announcement selected" draggable="true" data-sq-block data-sq-fluid data-sq-rows="2" data-section-id="announcement"><button class="sq-block-handle" type="button" aria-label="Drag announcement section"><?= ez_admin_icon('grip') ?></button><p data-sq-element data-sq-element-type="text" data-layout-desktop="1,1,12,2" data-layout-tablet="1,1,12,2" data-layout-mobile="1,1,12,2">Secure checkout for every product on this page</p></section>
            <nav class="sq-page-block sq-store-nav" draggable="true" data-sq-block data-sq-fluid data-sq-rows="2" data-section-id="navigation"><button class="sq-block-handle" type="button" aria-label="Drag navigation section"><?= ez_admin_icon('grip') ?></button><div class="sq-site-logo" data-sq-element data-sq-element-type="logo" data-layout-desktop="1,1,4,2" data-layout-tablet="1,1,5,2" data-layout-mobile="1,1,6,2"><img data-sq-logo-image alt="" hidden><b data-sq-logo-text>Morning Ritual</b></div><div data-sq-element data-sq-element-type="navigation" data-layout-desktop="7,1,6,2" data-layout-tablet="6,1,7,2" data-layout-mobile="7,1,6,2"><a href="#products">Shop</a><a href="#story">Our story</a><a href="#shipping" data-physical-only>Delivery</a><button type="button">Buy now</button></div></nav>
            <section class="sq-page-block sq-hero sq-hero-elements" draggable="true" data-sq-block data-sq-fluid data-sq-rows="15" data-section-id="hero"><button class="sq-block-handle" type="button" aria-label="Drag hero section"><?= ez_admin_icon('grip') ?></button><span class="sq-hero-kicker" data-sq-element data-sq-element-type="eyebrow" data-layout-desktop="1,3,6,1" data-layout-tablet="1,1,12,1" data-layout-mobile="1,1,12,1">Made with care · ready when you are</span><h1 class="sq-hero-heading" data-sq-element data-sq-element-type="heading" data-sq-content="headline" data-layout-desktop="1,4,6,5" data-layout-tablet="1,2,12,4" data-layout-mobile="1,2,12,4">Small-batch favorites for a better everyday ritual.</h1><p class="sq-hero-description" data-sq-element data-sq-element-type="text" data-sq-content="description" data-layout-desktop="1,9,6,3" data-layout-tablet="1,6,12,2" data-layout-mobile="1,6,12,3">Discover thoughtful products and a secure checkout with fulfillment matched to what you buy.</p><button class="sq-hero-action button-primary" type="button" data-sq-element data-sq-element-type="button" data-sq-button-role="primary" data-sq-link-type="section" data-sq-link="products" data-sq-new-tab="false" data-sq-content="cta" data-layout-desktop="1,12,3,2" data-layout-tablet="1,8,5,2" data-layout-mobile="1,9,7,2">Shop the collection</button><small class="sq-hero-trust" data-sq-element data-sq-element-type="trust-note" data-layout-desktop="4,12,3,2" data-layout-tablet="6,8,7,2" data-layout-mobile="1,11,12,1"><?= ez_admin_icon('shield') ?> Secure checkout powered by Ezkart</small><div class="sq-hero-collage" data-sq-element data-sq-element-type="collage" data-layout-desktop="7,2,6,12" data-layout-tablet="1,10,12,7" data-layout-mobile="1,12,12,7" data-sq-image-list><span class="large" draggable="true" tabindex="0" data-sq-image-item data-product-visual="granola" aria-label="Granola image — drag to rearrange"><?= ez_admin_product_art('Granola Madu Nusantara') ?></span><span draggable="true" tabindex="0" data-sq-image-item data-product-visual="coffee" aria-label="Kopi Susu image — drag to rearrange"><?= ez_admin_product_art('Kopi Susu Concentrate') ?></span><span draggable="true" tabindex="0" data-sq-image-item data-product-visual="sambal" aria-label="Sambal Roa image — drag to rearrange"><?= ez_admin_product_art('Sambal Roa Signature') ?></span></div></section>
            <section class="sq-page-block sq-product-section" id="products" draggable="true" data-sq-block data-sq-fluid data-sq-rows="21" data-section-id="products"><button class="sq-block-handle" type="button" aria-label="Drag product section"><?= ez_admin_icon('grip') ?></button><header data-sq-element data-sq-element-type="collection-heading" data-layout-desktop="1,1,12,7" data-layout-tablet="1,1,12,7" data-layout-mobile="1,1,12,7"><div><span>Shop the collection</span><h2>Pick one favorite—or build your whole basket.</h2></div><p>Every item stays synchronized with availability, secure payment, and the right fulfillment flow.</p></header><div class="sq-product-grid" data-sq-element data-sq-element-type="product-grid" data-layout-desktop="1,8,12,14" data-layout-tablet="1,8,12,28" data-layout-mobile="1,8,12,42" data-sq-product-grid>
              <article data-product-card="granola"><?= ez_admin_product_art('Granola Madu Nusantara') ?><div><small>Breakfast · 320 g</small><h3>Granola Madu Nusantara</h3><p>Honey-toasted oats, cashews, and warm local spice.</p><footer><b>Rp58.000</b><button type="button">Add to cart</button></footer></div></article>
              <article data-product-card="coffee"><?= ez_admin_product_art('Kopi Susu Concentrate') ?><div><small>Drinks · 650 ml</small><h3>Kopi Susu Concentrate</h3><p>Rich café-style coffee, balanced and ready in seconds.</p><footer><b>Rp79.000</b><button type="button">Add to cart</button></footer></div></article>
              <article data-product-card="sambal"><?= ez_admin_product_art('Sambal Roa Signature') ?><div><small>Pantry · 260 g</small><h3>Sambal Roa Signature</h3><p>Deep smoke, bright chili, and a savory Manado finish.</p><footer><b>Rp46.000</b><button type="button">Add to cart</button></footer></div></article>
            </div></section>
            <section class="sq-page-block sq-image-story" id="story" draggable="true" data-sq-block data-sq-fluid data-sq-rows="12" data-section-id="image-story"><button class="sq-block-handle" type="button" aria-label="Drag image story section"><?= ez_admin_icon('grip') ?></button><div data-sq-element data-sq-element-type="image" data-layout-desktop="1,1,7,12" data-layout-tablet="1,1,12,6" data-layout-mobile="1,1,12,6"><?= ez_admin_product_art('Granola Madu Nusantara') ?></div><article data-sq-element data-sq-element-type="copy" data-layout-desktop="8,1,5,12" data-layout-tablet="1,7,12,6" data-layout-mobile="1,7,12,6"><span>Image-led storytelling</span><h2>Let the product fill the screen.</h2><p>Use photography as the complete section or pair it with a short story. Image-only layouts are always available, but never forced by default.</p><button type="button">See how it is made</button></article></section>
            <section class="sq-page-block sq-benefit-row" draggable="true" data-sq-block data-sq-fluid data-sq-rows="6" data-section-id="benefits"><button class="sq-block-handle" type="button" aria-label="Drag benefits section"><?= ez_admin_icon('grip') ?></button><article data-sq-element data-sq-element-type="benefit" data-layout-desktop="1,1,4,6" data-layout-tablet="1,1,4,6" data-layout-mobile="1,1,12,2"><?= ez_admin_icon('star') ?><div><b>Clear product details</b><small>Know exactly what you will receive</small></div></article><article data-sq-element data-sq-element-type="benefit" data-layout-desktop="5,1,4,6" data-layout-tablet="5,1,4,6" data-layout-mobile="1,3,12,2"><?= ez_admin_icon('credit-card') ?><div><b>Secure payment</b><small>Checkout details verified by Ezkart</small></div></article><article data-physical-only data-sq-element data-sq-element-type="benefit" data-layout-desktop="9,1,4,6" data-layout-tablet="9,1,4,6" data-layout-mobile="1,5,12,2"><?= ez_admin_icon('truck') ?><div><b>Delivery arranged</b><small>Courier, live rate, and ETA at checkout</small></div></article></section>
            <section class="sq-page-block sq-cart-section" draggable="true" data-sq-block data-sq-fluid data-sq-rows="12" data-section-id="checkout"><button class="sq-block-handle" type="button" aria-label="Drag checkout section"><?= ez_admin_icon('grip') ?></button><div data-sq-element data-sq-element-type="copy" data-layout-desktop="1,1,6,12" data-layout-tablet="1,1,12,5" data-layout-mobile="1,1,12,5"><span>Your basket</span><h2>One checkout for every product on the page.</h2><p>Customers can combine products, choose quantities, and pay once through Ezkart's secure checkout.</p></div><aside data-sq-element data-sq-element-type="checkout" data-layout-desktop="8,2,5,10" data-layout-tablet="1,6,12,7" data-layout-mobile="1,6,12,7"><small>Example basket</small><ul data-sq-basket-lines><li data-product-line="granola"><span>Granola Madu Nusantara</span><b>Rp58.000</b></li><li data-product-line="coffee"><span>Kopi Susu Concentrate</span><b>Rp79.000</b></li><li data-product-line="sambal"><span>Sambal Roa Signature</span><b>Rp46.000</b></li></ul><footer><span>Total</span><strong data-sq-basket-total>Rp183.000</strong></footer><button type="button">Continue to secure checkout</button><em><?= ez_admin_icon('shield') ?> Secure checkout powered by Ezkart</em></aside></section>
            <section class="sq-page-block sq-shipping-section" id="shipping" data-physical-only draggable="true" data-sq-block data-sq-fluid data-sq-rows="5" data-section-id="shipping"><button class="sq-block-handle" type="button" aria-label="Drag shipping section"><?= ez_admin_icon('grip') ?></button><span data-sq-element data-sq-element-type="icon" data-layout-desktop="1,1,1,5" data-layout-tablet="1,1,2,5" data-layout-mobile="1,1,2,5"><?= ez_admin_icon('truck') ?></span><div data-sq-element data-sq-element-type="copy" data-layout-desktop="2,1,7,5" data-layout-tablet="3,1,10,3" data-layout-mobile="3,1,10,3"><small>Ezkart fulfillment</small><h2>From page visit to delivered order.</h2><p>Address collection, product weights, courier quotes, payment state, and fulfillment stay connected in one flow.</p></div><ul data-sq-element data-sq-element-type="list" data-layout-desktop="9,1,4,5" data-layout-tablet="3,4,10,2" data-layout-mobile="3,4,10,2"><li>JNE REG</li><li>SiCepat REG</li><li>J&amp;T EZ</li></ul></section>
          </article>
        </div>
      </div>
      <footer class="sq-stage-footer"><span><i></i> Editable canvas</span><span data-sq-stage-size>Desktop · 1440px</span><span data-sq-commerce-status><?= ez_admin_icon('shield') ?> Checking commerce integrations…</span></footer>
    </main>

    <aside class="sq-inspector">
      <header><div><small data-sq-inspector-context>Selected section</small><h2 data-sq-inspector-title>Announcement</h2></div><button type="button" data-sq-close-inspector aria-label="Close inspector"><?= ez_admin_icon('x') ?></button></header>
      <div class="sq-inspector-scroll">
        <section class="sq-content-controls"><div class="sq-inspector-heading"><h3>Content</h3><span>Direct edit</span></div><p class="sq-field-note">Edit here or click text directly on the canvas. Every section has its own fields.</p><div class="sq-content-fields" data-sq-content-fields></div></section>
        <section class="sq-element-controls" data-sq-element-controls hidden>
          <button class="sq-inspector-back" type="button" data-sq-select-section><?= ez_admin_icon('chevron-left') ?> Back to section</button>
          <div class="sq-inspector-heading"><h3>Element settings</h3><span data-sq-element-type>Element</span></div>
          <div class="sq-element-text-editor" data-sq-element-text-controls hidden><label><span data-sq-element-text-label>Text content</span><textarea rows="4" data-sq-element-text></textarea></label><p class="sq-field-note">Changes appear on the canvas immediately.</p></div>
          <div class="sq-logo-editor" data-sq-logo-controls hidden><div class="sq-inspector-heading"><h3>Logo</h3><span>Header brand</span></div><div class="sq-image-source-row"><label class="sq-upload-image"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif,image/svg+xml" data-sq-logo-upload><?= ez_admin_icon('image') ?><span>Upload logo</span></label><button type="button" data-sq-logo-clear>Use text</button></div><label><span>Logo URL</span><input type="url" placeholder="https://…" data-sq-logo-src></label><label><span>Brand name fallback</span><input type="text" maxlength="80" data-sq-logo-text-input></label><label><span>Logo alt text</span><input type="text" maxlength="120" data-sq-logo-alt></label><label><span>Logo width</span><input type="range" min="40" max="280" value="140" data-sq-logo-width><output data-sq-logo-width-output>140px</output></label><p class="sq-field-note">PNG, SVG, WebP, and JPEG are supported. Text remains as an accessible fallback.</p></div>
          <div class="sq-image-editor" data-sq-image-controls hidden>
            <div class="sq-inspector-heading"><h3>Image</h3><span>Live preview</span></div>
            <div class="sq-image-source-row"><label class="sq-upload-image"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif" data-sq-image-upload><?= ez_admin_icon('image') ?><span>Replace image</span></label><button type="button" data-sq-image-reset>Reset effects</button></div>
            <label><span>Image URL</span><input type="url" placeholder="https://…" data-sq-image-src></label>
            <label><span>Alt text</span><input type="text" maxlength="180" placeholder="Describe this image" data-sq-image-alt></label>
            <div class="sq-element-style-row"><label><span>Fit</span><select data-sq-image-fit><option value="cover">Cover</option><option value="contain">Contain</option><option value="fill">Stretch</option></select></label><label><span>Position</span><select data-sq-image-position><option value="center">Center</option><option value="top">Top</option><option value="bottom">Bottom</option><option value="left">Left</option><option value="right">Right</option></select></label></div>
            <div class="sq-image-adjustments">
              <label><span>Blur</span><input type="range" min="0" max="24" step="1" value="0" data-sq-image-filter="blur"><output data-sq-image-output="blur">0px</output></label>
              <label><span>Brightness</span><input type="range" min="30" max="170" step="5" value="100" data-sq-image-filter="brightness"><output data-sq-image-output="brightness">100%</output></label>
              <label><span>Contrast</span><input type="range" min="30" max="170" step="5" value="100" data-sq-image-filter="contrast"><output data-sq-image-output="contrast">100%</output></label>
              <label><span>Saturation</span><input type="range" min="0" max="200" step="5" value="100" data-sq-image-filter="saturate"><output data-sq-image-output="saturate">100%</output></label>
              <label><span>Grayscale</span><input type="range" min="0" max="100" step="5" value="0" data-sq-image-filter="grayscale"><output data-sq-image-output="grayscale">0%</output></label>
              <label><span>Opacity</span><input type="range" min="10" max="100" step="5" value="100" data-sq-image-filter="opacity"><output data-sq-image-output="opacity">100%</output></label>
            </div>
          </div>
          <div class="sq-element-button-role" data-sq-element-button-controls hidden>
            <div class="sq-inspector-heading"><h3>Button action</h3><span>Click behavior</span></div>
            <label><span>Button label</span><input type="text" maxlength="80" data-sq-button-label></label>
            <label><span>Destination</span><select data-sq-button-link-type><option value="section">Page section</option><option value="url">Web address</option><option value="checkout">Checkout</option><option value="email">Email</option><option value="phone">Phone</option><option value="none">No action</option></select></label>
            <label data-sq-button-link-wrap><span data-sq-button-link-label>Section ID</span><input type="text" placeholder="products" data-sq-button-link></label>
            <label class="sq-new-tab"><input type="checkbox" data-sq-button-new-tab><span>Open in a new tab</span></label>
            <div class="sq-checkout-test" data-sq-checkout-test hidden><span><?= ez_admin_icon('shield') ?></span><div><b>Connected checkout handoff</b><small>Biteship rates → secure payment</small></div><button type="button" data-sq-test-checkout>Open checkout</button></div>
            <h3 class="sq-role-heading">Visual role</h3><div class="sq-role-choices"><button class="active button-primary" type="button" data-sq-role-choice="primary">Primary</button><button class="button-secondary" type="button" data-sq-role-choice="secondary">Secondary</button><button class="button-tertiary" type="button" data-sq-role-choice="tertiary">Tertiary</button></div><p class="sq-field-note">Roles stay synchronized with the global button system.</p>
          </div>
          <div class="sq-product-layout-controls" data-sq-product-layout-controls hidden>
            <div class="sq-inspector-heading"><h3>Product grid layout</h3><span data-sq-product-layout-device>Desktop</span></div>
            <label><span>Cards per row</span><select data-sq-product-columns><option value="auto">Auto fit while resizing</option><option value="1">1 card</option><option value="2">2 cards</option><option value="3">3 cards</option><option value="4">4 cards</option></select></label>
            <label><span>Card size</span><select data-sq-product-density><option value="compact">Compact</option><option value="balanced">Balanced</option><option value="showcase">Large showcase</option></select></label>
            <p class="sq-field-note">Drag product cards to reorder them. Auto fit reflows cards as you resize this element instead of clipping them.</p>
          </div>
          <div class="sq-element-appearance"><h3>Appearance</h3><div class="sq-color-fields"><label><span>Text</span><input type="color" value="#24262b" data-sq-element-color="color"></label><label><span>Background</span><input type="color" value="#ffffff" data-sq-element-color="backgroundColor"></label><label><span>Border</span><input type="color" value="#e3e5e7" data-sq-element-color="borderColor"></label></div><div class="sq-element-style-row"><label><span>Surface</span><select data-sq-element-surface><option value="none">None</option><option value="soft">Soft</option><option value="card">Card</option><option value="outline">Outline</option><option value="glass">Glass</option></select></label><label><span>Align</span><select data-sq-element-align><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label></div><label><span>Corner radius</span><input type="range" min="0" max="48" value="0" data-sq-element-radius><output data-sq-element-radius-output>0px</output></label><button class="sq-reset-style" type="button" data-sq-element-style-reset>Reset element colors</button></div>
          <div class="sq-element-motion"><div class="sq-inspector-heading"><h3>Element motion</h3><span>Runs in Preview</span></div><label><span>Entrance effect</span><select data-sq-element-animation-control><option value="none">None</option><option value="fade">Fade in</option><option value="rise">Rise and fade</option><option value="slide-left">Slide from left</option><option value="slide-right">Slide from right</option><option value="scale">Soft scale</option><option value="blur">Blur reveal</option><option value="flip">Perspective flip</option></select></label><div class="sq-inline-controls"><label><span>Duration</span><input type="range" min="200" max="1800" step="100" value="700" data-sq-element-duration><output data-sq-element-duration-output>700ms</output></label><label><span>Delay</span><input type="range" min="0" max="1200" step="100" value="0" data-sq-element-delay><output data-sq-element-delay-output>0ms</output></label></div><div class="sq-hover-options"><button type="button" data-sq-hover-choice="none"><span>None</span></button><button type="button" data-sq-hover-choice="lift"><span>Lift</span></button><button type="button" data-sq-hover-choice="scale"><span>Scale</span></button><button type="button" data-sq-hover-choice="glow"><span>Glow</span></button><button type="button" data-sq-hover-choice="tilt"><span>Tilt</span></button><button type="button" data-sq-hover-choice="image-zoom"><span>Image zoom</span></button></div><button class="sq-replay-button" type="button" data-sq-element-replay><?= ez_admin_icon('play') ?> Preview page</button></div>
          <div class="sq-entrance-previews"><div class="sq-inspector-heading"><h3>Entrance effects</h3><span>Choose effect</span></div><div><button type="button" data-sq-entrance-preview="fade"><span>Fade</span></button><button type="button" data-sq-entrance-preview="rise"><span>Rise</span></button><button type="button" data-sq-entrance-preview="slide-left"><span>Left</span></button><button type="button" data-sq-entrance-preview="slide-right"><span>Right</span></button><button type="button" data-sq-entrance-preview="scale"><span>Scale</span></button><button type="button" data-sq-entrance-preview="blur"><span>Blur</span></button><button type="button" data-sq-entrance-preview="flip"><span>Flip</span></button></div></div>
          <details class="sq-advanced-layout"><summary>Advanced position &amp; size <span>12-column grid</span></summary><div><label data-sq-hero-preset-wrap><span>Section layout preset</span><select data-sq-layout-preset><option value="custom">Custom arrangement</option><option value="split">Split</option><option value="text-only">Text only / remove images</option><option value="single-image">Text + single image</option><option value="image-only">Image only</option><option value="stacked">Stacked</option></select></label><div class="sq-element-position"><label><span>Column</span><input type="number" min="1" max="12" data-sq-element-x></label><label><span>Row</span><input type="number" min="1" max="30" data-sq-element-y></label><label><span>Width</span><input type="number" min="1" max="12" data-sq-element-w></label><label><span>Height</span><input type="number" min="1" max="30" data-sq-element-h></label></div><p class="sq-field-note">Drag on the canvas for normal editing. Exact values are saved independently for desktop, tablet, and mobile.</p></div></details>
          <div class="sq-code-controls" data-sq-code-controls hidden><div class="sq-inspector-heading"><h3>Custom HTML, CSS &amp; JS</h3><span>Sandboxed</span></div><p class="sq-field-note">Code runs inside an isolated preview while editing and is included directly in exported HTML.</p><textarea rows="12" spellcheck="false" data-sq-code-input></textarea><button class="sq-replay-button" type="button" data-sq-run-code><?= ez_admin_icon('play') ?> Run code preview</button></div>
          <div class="sq-element-actions"><button type="button" data-sq-element-duplicate><?= ez_admin_icon('layers') ?> Duplicate</button><button type="button" data-sq-element-hide><?= ez_admin_icon('eye') ?> Hide</button><button class="danger" type="button" data-sq-element-delete><?= ez_admin_icon('x') ?> Delete</button></div>
        </section>
        <section><div class="sq-inspector-heading"><h3>Responsive spacing</h3><span data-sq-spacing-device>Desktop</span></div><label class="sq-link-spacing"><input type="checkbox" data-sq-link-spacing><span>Link all sides</span></label><div class="sq-spacing-grid"><label><span>Top</span><input type="range" min="0" max="160" value="8" data-sq-spacing="top"><output data-sq-spacing-output="top">8</output></label><label><span>Right</span><input type="range" min="0" max="160" value="16" data-sq-spacing="right"><output data-sq-spacing-output="right">16</output></label><label><span>Bottom</span><input type="range" min="0" max="160" value="8" data-sq-spacing="bottom"><output data-sq-spacing-output="bottom">8</output></label><label><span>Left</span><input type="range" min="0" max="160" value="16" data-sq-spacing="left"><output data-sq-spacing-output="left">16</output></label></div><p class="sq-field-note">Values are saved independently for desktop, tablet, and mobile.</p></section>
        <section><h3>Entrance animation</h3><label><span>Effect</span><select data-sq-animation><option value="none">None</option><option value="fade">Fade in</option><option value="slide-up">Slide up</option><option value="slide-left">Slide from left</option><option value="scale">Soft scale</option></select></label><div class="sq-inline-controls"><label><span>Duration</span><input type="range" min="200" max="1600" step="100" value="600" data-sq-duration><output data-sq-duration-output>600ms</output></label><label><span>Delay</span><input type="range" min="0" max="1000" step="100" value="0" data-sq-delay><output data-sq-delay-output>0ms</output></label></div><label><span>Easing</span><select data-sq-easing><option value="ease-out">Smooth out</option><option value="ease-in-out">Smooth both</option><option value="cubic-bezier(.2,.8,.2,1)">Expressive</option><option value="linear">Linear</option></select></label><button class="sq-replay-button" type="button" data-sq-replay><?= ez_admin_icon('play') ?> Preview page</button></section>
        <section><h3>Section layout</h3><label><span>Content width</span><input type="range" min="720" max="1440" step="40" value="1200" data-sq-content-width><output data-sq-width-output>1200px</output></label><label><span>Background</span><select data-sq-background><option value="light">Warm white</option><option value="white">White</option><option value="dark">Charcoal</option><option value="accent">Brand accent</option></select></label></section>
      </div>
      <footer><button type="button" data-sq-duplicate><?= ez_admin_icon('layers') ?> Duplicate</button><button type="button" data-sq-visibility><?= ez_admin_icon('eye') ?> Hide</button><button class="danger" type="button" data-sq-delete aria-label="Delete selected section"><?= ez_admin_icon('x') ?> Delete section</button></footer>
    </aside>
  </div>
</section>

<dialog class="sq-live-preview-dialog" id="landing-preview-dialog">
  <div class="sq-live-preview-shell"><header><div><small>Live page preview</small><h2 data-sq-preview-title>Landing page</h2></div><nav aria-label="Preview size"><button class="active" type="button" data-sq-preview-device="desktop"><?= ez_admin_icon('monitor') ?><span>Desktop · 1440</span></button><button type="button" data-sq-preview-device="tablet"><?= ez_admin_icon('layout') ?><span>Tablet · 768</span></button><button type="button" data-sq-preview-device="mobile"><?= ez_admin_icon('smartphone') ?><span>Mobile · 390</span></button></nav><div><button type="button" data-sq-preview-new-tab><?= ez_admin_icon('globe') ?><span>Open tab</span></button><button type="button" data-sq-preview-close aria-label="Close preview"><?= ez_admin_icon('x') ?></button></div></header><main data-sq-live-preview-stage data-preview-device="desktop"><div class="sq-live-preview-frame"><iframe title="Landing page production preview" sandbox="allow-scripts allow-forms allow-popups allow-top-navigation-by-user-activation" data-sq-live-preview-frame></iframe></div></main></div>
</dialog>

<dialog class="sq-export-dialog" id="html-export-dialog">
  <form method="dialog"><header><span><?= ez_admin_icon('code') ?></span><div><small>Production output</small><h2>Generated landing-page HTML</h2><p>Responsive structure, selected products, spacing, animations, SEO metadata, and checkout hooks are included.</p></div><button value="close" aria-label="Close HTML export"><?= ez_admin_icon('x') ?></button></header><div class="sq-export-summary"><span><?= ez_admin_icon('check-circle') ?> Semantic HTML</span><span><?= ez_admin_icon('check-circle') ?> Responsive CSS</span><span><?= ez_admin_icon('check-circle') ?> Animation CSS</span><span><?= ez_admin_icon('check-circle') ?> Commerce hooks</span></div><textarea readonly spellcheck="false" data-sq-html-output></textarea><footer><small data-sq-html-size>Ready to generate</small><button type="button" data-sq-copy-html>Copy HTML</button><button class="primary" type="button" data-sq-download-html><?= ez_admin_icon('download') ?> Download .html</button></footer></form>
</dialog>

<dialog class="page-creator-dialog" id="page-creator-dialog"><form method="dialog" data-page-creator-form>
  <header><span><?= ez_admin_icon('layout') ?></span><div><small>Create a landing page</small><h2>Start with at least one product.</h2><p>Choose from the real products already saved in your Ezkart catalog.</p></div><button type="button" data-creator-close aria-label="Close"><?= ez_admin_icon('x') ?></button></header>
  <section>
    <label><span>Page name</span><input name="page_name" required maxlength="60" placeholder="Example: Ramadan Collection"></label>
    <fieldset data-creator-products><legend>Starting products</legend><p class="creator-products-empty" data-creator-products-empty>No products are available yet. <a href="?page=products">Create a product first</a>.</p></fieldset>
    <label><span>Free Ezkart URL</span><div class="slug-field"><input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="ramadan-collection"><em>.ezkart.site</em></div></label>
  </section>
  <footer><button type="button" data-creator-close>Cancel</button><button class="primary" value="default" data-create-page>Build full page</button></footer>
</form></dialog>
