<?php
if (!isset($notificationConfig)) { http_response_code(404); exit; }
$noticeEscape = static fn($value): string => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$noticeIcons = ['settings'=>'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10 3v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>','message'=>'<path d="M20 15a3 3 0 0 1-3 3H8l-5 3V7a3 3 0 0 1 3-3h11a3 3 0 0 1 3 3v8Z"/><path d="M8 10h8M8 14h5"/>','mail'=>'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>','truck'=>'<path d="M3 6h11v11H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>','check-circle'=>'<circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16.5 8"/>','chevron-down'=>'<path d="m7 10 5 5 5-5"/>','refresh'=>'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 11.6-1L20 9M4 15l2.4 3A7 7 0 0 0 18 17"/>','filter'=>'<path d="M4 7h16M7 12h10M10 17h4"/><circle cx="8" cy="7" r="2"/><circle cx="16" cy="12" r="2"/>','inbox'=>'<path d="m4 4-2 11v5h20v-5L20 4ZM2 15h6l2 3h4l2-3h6"/>','arrow'=>'<path d="M5 12h14m-5-5 5 5-5 5"/>'];
$noticeIcon = static fn(string $name): string => '<svg class="notice-action-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">' . $noticeIcons[$name] . '</svg>';
?>
<link rel="stylesheet" href="/cart/notifications.css?v=<?= (int) filemtime(__DIR__ . '/notifications.css') ?>">
<section class="ez-notifications" data-notification-workspace data-config="<?= $noticeEscape(json_encode($notificationConfig, JSON_THROW_ON_ERROR)) ?>" aria-label="Notifications">
  <template data-notice-icon="check"><?= $noticeIcon('check-circle') ?></template><template data-notice-icon="arrow"><?= $noticeIcon('arrow') ?></template>
  <header class="notice-header"><div><h1>Notifications</h1><p><?= $notificationConfig['merchant'] ? 'Keep up with payments, deliveries, returns, refunds, and conversations.' : 'Updates from your stores, from payment to delivery.' ?></p></div><div class="notice-actions"><button type="button" data-notice-refresh> <?= $noticeIcon('refresh') ?><span>Refresh</span></button><?php if ($notificationConfig['merchant']): ?><a href="?page=settings#notifications"> <?= $noticeIcon('settings') ?><span>Preferences</span></a><?php else: ?><a href="/cart/messages.php"> <?= $noticeIcon('message') ?><span>Messages</span></a><?php endif; ?></div></header>
  <div class="notice-summary"><strong data-notice-count>Loading updates…</strong><span data-notice-total></span></div>
  <p class="notice-info" data-notice-held hidden></p><p class="notice-error" data-notice-error role="alert" hidden></p><a href="" data-notice-signin hidden>Reload sign-in</a>
  <p data-notice-live role="status" class="notice-live"></p>
  <div data-notice-private>
    <nav class="notice-views" aria-label="Notification views"><button type="button" data-notice-view="inbox" aria-pressed="true"> <?= $noticeIcon('inbox') ?><span>Your inbox</span></button><button type="button" data-notice-view="email" aria-pressed="false"> <?= $noticeIcon('mail') ?><span>Your emails</span></button><?php if ($notificationConfig['merchant']): ?><button type="button" data-notice-view="processing" aria-pressed="false"> <?= $noticeIcon('truck') ?><span>Store delivery activity</span></button><?php else: ?><button type="button" data-notice-view="preferences" aria-pressed="false"> <?= $noticeIcon('settings') ?><span>Preferences</span></button><?php endif; ?></nav>
    <section data-notice-inbox aria-label="Your notification inbox">
      <p class="notice-info" data-notice-email-info hidden>Your email notification history includes updates you chose to receive by email only. Delivery confirms acceptance by your mail server; it does not confirm you read the email.</p>
      <form class="notice-filters" data-notice-filters><label>Search updates<input type="search" name="q" maxlength="120" placeholder="Search notification text"></label><label>Category<select name="category"><option value="">All categories</option><option value="payment_confirmed">Payment confirmed</option><option value="payment_pending">Payment pending</option><option value="payment_failed">Payment unsuccessful</option><?php if ($notificationConfig['merchant']): ?><option value="payment_review">Payment review</option><?php endif; ?><option value="shipping">Shipping</option><option value="returns">Returns and refunds</option><option value="messages">Messages</option><?php if ($notificationConfig['merchant']): ?><option value="weekly_activity">Weekly activity</option><?php endif; ?></select></label><label data-notice-read-filter>Read status<select name="state"><option value="all">All updates</option><option value="unread">Unread</option><option value="read">Read</option></select></label><button type="submit"> <?= $noticeIcon('filter') ?><span>Apply filters</span></button></form>
      <div class="notice-list-heading"><p data-notice-result role="status">Loading your notifications…</p><button type="button" data-notice-mark disabled> <?= $noticeIcon('check-circle') ?><span data-notice-mark-label>Mark shown as read</span></button></div>
      <p class="notice-error" data-notice-read-error role="alert" hidden></p><button type="button" data-notice-read-retry hidden> <?= $noticeIcon('refresh') ?><span>Retry read confirmation</span></button>
      <ol class="notice-list" data-notice-list></ol><button type="button" data-notice-more hidden> <?= $noticeIcon('chevron-down') ?><span>Load older notifications</span></button>
    </section>
    <?php if (!$notificationConfig['merchant']) require __DIR__ . '/buyer-notification-preferences.php'; ?>
    <?php if ($notificationConfig['merchant']): ?><section data-notice-processing aria-label="Store notification delivery activity" hidden>
      <p class="notice-info">Delivery activity covers this store's updates. In-app counts confirm that an update reached an inbox. Email delivery confirms acceptance by the recipient’s mail server. Neither confirms the update was read.</p>
      <form class="notice-filters notice-processing-filter" data-notice-process-filters><label>Delivery state<select name="state"><option value="attention">Needs attention</option><option value="queued">Queued</option><option value="succeeded">Processed</option><option value="all">All updates</option></select></label><button type="submit"> <?= $noticeIcon('filter') ?><span>Apply delivery filter</span></button></form>
      <p data-notice-process-result role="status"></p><ol class="notice-list" data-notice-process-list></ol><button type="button" data-notice-process-more hidden> <?= $noticeIcon('chevron-down') ?><span>Load older delivery activity</span></button>
    </section><?php endif; ?>
  </div>
</section>
<?php if (!$notificationConfig['merchant']): ?><script src="/cart/buyer-notification-preferences.js?v=<?= (int) filemtime(__DIR__ . '/buyer-notification-preferences.js') ?>" defer></script><?php endif; ?>
<script src="/cart/notifications.js?v=<?= (int) filemtime(__DIR__ . '/notifications.js') ?>" defer></script>
