import {supportAccess} from './commerce-support.js';
import {commerceHash} from './commerce-orders.js';
import {sellerByPageAddress} from './seller-page-address.js';
import {decodeHTML} from 'entities';
import {seedJevPageRevision} from './jev-page-state.js';
import {JEV_MIN_CONFIDENCE,jevDecision,JEV_MODEL,JEV_POLICY,JEV_RULES,JEV_VIOLATIONS,normalizeJevOutcome,jevRequest,callJev} from './jev-provider.js';
const fail=(m,s=422)=>{throw new Response(m,{status:s});};
const now=()=>new Date().toISOString(),id=p=>p+crypto.randomUUID().replaceAll('-','');
const fields=(v,ks)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!ks.includes(k)))fail('Jev request is invalid.');};
const key=k=>{if(typeof k!=='string'||!/^[a-f0-9]{32}$/.test(k))fail('Original request key is required.');};
const txt=(s,n)=>typeof s==='string'&&s.length<=n&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(s);
const pid=p=>typeof p==='string'&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p)&&p.length<=48;
const pageKey=(s,p)=>`sellers/${s}/landing-pages/${p}.json`;
export async function jevPageHeld(env,sellerId,pageId){return !!await env.DB.prepare('SELECT 1 FROM jev_page_holds WHERE seller_id=? AND page_id=?').bind(sellerId,pageId).first();}
export function jevMode(env){return {advisory:true,reviewerTriggered:true,model:JEV_MODEL,modelEnabled:env.JEV_ENABLED==='enabled'&&!!env.JEV_OPENROUTER_API_KEY,
 minimumConfidence:JEV_MIN_CONFIDENCE,policyVersion:JEV_POLICY,policyRules:JEV_RULES,policyApproved:env.JEV_APPROVED_POLICY===JEV_POLICY,archiveEnabled:env.JEV_ARCHIVE==='enabled'&&env.JEV_APPROVED_POLICY===JEV_POLICY,deletionEnabled:false};}
async function page(env,sellerId,pageId){const object=await env.PRIVATE_ASSETS.get(pageKey(sellerId,pageId));if(!object)fail('Page not found.',404);if(object.size>8000000)fail('Page is too large to review.',413);const value=await object.json();return {value,revision:object.etag};}
const redact=s=>s.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[email redacted]').replace(/\+?[0-9][0-9 ()-]{8,}[0-9]/g,'[number redacted]');
async function snapshot(p){
 const html=String(p.value.publishedHtml||''),stack=[],chunks=[];let media=false;const voids=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);
 await new HTMLRewriter().on('*',{element(e){if(['img','video','audio','iframe','canvas','svg'].includes(e.tagName))media=true;const blocked=stack.some(x=>x.blocked)||['script','style','template','noscript'].includes(e.tagName)||e.hasAttribute('hidden')||e.getAttribute('aria-hidden')==='true';
  if(!voids.has(e.tagName)){const item={blocked};stack.push(item);e.onEndTag(()=>{const i=stack.indexOf(item);if(i>=0)stack.splice(i);});}},text(t){if(!stack.some(x=>x.blocked))chunks.push(t.text);}}).transform(new Response(html)).text();
 const all=redact(decodeHTML(chunks.join(' ')).replace(/\s+/g,' ').trim()),short=all.slice(0,2800),sources=[];
 for(let i=0;i<short.length;i+=700)sources.push({id:'page:'+String(sources.length+1),text:short.slice(i,i+700)});
 return {sources,coverage:{textOnly:true,unreviewedMedia:media,truncated:short.length<all.length},name:String(p.value.name||'').slice(0,80)};
}
async function store(env,slug){if(typeof slug!=='string'||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)||slug.length>96)fail('Store address is invalid.');const s=await sellerByPageAddress(env,slug);if(!s)fail('Store not found.',404);return s;}
export async function jevPages(env,actor,url){await supportAccess(env,actor);if([...url.searchParams.keys()].some(k=>k!=='store')||url.searchParams.getAll('store').length!==1)fail('Choose one store address.');const seller=await store(env,url.searchParams.get('store'));
 const objects=await env.PRIVATE_ASSETS.list({prefix:`sellers/${seller.id}/landing-pages/`,limit:100});const pages=[];
 for(const o of objects.objects.filter(o=>o.key.endsWith('.json'))){const p=o.key.split('/').pop().slice(0,-5);pages.push({id:p,name:o.customMetadata?.name||p,revision:o.etag,status:o.customMetadata?.status||'unknown',archived:await jevPageHeld(env,seller.id,p)});}
 return {store:seller.pageSlug||seller.slug,pages,truncated:objects.truncated};}
const read=async(env,rid)=>{const r=await env.DB.prepare(`SELECT r.*,c.seller_id,c.page_id,c.store_slug,c.deadline_at,c.evaluation_only FROM jev_reviews r JOIN jev_cases c ON c.id=r.case_id WHERE r.id=?`).bind(rid).first();if(!r)fail('Review not found.',404);return r;};
async function shape(env,r,full=false){const result=await env.DB.prepare('SELECT * FROM jev_results WHERE review_id=?').bind(r.id).first(),attempt=await env.DB.prepare('SELECT created_at FROM jev_attempts WHERE review_id=?').bind(r.id).first();
 const archive=await env.DB.prepare('SELECT id,action,reason,created_at,review_id FROM jev_page_actions WHERE seller_id=? AND page_id=? ORDER BY sequence DESC LIMIT 1').bind(r.seller_id,r.page_id).first();
 const state=result?.state||(attempt?'uncertain':'queued'),out={id:r.id,caseId:r.case_id,store:r.store_slug,pageId:r.page_id,revision:r.revision,createdAt:r.created_at,state,canGrade:!!result,deadlineAt:r.deadline_at,rescanCount:r.ordinal,due:!r.evaluation_only&&now()>=r.deadline_at,archiveState:archive?.action==='archive'?'archived':'active',archiveReason:archive?.reason||'',archiveId:archive?.action==='archive'?archive.id:null,evaluationOnly:!!r.evaluation_only,policyVersion:r.policy_version,outcome:result?.outcome_json?JSON.parse(result.outcome_json):null,failureCode:result?.failure_code||null};
 Object.assign(out,jevDecision(out.outcome,JSON.parse(r.snapshot_json)));
 if(full){const snap=JSON.parse(r.snapshot_json);Object.assign(out,{reportText:r.report_text,sources:snap.sources,coverage:snap.coverage,caseTitle:r.evaluation_only?snap.name:null,expectedVerdict:r.evaluation_only?snap.expectedVerdict||null:null,model:JEV_MODEL,costMicrousd:result?.cost_microusd??null,rejectedOutput:result?.rejected_output||null,inputTokens:result?.input_tokens??null,outputTokens:result?.output_tokens??null,
 grades:(await env.DB.prepare('SELECT id,score,agreement,comment,created_by AS createdBy,created_at AS createdAt FROM jev_grades WHERE review_id=? ORDER BY created_at DESC,id DESC').bind(r.id).all()).results});try{const current=await page(env,r.seller_id,r.page_id);out.currentRevision=current.revision;if(current.revision!==r.revision){const source=await snapshot(current);out.currentSources=source.sources;out.currentCoverage=source.coverage;}}catch{out.currentRevision=null;}out.stale=!r.evaluation_only&&out.currentRevision!==r.revision;}
 return out;}
async function budgetMode(env){const b=await env.DB.prepare("SELECT COUNT(*) AS allCalls,SUM(CASE WHEN created_by='benchmark-import' THEN 1 ELSE 0 END) AS benchmarkCalls,COALESCE(SUM(budget_microusd),0) AS reserved FROM jev_attempts").first();return {...jevMode(env),benchmarkCalls:b.benchmarkCalls||0,reviewerCalls:b.allCalls-(b.benchmarkCalls||0),remainingCalls:Math.max(0,Number(env.JEV_MAX_CALLS||0)-b.allCalls+(b.benchmarkCalls||0)),remainingBudgetMicrousd:Math.max(0,Number(env.JEV_BUDGET_MICROUSD||0)-b.reserved),perCallReservationMicrousd:10000};}
export async function jevList(env,actor,url){const permission=await supportAccess(env,actor);if(url.search)fail('Review filters are not supported.');const rows=await env.DB.prepare(`SELECT r.*,c.seller_id,c.page_id,c.store_slug,c.deadline_at,c.evaluation_only FROM jev_reviews r JOIN jev_cases c ON c.id=r.case_id ORDER BY r.created_at DESC,r.id DESC LIMIT 51`).all();return {items:await Promise.all(rows.results.slice(0,50).map(r=>shape(env,r))),truncated:rows.results.length>50,mode:await budgetMode(env),canWrite:permission.canWrite};}
export async function jevDetail(env,actor,rid){const permission=await supportAccess(env,actor);return {review:await shape(env,await read(env,rid),true),mode:await budgetMode(env),canWrite:permission.canWrite};}
export async function createJevReview(env,actor,input,parentId=null){await supportAccess(env,actor,true);fields(input,parentId?['requestKey','expectedRevision','reportText']:['requestKey','store','pageId','expectedRevision','reportText']);key(input.requestKey);
 if(!txt(input.reportText,1200)||!input.reportText.trim()||!txt(input.expectedRevision,100))fail('Report text and exact page revision are required.');
 const hash=await commerceHash({actor:actor.id,input,parentId}),old=await env.DB.prepare('SELECT id,request_hash FROM jev_reviews WHERE request_key=?').bind(input.requestKey).first();if(old){if(old.request_hash!==hash)fail('This original request has different details.',409);return jevDetail(env,actor,old.id);}
 const parent=parentId?await read(env,parentId):null;if(parent?.evaluation_only)fail('Synthetic benchmark results cannot rescan a real page.',409);
 const seller=parent?{id:parent.seller_id,pageSlug:parent.store_slug}:await store(env,input.store),pageId=parent?.page_id||input.pageId;if(!pid(pageId))fail('Page reference is invalid.');
 if(!parent&&await jevPageHeld(env,seller.id,pageId))fail('This page already has an archive case. Use that original case for re-scans.',409);
 let ordinal=0;if(parent){const latest=await env.DB.prepare('SELECT MAX(ordinal) AS n FROM jev_reviews WHERE case_id=?').bind(parent.case_id).first();ordinal=latest.n+1;if(ordinal>3||now()>=parent.deadline_at)fail('This case is due for a human decision; no further re-scan is allowed.',409);}
 const p=await page(env,seller.id,pageId);if(p.revision!==input.expectedRevision)fail('The page changed. Reload its current revision.',409);await seedJevPageRevision(env,seller.id,pageId,p.revision);const snap=await snapshot(p),at=now(),caseId=parent?.case_id||id('jcase_'),rid=id('jev_'),report=redact(input.reportText.trim());
 const statements=[];if(!parent)statements.push(env.DB.prepare('INSERT INTO jev_cases(id,seller_id,page_id,store_slug,created_by,request_key,request_hash,created_at,deadline_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(caseId,seller.id,pageId,seller.pageSlug||seller.slug,actor.id,input.requestKey,hash,at,new Date(Date.now()+5*86400000).toISOString()));
 statements.push(env.DB.prepare('INSERT INTO jev_reviews(id,case_id,ordinal,request_key,request_hash,revision,snapshot_json,report_text,policy_version,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(rid,caseId,ordinal,input.requestKey,hash,p.revision,JSON.stringify(snap),report,JEV_POLICY,actor.id,at));
 try{await env.DB.batch(statements);}catch(e){if(/jev_|UNIQUE/.test(String(e)))fail('Review changed. Reload the original request.',409);throw e;}return jevDetail(env,actor,rid);}
export async function runJevReview(env,actor,rid,input){await supportAccess(env,actor,true);fields(input,['requestKey']);key(input.requestKey);const r=await read(env,rid);if(r.evaluation_only)fail('Synthetic benchmark results cannot initiate another paid run.',409);
 const old=await env.DB.prepare('SELECT request_key FROM jev_attempts WHERE review_id=?').bind(rid).first();if(old){if(old.request_key!==input.requestKey)fail('Use the original run request; Jev will not repeat an uncertain call.',409);return jevDetail(env,actor,rid);}
 if(!jevMode(env).modelEnabled)fail('Jev model calls are held until private configuration is enabled.',503);
 const originalPage=await page(env,r.seller_id,r.page_id);if(originalPage.revision!==r.revision)fail('This page changed. Queue a review of its exact current revision.',409);await seedJevPageRevision(env,r.seller_id,r.page_id,originalPage.revision);
 const snap=JSON.parse(r.snapshot_json);let payload;try{payload=jevRequest(snap,r.report_text,r.policy_version);}catch{fail('The bounded review input is too large. Queue a shorter report for human review.',413);}const attemptId=id('jrun_'),at=now(),limit=Number(env.JEV_MAX_CALLS||0),budget=Number(env.JEV_BUDGET_MICROUSD||0);
 if(!Number.isSafeInteger(limit)||limit<1||limit>500||!Number.isSafeInteger(budget)||budget<10000||budget>5000000)fail('Jev needs an explicit call and spending cap.',503);
 const grant=await env.DB.prepare(`INSERT INTO jev_attempts(id,review_id,request_key,model,request_json,budget_microusd,created_by,created_at) SELECT ?,?,?,?,?,10000,?,? WHERE (SELECT COUNT(*) FROM jev_attempts WHERE created_by!='benchmark-import')<? AND (SELECT COALESCE(SUM(budget_microusd),0) FROM jev_attempts)+10000<=? ON CONFLICT DO NOTHING`).bind(attemptId,rid,input.requestKey,JEV_MODEL,JSON.stringify(payload),actor.id,at,limit,budget).run();
 if(!grant.meta.changes){const saved=await env.DB.prepare('SELECT request_key FROM jev_attempts WHERE review_id=?').bind(rid).first();if(saved?.request_key===input.requestKey)return jevDetail(env,actor,rid);fail('Jev evaluation budget is exhausted or this request was already used.',409);}
 let result;try{result=await callJev(env.JEV_OPENROUTER_API_KEY,payload,snap);}catch(e){const code=/^jev_/.test(e.message)?e.message:'jev_response_unconfirmed';await env.DB.prepare('INSERT INTO jev_results(review_id,attempt_id,state,failure_code,rejected_output,provider_id,cost_microusd,input_tokens,output_tokens,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(rid,attemptId,code==='jev_transport_uncertain'?'uncertain':'failed',code,e.diagnostic?.rawOutcome||null,e.diagnostic?.providerId||null,e.diagnostic?.costMicrousd??null,e.diagnostic?.inputTokens??null,e.diagnostic?.outputTokens??null,now()).run();return jevDetail(env,actor,rid);}
 const entries=[env.DB.prepare('INSERT INTO jev_results(review_id,attempt_id,state,outcome_json,provider_id,cost_microusd,input_tokens,output_tokens,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(rid,attemptId,'completed',JSON.stringify(result.outcome),result.providerId,result.costMicrousd,result.inputTokens,result.outputTokens,now())];
 let current=null;try{current=await page(env,r.seller_id,r.page_id);}catch{}
 let authority=true;try{await supportAccess(env,actor,true);}catch{authority=false;}
 const override=await env.DB.prepare("SELECT 1 FROM jev_page_actions WHERE seller_id=? AND page_id=? AND actor_kind='reviewer' AND created_at>=?").bind(r.seller_id,r.page_id,at).first();
 if(authority&&!override&&jevMode(env).archiveEnabled&&r.policy_version===JEV_POLICY&&current?.revision===r.revision&&jevDecision(result.outcome,snap).decisionVerdict==='needs_change'&&!result.outcome.uncertainties.length&&!snap.coverage.unreviewedMedia&&!snap.coverage.truncated&&result.outcome.findings.some(f=>JEV_VIOLATIONS.includes(f.code))){
  entries.push(action(env,r,'archive','jev',attemptId,'auto:'+attemptId,result.outcome.summary));}
 try{await env.DB.batch(entries);}catch(e){if(entries.length>1&&/jev_page_revision_changed|jev_human_override/.test(String(e)))await entries[0].run();else throw e;}return jevDetail(env,actor,rid);}
function action(env,r,type,kind,actor,requestKey,reason,hash='',targetRevision=r.revision,holdId=null){return env.DB.prepare('INSERT INTO jev_page_actions(id,seller_id,page_id,review_id,revision,target_revision,action,actor_kind,actor_id,request_key,request_hash,reason,created_at,supersedes_action_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id('jact_'),r.seller_id,r.page_id,r.id,r.revision,targetRevision,type,kind,actor,requestKey,hash,reason,now(),holdId);}
export async function gradeJevReview(env,actor,rid,input){await supportAccess(env,actor,true);fields(input,['requestKey','score','agreement','comment']);key(input.requestKey);if(!Number.isInteger(input.score)||input.score<1||input.score>5||!['agree','disagree','uncertain'].includes(input.agreement)||!txt(input.comment,1200))fail('Grade is invalid.');await read(env,rid);
 if(!await env.DB.prepare("SELECT 1 FROM jev_results WHERE review_id=?").bind(rid).first())fail('A recorded model outcome or failure is required before grading.',409);
 const hash=await commerceHash({rid,actor:actor.id,input}),old=await env.DB.prepare('SELECT request_hash FROM jev_grades WHERE request_key=?').bind(input.requestKey).first();if(old&&old.request_hash!==hash)fail('Original grade details cannot change.',409);
 if(!old)await env.DB.prepare('INSERT INTO jev_grades(id,review_id,request_key,request_hash,score,agreement,comment,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id('jgrade_'),rid,input.requestKey,hash,input.score,input.agreement,redact(input.comment),actor.id,now()).run();return jevDetail(env,actor,rid);}
export async function restoreJevPage(env,actor,rid,input){await supportAccess(env,actor,true);fields(input,['requestKey','reason','expectedRevision','expectedArchiveId']);key(input.requestKey);if(!txt(input.reason,1000)||input.reason.trim().length<3)fail('Explain the human override.');const r=await read(env,rid);if(r.evaluation_only)fail('Synthetic evaluations cannot change page visibility.',409);const hash=await commerceHash({rid,actor:actor.id,input});
 const old=await env.DB.prepare('SELECT request_hash FROM jev_page_actions WHERE request_key=?').bind(input.requestKey).first();if(old&&old.request_hash!==hash)fail('Original override details cannot change.',409);if(!old){const hold=await env.DB.prepare('SELECT h.id,r.case_id FROM jev_page_holds h JOIN jev_reviews r ON r.id=h.review_id WHERE h.seller_id=? AND h.page_id=?').bind(r.seller_id,r.page_id).first();if(!hold||hold.id!==input.expectedArchiveId||hold.case_id!==r.case_id)fail('The active archive changed. Reload before restoring.',409);const current=await page(env,r.seller_id,r.page_id);if(current.revision!==input.expectedRevision)fail('The page changed. Reload before restoring.',409);await seedJevPageRevision(env,r.seller_id,r.page_id,current.revision);try{await action(env,r,'restore','reviewer',actor.id,input.requestKey,redact(input.reason),hash,current.revision,input.expectedArchiveId||null).run();}catch(e){if(/jev_hold_changed|jev_page_revision_changed/.test(String(e)))fail('The page or active archive changed. Reload before restoring.',409);throw e;}}return jevDetail(env,actor,rid);}

/** Signed operator import of the capped synthetic benchmark; never a real-page verdict. */
export async function importJevEvaluation(env,input){
 if(!['test','beta'].includes(env.APP_ENVIRONMENT))fail('Synthetic evaluation import is restricted to workbench.',403);
 fields(input,['requestKey','records']);key(input.requestKey);if(!Array.isArray(input.records)||input.records.length!==6)fail('Import exactly six synthetic cases.');
 const seller=await env.DB.prepare("SELECT id,slug FROM sellers WHERE id=? AND status='active'").bind(env.JEV_EVALUATION_SELLER_ID||'').first();if(!seller)fail('Configured private evaluation store is required.',503);
 const statements=[],ids=[];let index=0;
 for(const record of input.records){fields(record,['caseId','title','input','result','expectedVerdict']);if(!txt(record.caseId,70)||!/^[a-z0-9-]+$/.test(record.caseId)||!txt(record.title,120))fail('Synthetic case identity is invalid.');
  const snap=record.input;if(!snap||!Array.isArray(snap.sources)||snap.sources.length<1||snap.sources.length>6||snap.sources.some(s=>!txt(s.id,32)||!txt(s.text,3000))||!txt(snap.report?.text,1200)||!snap.coverage||snap.coverage.textOnly!==true)fail('Synthetic source is invalid.');
  const result=record.result;fields(result,['outcome','providerId','costMicrousd','inputTokens','outputTokens','failureCode','rejectedOutput']);if(result.outcome!==null)normalizeJevOutcome(result.outcome,snap,{historical:true});else if(typeof result.failureCode!=='string'||!/^jev_[a-z_]+$/.test(result.failureCode))fail('Rejected synthetic outcome needs its original validation reason.');
  if((result.providerId!==null&&!txt(result.providerId,160))||![result.costMicrousd,result.inputTokens,result.outputTokens].every(v=>v===null||Number.isSafeInteger(v)&&v>=0)||result.costMicrousd>10000)fail('Synthetic provider evidence is invalid.');
  const payload=jevRequest(snap,snap.report.text,JEV_POLICY),digest=await commerceHash({batch:input.requestKey,index:index++,record}),requestKey=(await commerceHash(input.requestKey+record.caseId)).slice(0,32),rid='jev_'+digest.slice(0,32),caseId='jcase_'+digest.slice(0,32),attempt='jrun_'+digest.slice(0,32),at=now();ids.push(rid);
  const old=await env.DB.prepare('SELECT id,request_hash FROM jev_reviews WHERE request_key=?').bind(requestKey).first();if(old){if(old.request_hash!==digest)fail('Original benchmark import cannot change.',409);continue;}
  statements.push(env.DB.prepare('INSERT INTO jev_cases(id,seller_id,page_id,store_slug,evaluation_only,created_by,request_key,request_hash,created_at,deadline_at) VALUES(?,?,?,?,1,?,?,?,?,?)').bind(caseId,seller.id,'synthetic-'+record.caseId.slice(0,35),'Synthetic evaluation','benchmark-import',requestKey,digest,at,at),
   env.DB.prepare('INSERT INTO jev_reviews(id,case_id,ordinal,request_key,request_hash,revision,snapshot_json,report_text,policy_version,created_by,created_at) VALUES(?,?,0,?,?,?,?,?,?,?,?)').bind(rid,caseId,requestKey,digest,'synthetic-'+record.caseId,JSON.stringify({...snap,name:record.title,expectedVerdict:['clear','needs_change','escalate'].includes(record.expectedVerdict)?record.expectedVerdict:null}),snap.report.text,JEV_POLICY,'benchmark-import',at),
   env.DB.prepare('INSERT INTO jev_attempts(id,review_id,request_key,model,request_json,budget_microusd,created_by,created_at) VALUES(?,?,?,?,?,10000,?,?)').bind(attempt,rid,requestKey,JEV_MODEL,JSON.stringify(payload),'benchmark-import',at),
   env.DB.prepare("INSERT INTO jev_results(review_id,attempt_id,state,outcome_json,provider_id,cost_microusd,input_tokens,output_tokens,created_at,failure_code,rejected_output) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(rid,attempt,result.outcome===null?'failed':'completed',result.outcome===null?null:JSON.stringify(result.outcome),result.providerId,result.costMicrousd,result.inputTokens,result.outputTokens,at,result.failureCode||null,result.rejectedOutput||null));
 }
 if(statements.length)await env.DB.batch(statements);return {reviewIds:ids,evaluationOnly:true,modelCalls:0};
}
