import test from 'node:test';
import assert from 'node:assert/strict';
import {setupCommerceFixture} from './commerce-fixture.mjs';
const key=()=>crypto.randomUUID().replaceAll('-','');
const claims=()=>({aal:'aal2',amr:[{method:'totp',timestamp:Math.floor(Date.now()/1000)}]});
const decision={outcome:'approved',notes:'Owner contacted using existing details and bank ownership checked.',verificationReference:'private-case-1234',ownerContactVerified:true,bankOwnershipVerified:true};
test('saved bank replacement requires independent human decision; protected queue, immutable evidence and exact retries',async t=>{
 const f=await setupCommerceFixture(t,{bindings:{APP_ENVIRONMENT:'beta'}});
 const actor={id:'alice',email:'alice@example.test',proofExpiresAt:new Date(Date.now()+550000).toISOString()},path='/internal/commerce/onboarding';
 const request={environment:'production',seller:'seller_alice',actor,action:'bank',revision:1,requestKey:key(),bank:{code:'CENAIDJA',accountNumber:'000555555555',channel:'BI_FAST'},reason:'My previous account is being closed by the bank.'};
 const bank=()=>f.db.prepare("SELECT * FROM seller_onboarding_current_bank WHERE seller_id='seller_alice'").first();
 const old=await bank();
 assert.equal((await f.call(path,{...request,reason:''})).status,422);
 const submitted=await f.call(path,request);assert.equal(submitted.status,200,submitted.error);assert.equal(submitted.onboarding.bankChange.status,'pending');assert.equal(submitted.onboarding.bank.revision,1);assert.equal((await bank()).account_number,old.account_number);
 const id=submitted.onboarding.bankChange.id;
 assert.equal((await f.call(path,request)).onboarding.bankChange.id,id);
 assert.equal((await f.call(path,{...request,bank:{...request.bank,accountNumber:'99999999'}})).status,409);
 assert.equal((await f.call(path,{...request,requestKey:key()})).status,409);
 await assert.rejects(f.db.prepare(`INSERT INTO seller_onboarding_banks SELECT seller_id,revision+1,?,request_hash,owner_auth_id,bank_code,'88888888',channel,proof_expires_at,created_at FROM seller_onboarding_current_bank WHERE seller_id='seller_alice'`).bind(key()).run(),/bank_change_review_required/);
 const route='/v1/support/bank-changes',review=(body,extra={})=>f.merchant(route+'/'+id,body,{seller:'bob',claims:claims(),method:body?'POST':'GET',...extra});
 assert.equal((await review()).status,403);
 const permit=async(id,role)=>f.db.prepare("INSERT INTO commerce_support_permissions(id,commerce_environment,auth_user_id,role,request_key,request_hash,operator,reason,created_at) VALUES(?,'production',?,?,?,'test','operator','Test review permission',?)").bind(key(),id,role,key(),new Date().toISOString()).run();
 await permit('bob','viewer');assert.equal((await review(decision)).status,403);
 await permit('bob','reviewer');await permit('alice','reviewer');
 assert.equal((await review(undefined,{claims:{aal:'aal1'}})).status,401);
 assert.equal((await review(decision,{claims:{aal:'aal2',amr:[{method:'totp',timestamp:Math.floor(Date.now()/1000)-700}]}})).status,401);
 assert.equal((await review(decision,{seller:'alice'})).status,403);
 assert.equal((await review({...decision,ownerContactVerified:false})).status,422);
 assert.equal((await review({...decision,bankOwnershipVerified:false})).status,422);
 const list=await f.merchant(route,undefined,{seller:'bob',claims:claims()});assert.equal(list.status,200,list.error);assert(!JSON.stringify(list).includes(request.bank.accountNumber));
 const detail=await review();assert.equal(detail.request.bank.accountNumber,request.bank.accountNumber);
 const approved=await review(decision);assert.equal(approved.status,200,approved.error);assert.equal(approved.request.status,'approved');assert.equal((await bank()).revision,2);assert.equal((await bank()).account_number,request.bank.accountNumber);
 assert.equal((await review(decision)).status,200);assert.equal((await bank()).revision,2);
 assert.equal((await review({...decision,outcome:'rejected'})).status,409);
 assert.equal((await f.call(path,request)).status,200);
 await assert.rejects(f.db.prepare("DELETE FROM seller_bank_change_decisions WHERE request_id=?").bind(id).run(),/onboarding_immutable/);
 const second=await f.call(path,{...request,revision:2,requestKey:key(),bank:{...request.bank,accountNumber:'7777777'}});assert.equal(second.status,200,second.error);
 const rejected=await f.merchant(route+'/'+second.onboarding.bankChange.id,{outcome:'rejected',notes:'Owner could not confirm the bank change request.'},{seller:'bob',claims:claims(),method:'POST'});assert.equal(rejected.status,200,rejected.error);assert.equal((await bank()).revision,2);
 const third=await f.call(path,{...request,revision:2,requestKey:key(),bank:{...request.bank,accountNumber:'6666666'}});assert.equal(third.status,200,third.error);
 await f.db.prepare("UPDATE seller_memberships SET role='viewer' WHERE seller_id='seller_alice' AND auth_user_id='alice'").run();
 const stale=await f.merchant(route+'/'+third.onboarding.bankChange.id,decision,{seller:'bob',claims:claims(),method:'POST'});assert.equal(stale.status,409);assert.equal((await bank()).revision,2);
 assert.equal((await f.db.prepare('SELECT count(*) AS n FROM seller_bank_change_decisions').first()).n,2,'failed approval rolls back its decision');
});
