import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {decodeHTMLAttribute,decodeHTML} from 'entities';
import {seedDeclaredOnboarding} from './onboarding-fixture.mjs';
import {setupCommerceFixture} from './commerce-fixture.mjs';
import {socialProfile,socialProfileError} from '../src/landing-social-profiles.js';
import {putJevPage} from '../src/jev-page-state.js';
import {publishDueLandingPages} from '../src/landing-page-schedule.js';

export const badProfiles=[
 'https://wa.me/123456','https://api.whatsapp.com/send?phone=123','https://whatsapp.com/channel/abc','https://example.com','https://linktr.ee/myshop','https://bit.ly/myshop','https://youtu.be/dQw4w9WgXcQ',
 'javascript:alert(1)','data:text/html,x','ftp://instagram.com/myshop','//instagram.com/myshop','https://instagram.com.evil.test/myshop','https://instagram.com@evil.test/myshop','https://user@instagram.com/myshop','https://instagram.com:444/myshop','https://instagram.com./myshop','https://%69nstagram.com/myshop',
 'https://instagram.com/p/123','https://instagram.com/reels','https://instagram.com/accounts','https://instagram.com/myshop?next=https://evil.test','https://instagram.com/myshop#bio','https://instagram.com/../myshop','https://instagram.com/%2e%2e/myshop','https://instagram.com/%2fmyshop','https://instagram.com/myshop/post','https://instagram.com\\evil.test/myshop',
 'https://tiktok.com/@myshop/video/123','https://vm.tiktok.com/abc','https://youtube.com/watch?v=dQw4w9WgXcQ','https://youtube.com/redirect?q=https://evil.test','https://facebook.com/sharer.php','https://facebook.com/profile.php?id=123456&next=evil','https://facebook.com/groups/shop','https://linkedin.com/feed','https://linkedin.com/posts/shop','https://x.com/home','https://x.com/intent/tweet','https://x.com/shop/status/123','https://pinterest.com/myshop/board','https://threads.net/@shop/post/123',
];
const good=[['instagram','http://instagram.com/my.shop/','https://www.instagram.com/my.shop'],['tiktok','https://tiktok.com/@my_shop','https://www.tiktok.com/@my_shop'],['youtube','https://youtube.com/@caf%C3%A9-shop','https://www.youtube.com/@caf%C3%A9-shop'],['youtube','https://youtube.com/@my-shop','https://www.youtube.com/@my-shop'],['youtube','https://youtube.com/channel/UC1234567890123456789012','https://www.youtube.com/channel/UC1234567890123456789012'],['facebook','https://facebook.com/my.shop','https://www.facebook.com/my.shop'],['facebook','https://facebook.com/profile.php?id=123456','https://www.facebook.com/profile.php?id=123456'],['linkedin','https://linkedin.com/company/my-shop','https://www.linkedin.com/company/my-shop'],['linkedin','https://linkedin.com/in/my-shop','https://www.linkedin.com/in/my-shop'],['x','https://twitter.com/my_shop','https://x.com/my_shop'],['pinterest','https://pinterest.com/my_shop','https://www.pinterest.com/my_shop'],['threads','https://threads.net/@my.shop','https://www.threads.com/@my.shop']];
test('shared social policy accepts bounded profiles and rejects protocol, host and path bypasses',()=>{
 for(const [provider,input,url] of good)assert.equal(socialProfile(input,provider)?.url,url,input);
 for(const input of badProfiles)assert.equal(socialProfile(input),null,input);
 assert.equal(socialProfile('@my_shop','instagram').url,'https://www.instagram.com/my_shop');assert.equal(socialProfile('https://tiktok.com/@my_shop','instagram'),null);assert.equal(socialProfile('https://instagram.com/my_shop','whatsapp'),null);
});
const commerce='<div data-native-commerce=\'{"type":"commerce","part":"add","productId":"tea"}\'><button data-commerce-add>Buy</button></div>';
const native=url=>`<nav data-native-type="social" data-sq-native='${JSON.stringify({type:'social',links:[{label:'Orders',url}]})}'><a href="${url}">Orders</a></nav>`;
const image=url=>`<section data-image-page data-image-extras='${JSON.stringify({footer:{enabled:true,links:[{label:'Orders',url}]}})}'></section><footer data-image-footer><nav class="sq-social-links"><a href="${url}">Orders</a></nav></footer>`;

test('Worker parses dedicated social nodes, canonicalizes valid profiles, omits legacy invalid links and leaves custom code intact',async t=>{
 const bundle=await build({stdin:{contents:`import {normalizeSocialHtml,validateSocialProfiles} from './src/landing-social-profiles.js';export default {async fetch(r){const {html,state}=await r.json();return Response.json({...await normalizeSocialHtml(html),validation:await validateSocialProfiles({html,state})});}}`,resolveDir:new URL('..',import.meta.url).pathname},bundle:true,write:false,format:'esm',platform:'neutral'});
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-08-11'}));t.after(()=>mf.dispose());
 const check=async html=>(await mf.dispatchFetch('http://worker.test/',{method:'POST',body:JSON.stringify({html,state:{preview:html}})})).json();
 for(const input of badProfiles){for(const surface of [native,image]){const result=await check(surface(input));assert.equal(result.validation,socialProfileError,input);assert.ok(!result.html.includes('<a '),input);const match=result.html.match(/data-(?:sq-native|image-extras)="([^"]*)"/);assert.ok(match,'Source retained for repair');const config=JSON.parse(decodeHTMLAttribute(match[1]));assert.equal((config.links||config.footer.links)[0].url,input);}}
 for(const [provider,input,url] of good){const result=await check(native(input));assert.equal(result.validation,'');assert.ok(result.html.includes(`href="${url.replaceAll('&','&amp;')}"`));assert.ok(result.html.includes(`data-social-profile="${provider}"`));assert.ok(result.html.includes('>Orders</a>'));}
 const custom='<a href="https://wa.me/123456">Existing custom contact</a><script>window.customCode="https://linktr.ee/shop"</script><nav class="sq-social-links"><a href="https://example.com">Custom navigation</a></nav>';
 const result=await check(custom+native('https://example.com'));assert.ok(result.html.startsWith(custom));assert.equal((result.html.match(/<a /g)||[]).length,2);
});

test('authenticated saves, preview caches, exports, publication and scheduled snapshots enforce only dedicated social profiles',async t=>{
 const f=await setupCommerceFixture(t);await seedDeclaredOnboarding(f.db);const bucket=await f.mf.getR2Bucket('PRIVATE_ASSETS'),id='social-profile-fixture';
 const state={version:6,preview:commerce+native('https://example.com')};let saved=await f.merchant(`/v1/landing-pages/${id}`,{name:'Social fixture',products:['tea'],customProducts:[],state});assert.equal(saved.status,200);assert.ok(!saved.page.state.preview.includes('<a '));assert.ok(saved.page.state.preview.includes('https://example.com'));
 for(const surface of [native,image]){
  const bad=commerce+surface('https://wa.me/123456');
  for(const endpoint of [`/v1/landing-pages/${id}/export`,`/v1/landing-pages/${id}`]){const response=await f.merchant(endpoint,{name:'Social fixture',status:'published',products:['tea'],customProducts:[],publishedHtml:bad,html:bad,state:{version:6,preview:bad}},{method:endpoint.endsWith('/export')?'POST':'PUT'});assert.equal(response.status,422,JSON.stringify(response));assert.match(response.error,/social network/);}
 }
 const preview='<!doctype html><html><body><main class="sq-page-preview">'+native('https://wa.me/123456')+'<a href="https://example.com/custom">Custom contact</a><script>window.customCode=true</script></main></body></html>';
 const previewResult=await f.merchant(`/v1/landing-pages/${id}/preview`,{html:preview,sourceUpdatedAt:saved.page.updatedAt},{method:'POST'});assert.equal(previewResult.status,200,JSON.stringify(previewResult));const previewKey=`sellers/seller_alice/landing-page-previews/${id}.html`;const cache=await(await bucket.get(previewKey)).text();assert.ok(!cache.includes('href="https://wa.me'));assert.ok(cache.includes('href="https://example.com/custom"'));assert.ok(cache.includes('<script>window.customCode=true</script>'));
 // Pre-policy cached previews are normalized again at interactive render time.
 await bucket.put(previewKey,preview);const interactive=await f.mf.dispatchFetch(`https://api.fixture.test/v1/landing-pages/${id}/view`,{headers:{authorization:'Bearer '+await f.merchantToken()}});assert.equal(interactive.status,200);const interactiveSource=decodeHTML((await interactive.text()).match(/srcdoc="([^"]*)"/)[1]);assert.ok(!interactiveSource.includes('href="https://wa.me'));assert.ok(interactiveSource.includes('href="https://example.com/custom"'));
 const badSchedule=await f.merchant(`/v1/landing-pages/${id}/schedule`,{action:'create',requestId:crypto.randomUUID(),sourceUpdatedAt:saved.page.updatedAt,at:new Date(Date.now()+3600000).toISOString(),timezone:'Asia/Jakarta',html:commerce+native('https://wa.me/123')},{method:'POST'});assert.equal(badSchedule.status,422);
 const html=commerce+native('http://instagram.com/myshop/');saved=await f.merchant(`/v1/landing-pages/${id}`,{state:{version:6,preview:html}});assert.equal(saved.status,200);assert.match(saved.page.state.preview,/https:\/\/www.instagram.com\/myshop/);
 const requestId=crypto.randomUUID();const scheduled=await f.merchant(`/v1/landing-pages/${id}/schedule`,{action:'create',requestId,sourceUpdatedAt:saved.page.updatedAt,at:new Date(Date.now()+3600000).toISOString(),timezone:'Asia/Jakarta',html},{method:'POST'});assert.equal(scheduled.status,200,JSON.stringify(scheduled));const key=`sellers/seller_alice/landing-pages/${id}.json`;let page=await (await bucket.get(key)).json();assert.match(page.scheduledPublication.html,/href="https:\/\/www.instagram.com\/myshop"/);
 // A pre-policy scheduled snapshot cannot bypass the recheck at execution.
 page.scheduledPublication.html=commerce+native('https://wa.me/123456');page.scheduledPublication.state={preview:page.scheduledPublication.html};const env={DB:f.db,PRIVATE_ASSETS:bucket},object=await bucket.head(key);await putJevPage(env,'seller_alice',id,object.etag,JSON.stringify(page),{customMetadata:object.customMetadata});const run=await publishDueLandingPages(env,async(_seller,html,state)=>{const response=await f.merchant(`/v1/landing-pages/${id}/export`,{html,state},{method:'POST'});if(response.status!==200)throw new Response(response.error,{status:response.status});return page.scheduledPublication.priceBaseline;},async()=>false,Date.now()+7200000);assert.equal(run.failed,1);page=await(await bucket.get(key)).json();assert.match(page.scheduledPublication.error,/social network/);
 const immediate=await f.merchant(`/v1/landing-pages/${id}`,{name:'Social fixture',status:'published',products:['tea'],customProducts:[],state:{version:6,preview:html},publishedHtml:html});assert.equal(immediate.status,200,JSON.stringify(immediate));assert.match(immediate.page.publishedHtml,/href="https:\/\/www.instagram.com\/myshop"/);page=await(await bucket.get(key)).json();
 page.status='published';page.publishedHtml=preview;const current=await bucket.head(key);await putJevPage(env,'seller_alice',id,current.etag,JSON.stringify(page),{customMetadata:current.customMetadata});const live=await f.mf.dispatchFetch('https://api.fixture.test/v1/public/landing-pages/'+saved.page.publicPath.split('/')[1]+'/'+id);assert.equal(live.status,200);const liveSource=decodeHTML((await live.text()).match(/srcdoc="([^"]*)"/)[1]);assert.ok(!liveSource.includes('href="https://wa.me'));assert.ok(liveSource.includes('href="https://example.com/custom"'));
});
